export const ICEBREAKERS = [
    "If you could have any superpower, what would it be?",
    "If you were a vegetable, what would you be?",
    "Would you rather travel 100 years into the past or 100 years into the future?",
    "Do you believe in aliens? Why or why not?",
    "If you could instantly become an expert in any subject, what would it be?",
    "If you were stranded on a desert island, what three items would you bring?",
    "If you could have any mythical creature as a pet, what would it be?",
    "If you could speak to animals, what's the first thing you'd ask?",
    "If you were a superhero, what would your name and outfit be?",
    "What's the most spontaneous thing you've ever done?",
    "What is your 'guilty pleasure' song or movie?",
    "What's the best thing you've got going on in your life at the moment?",
    "What incredibly common thing have you never done?",
    "What food do you love that a lot of people might find a little odd?",
    "If you could start a charity, what would it be for?",
    "What was the funniest thing you've seen recently online?",
    "What takes a lot of time but is totally worth it?",
    "What is the most amazing fact you know?",
    "What website or app doesn't exist, but you really wish it did?",
    "What's your favorite type of day? (weather, temp, etc.)",
    "When someone finds out what you do, or where you are from, what question do they always ask you?",
    "Are you more productive at night or in the morning?",
    "What scene in a movie always gives you goosebumps every time you watch it?",
    "What topic could you give a 20-minute presentation on without any preparation?",
    "What's something that a lot of people are missing out on because they don't know about it?",
    "What are some of your guilty pleasures?",
    "Who is the most interesting person you've met and talked with?",
    "How did you spend the money from your very first job?",
    "What do you wish someone taught you a long time ago?",
    "Do you think you rely too heavily on your phone? Why or why not?",
    "What subjects should be taught in school but aren't?",
    "What's the biggest vehicle you've driven?",
    "What songs would be played on a loop in hell?",
    "What kind of challenges are you facing these days?",
    "What do you highly recommend to most people you meet?",
    "Do you think you have a pretty good work-life balance?",
    "What was the last thing you were really excited about?",
    "What does your perfect breakfast look like?",
    "If you could choose your dreams, what would you prefer to dream about?",
    "What tells you the most about a person?",
    "What book had the most significant impact on you?",
    "What is the best event you've attended?",
    "What's your favorite food combination?",
    "What's the weirdest way you have met someone?",
    "What's the most amazing natural occurrence you've witnessed?",
    "How did you get that scar of yours?",
    "What do you wish was illegal?",
    "If someone came up to you and said 'Hey, do that thing you do!', what thing would pop into your head first?",
    "Who is the most intelligent or creative person you know?",
    "What wastes the most time in your day to day life?",
    "What's a problem you have, that might be entirely unique to you?",
    "Would you ever try space tourism, if you had the money for it?",
    "What are you grateful for?",
    "What hobby would you be a lot of fun to get into?",
    "What do you resent paying for most?",
    "What's the best or worst prank you've played on someone?",
    "What motivates you?",
    "Where are five places you really want to visit before you die?",
    "What skill or talent would you most like to learn?",
    "What weird thing do you have nostalgia for?",
    "What do you wish your phone could do?",
    "If you could rename yourself, what name would you choose?",
    "What's the most useless talent you have?",
    "What's the best piece of advice you've ever received?",
    "If you could live in any fictional world, where would it be?",
    "What's your 'go-to' karaoke song?",
    "What would the title of your autobiography be?",
    "If you could swap lives with anyone for a day, who would it be?",
    "What's the most beautiful place you've ever been to?",
    "What's your favorite way to spend a rainy day?",
    "If you could witness any event in history, what would it be?",
    "What's the most underrated movie or TV show?",
    "If you could be any age for the rest of your life, what would it be?",
    "What's the best gift you've ever given or received?",
    "What's something you're looking forward to this year?",
    "If you could have dinner with any historical figure, who would it be?",
    "What's your favorite childhood memory?",
    "What's the most adventurous thing you've ever eaten?",
    "What would you do if you won a billion dollars tomorrow?",
    "What's your favorite thing about yourself?",
    "If you could change one thing about the world, what would it be?",
    "What's the most important quality in a friend?",
    "What's your favorite smell?",
    "If you were a color, what color would you be and why?",
    "What's the best concert you've ever been to?",
    "If you could travel anywhere right now, where would it be?",
    "What's your favorite book and why?",
    "What's the biggest risk you've ever taken?",
    "What's your favorite season and why?",
    "If you could meet your future self, what one question would you ask?",
    "What's the most meaningful object you own?",
    "What's your favorite way to de-stress?",
    "If you could master any martial art, which one would it be?",
    "What's the most interesting tradition your family has?",
    "What's your favorite thing to cook (or eat)?",
    "If you could have a conversation with your pet, what would it talk about?",
    "What's the most surprising thing you've learned recently?",
    "What's your favorite quote?",
    "If you could visit any planet, which one would it be?",
    "What's the most creative thing you've ever done?",
    "What's your favorite way to start the day?",
    "If you could instantly become fluent in any language, which would it be?",
    "What's the weirdest food you've ever tried and actually liked?",
    "If you had to live in a TV show universe for a month, which one would it be?",
    "What's the most unusual talent you have?",
    "If you could have dinner with any fictional character, who would it be?",
    "What's the strangest thing you've ever bought just because it was on sale?",
    "Which song do you secretly know every word to?",
    "If you could travel anywhere right now with no cost or restrictions, where would you go?",
    "What's a habit you picked up that you're secretly proud of?",
    "Have you ever had a dream that felt more real than reality?",
    "If you could swap lives with one person for a day, who would it be?",
    "What's a movie you can quote line for line?",
    "If you could ask one question to your future self, what would it be?",
    "What's the funniest thing that has happened to you recently?",
    "Which fictional world would you most like to live in for a week?",
    "Do you prefer adventures in the city or in nature?",
    "What's the most random fact you know?",
    "What's a hobby you've always wanted to try but haven't yet?",
    "If you could be on any game show, which would you choose?",
    "What's the most unusual pet you've ever had or wanted?",
    "If you could instantly master any instrument, which would it be?",
    "What's your favorite breakfast food and why?",
    "Have you ever experienced a coincidence that was too crazy to be random?",
    "If you could witness any historical event, which would it be?",
    "What's the most ridiculous argument you've ever had?",
    "Have you ever met someone famous? What happened?",
    "What's a skill you've learned that most people wouldn't guess?",
    "What's the strangest compliment you've ever received?",
    "If you could live in any time period, past or future, which would it be?",
    "What's the most memorable trip you've ever taken?",
    "What's one thing you've done that scared you but you're glad you did?",
    "If you could instantly be an expert in any subject, what would it be?",
    "What's your favorite quirky tradition or ritual?",
    "Which app or website do you use the most and why?",
    "Have you ever experienced something you couldn't explain?",
    "What's a book or movie that changed your perspective on life?",
    "What's the most unusual thing you've eaten for breakfast?",
    "If you could redesign the human body, what would you change?",
    "What's the most unexpected kindness you've ever received?",
    "If you could instantly solve any problem in the world, what would it be?",
    "What's a skill you wish you could teach everyone?",
    "Have you ever had an embarrassing moment that you can now laugh about?",
    "What's your favorite guilty pleasure TV show or movie?",
    "What's a game you've spent way too much time playing?",
    "If you could invent a new holiday, what would it celebrate?",
    "Have you ever witnessed something completely bizarre in public?",
    "What's your favorite smell and why?",
    "If you could teleport anywhere for 24 hours, where would you go?",
    "What's the weirdest tradition your family has?",
    "What's one habit you want to pick up in the next year?",
    "If you could swap careers with anyone, who would it be?",
    "What's the funniest thing that's ever happened at work or school?",
    "What's a conspiracy theory you secretly find fascinating?",
    "Which song or band could you listen to on repeat forever?",
    "Have you ever had a supernatural or unexplained experience?",
    "What's the most ridiculous thing you've convinced someone to believe?",
    "If you could instantly redesign your city, what would you add?",
    "What's a skill or talent you think everyone should try once?",
    "What's a movie that makes you cry every time?",
    "Have you ever tried a challenge or activity just because everyone else was doing it?",
    "What's your favorite urban legend or myth?",
    "If you could be invisible for a day, what would you do?",
    "What's a food combination you swear by that others think is weird?",
    "If you could live anywhere in the world for a year, where would it be?",
    "What's the most unusual compliment you've given or received?",
    "What's one piece of advice you'd give your younger self?",
    "What's the strangest coincidence you've ever experienced?",
    "If you could have a conversation with any animal, which would it be?",
    "Have you ever accidentally embarrassed yourself in front of someone important?",
    "What's the most fascinating fact you've learned recently?",
    "If you could instantly redo one day in your life, which would it be?",
    "Have you ever experienced something that completely changed your perspective?",
    "What's your favorite random act of kindness you've witnessed?",
    "If you could spend a day as someone else, who would it be?",
    "What's the weirdest dream you can remember?",
    "Have you ever met someone and instantly felt like you knew them forever?",
    "What's a tradition you want to start yourself?",
    "If you could create a new sport, what would it involve?",
    "What's your favorite hidden spot in your city or town?",
    "Have you ever stumbled upon a secret place or event by accident?",
    "If you could instantly acquire a new language, which would it be?",
    "What's the funniest thing you've overheard in public?",
    "If you could witness any invention being created, which would it be?",
    "What's one thing you've learned that completely blew your mind?",
    "Have you ever seen something that made you question reality?",
    "If you could relive one moment in your life just to experience it again, what would it be?",
    "What's a weird habit you secretly enjoy?",
    "Have you ever had a moment of serendipity you'll never forget?",
    "If you could instantly become famous, what would you be famous for?",
    "What's the most interesting thing you've discovered about a friend recently?",
    "What's a challenge you've faced that you're proud of overcoming?",
    "If you could live inside any book or movie world, which would it be?",
    "What's the most creative or unusual gift you've given someone?",
    "What's a talent you wish you had as a child?",
    "If you could have unlimited access to one type of entertainment, what would it be?",
    "What's the strangest thing you've done for a dare or challenge?",
    "What's the most random adventure you've ever gone on?",
    "What's a smell that instantly takes you back in time?",
    "If you could meet any artist, living or dead, who would it be?",
    "What's one experience you think everyone should try at least once?",
    "What's the funniest or most awkward conversation you've had with a stranger?",
    "If you could instantly be famous for one thing, what would it be?",
    "What's the most random skill you've picked up in life?",
    "What's a question you love asking people to get to know them?",
    "What's a habit you've developed that you're proud of?"
];

let remainingIcebreakers = [];

/**
 * Shuffles an array in place using Durstenfeld shuffle algorithm
 */
const shuffleArray = (array) => {
    for (let i = array.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
};

export const getRandomIcebreaker = () => {
    if (remainingIcebreakers.length === 0) {
        remainingIcebreakers = shuffleArray([...ICEBREAKERS]);
    }
    return remainingIcebreakers.pop();
};
