export const TRIVIA_PART2 = {
  "History & Arts": [
    { question: "Which ancient wonder was located in Alexandria, Egypt?", options: ["Colossus of Rhodes", "Lighthouse of Alexandria", "Hanging Gardens", "Temple of Artemis"], answer: 1 },
    { question: "Who painted the Sistine Chapel ceiling?", options: ["Leonardo da Vinci", "Raphael", "Michelangelo", "Donatello"], answer: 2 },
    { question: "In which year did World War I begin?", options: ["1912", "1914", "1916", "1918"], answer: 1 },
    { question: "Which empire was ruled by Julius Caesar?", options: ["Greek Empire", "Ottoman Empire", "Roman Empire", "Byzantine Empire"], answer: 2 },
    { question: "The French Revolution began in which year?", options: ["1776", "1789", "1799", "1804"], answer: 1 },
    { question: "Who sculpted the statue of David?", options: ["Raphael", "Michelangelo", "Bernini", "Donatello"], answer: 1 },
    { question: "Which treaty ended World War I?", options: ["Treaty of Paris", "Treaty of Utrecht", "Treaty of Versailles", "Treaty of Westphalia"], answer: 2 },
    { question: "The ancient city of Carthage was located in modern-day which country?", options: ["Libya", "Algeria", "Tunisia", "Morocco"], answer: 2 },
    { question: "Who painted 'The Starry Night'?", options: ["Paul Gauguin", "Claude Monet", "Vincent van Gogh", "Pablo Picasso"], answer: 2 },
    { question: "Which pharaoh built the Great Pyramid of Giza?", options: ["Tutankhamun", "Ramesses II", "Khufu", "Cleopatra"], answer: 2 },
    { question: "The Magna Carta was signed in which year?", options: ["1066", "1215", "1348", "1492"], answer: 1 },
    { question: "Who was the first emperor of China?", options: ["Kublai Khan", "Sun Yat-sen", "Qin Shi Huang", "Wu Zetian"], answer: 2 },
    { question: "Leonardo da Vinci painted the Mona Lisa in which century?", options: ["14th", "15th", "16th", "17th"], answer: 2 },
    { question: "The Battle of Waterloo was fought in which year?", options: ["1805", "1812", "1815", "1820"], answer: 2 },
    { question: "Which museum houses the Mona Lisa?", options: ["British Museum", "Uffizi Gallery", "Louvre", "Prado"], answer: 2 },
    { question: "The Roman Colosseum was completed in which year AD?", options: ["50", "80", "100", "120"], answer: 1 },
    { question: "Who led the Cuban Revolution?", options: ["Che Guevara", "Fidel Castro", "Fulgencio Batista", "José Martí"], answer: 1 },
    { question: "Which civilization built Machu Picchu?", options: ["Aztec", "Maya", "Inca", "Olmec"], answer: 2 },
    { question: "The Renaissance period began in which country?", options: ["France", "Spain", "England", "Italy"], answer: 3 },
    { question: "Who wrote 'The Art of War'?", options: ["Confucius", "Sun Tzu", "Lao Tzu", "Mencius"], answer: 1 },
    { question: "Which explorer first circumnavigated the globe?", options: ["Christopher Columbus", "Vasco da Gama", "Ferdinand Magellan", "James Cook"], answer: 2 },
    { question: "The Parthenon is located in which city?", options: ["Rome", "Athens", "Istanbul", "Cairo"], answer: 1 },
    { question: "Who painted 'Girl with a Pearl Earring'?", options: ["Rembrandt", "Vermeer", "Rubens", "Van Dyck"], answer: 1 },
    { question: "The Boston Tea Party occurred in which year?", options: ["1770", "1773", "1776", "1783"], answer: 1 },
    { question: "Which empire was known as the 'Sick Man of Europe'?", options: ["Russian Empire", "Austro-Hungarian Empire", "Ottoman Empire", "Spanish Empire"], answer: 2 },
    { question: "Who was the first woman to win a Nobel Prize?", options: ["Rosalind Franklin", "Marie Curie", "Ada Lovelace", "Florence Nightingale"], answer: 1 },
    { question: "The Impressionist art movement began in which country?", options: ["Germany", "England", "France", "Netherlands"], answer: 2 },
    { question: "Which ancient Greek historian is called the 'Father of History'?", options: ["Thucydides", "Plutarch", "Herodotus", "Xenophon"], answer: 2 },
    { question: "The Berlin Wall fell in which year?", options: ["1987", "1988", "1989", "1991"], answer: 2 },
    { question: "Who painted 'The Last Supper'?", options: ["Michelangelo", "Raphael", "Leonardo da Vinci", "Titian"], answer: 2 },
    { question: "Which ancient wonder was a statue of the sun god at Rhodes?", options: ["Colossus of Rhodes", "Statue of Zeus", "Lighthouse of Alexandria", "Temple of Artemis"], answer: 0 },
    { question: "Napoleon Bonaparte was born in which island?", options: ["Sardinia", "Sicily", "Corsica", "Malta"], answer: 2 },
    { question: "The Hagia Sophia was originally built as which type of structure?", options: ["Mosque", "Palace", "Christian cathedral", "Forum"], answer: 2 },
    { question: "Who was the Egyptian queen famously associated with Julius Caesar and Mark Antony?", options: ["Nefertiti", "Hatshepsut", "Cleopatra VII", "Isis"], answer: 2 },
    { question: "Which artist created 'The Persistence of Memory' with melting clocks?", options: ["René Magritte", "Salvador Dalí", "Max Ernst", "Joan Miró"], answer: 1 },
    { question: "The Hundred Years' War was fought between England and which country?", options: ["Spain", "France", "Germany", "Portugal"], answer: 1 },
    { question: "Who built the Taj Mahal?", options: ["Akbar", "Aurangzeb", "Shah Jahan", "Humayun"], answer: 2 },
    { question: "The ancient city of Troy was located in modern-day which country?", options: ["Greece", "Turkey", "Lebanon", "Syria"], answer: 1 },
    { question: "Pablo Picasso co-founded which art movement?", options: ["Surrealism", "Fauvism", "Cubism", "Dadaism"], answer: 2 },
    { question: "The Russian Revolution that brought the Bolsheviks to power occurred in which year?", options: ["1905", "1915", "1917", "1919"], answer: 2 },
    { question: "Which architect designed the Eiffel Tower?", options: ["Gustave Eiffel", "Hector Guimard", "Charles Garnier", "Eugène Viollet-le-Duc"], answer: 0 },
    { question: "The Code of Hammurabi is associated with which ancient civilization?", options: ["Egyptian", "Persian", "Babylonian", "Sumerian"], answer: 2 },
    { question: "Who was the first Roman emperor?", options: ["Julius Caesar", "Augustus", "Nero", "Caligula"], answer: 1 },
    { question: "The Uffizi Gallery is located in which Italian city?", options: ["Rome", "Venice", "Florence", "Milan"], answer: 2 },
    { question: "Which empire built the Silk Road trading network?", options: ["Mongol Empire", "Roman Empire", "Han Dynasty", "Persian Empire"], answer: 2 },
    { question: "Who painted 'Guernica', depicting the bombing of a Basque town?", options: ["Salvador Dalí", "Pablo Picasso", "Joan Miró", "Francis Bacon"], answer: 1 },
    { question: "The Battle of Thermopylae involved warriors from which Greek city-state?", options: ["Athens", "Corinth", "Thebes", "Sparta"], answer: 3 },
    { question: "The Declaration of Independence was signed in which year?", options: ["1774", "1775", "1776", "1777"], answer: 2 },
    { question: "Which ancient structure is also known as the 'Great Wall'?", options: ["Hadrian's Wall", "Great Wall of China", "Aurelian Wall", "Antonine Wall"], answer: 1 },
    { question: "Rembrandt was a master painter from which country?", options: ["Belgium", "Germany", "Netherlands", "Denmark"], answer: 2 },
    { question: "The Peloponnesian War was fought between Athens and which city-state?", options: ["Corinth", "Thebes", "Macedon", "Sparta"], answer: 3 },
    { question: "Which king of England had six wives?", options: ["Henry VII", "Henry VIII", "Edward VI", "Richard III"], answer: 1 },
    { question: "The Prado Museum is located in which city?", options: ["Lisbon", "Barcelona", "Madrid", "Seville"], answer: 2 },
    { question: "Who was the leader of the Nazi Party?", options: ["Hermann Göring", "Joseph Goebbels", "Heinrich Himmler", "Adolf Hitler"], answer: 3 },
    { question: "The famous cave paintings at Lascaux are located in which country?", options: ["Spain", "France", "Germany", "Italy"], answer: 1 },
    { question: "Which ancient Greek philosopher was the teacher of Alexander the Great?", options: ["Plato", "Socrates", "Aristotle", "Pythagoras"], answer: 2 },
    { question: "The Thirty Years' War ended with which peace agreement?", options: ["Peace of Augsburg", "Treaty of Westphalia", "Peace of Utrecht", "Treaty of Münster"], answer: 1 },
    { question: "Auguste Rodin created which famous sculpture?", options: ["The Winged Victory", "The Thinker", "Ecstasy of Saint Teresa", "Perseus with the Head of Medusa"], answer: 1 },
    { question: "The Ottoman Empire's capital was which city?", options: ["Baghdad", "Cairo", "Constantinople", "Damascus"], answer: 2 },
    { question: "Which explorer reached India by sailing around Africa?", options: ["Christopher Columbus", "Ferdinand Magellan", "Vasco da Gama", "Bartolomeu Dias"], answer: 2 },
    { question: "The art style known as Baroque originated in which century?", options: ["15th", "16th", "17th", "18th"], answer: 2 },
    { question: "Who was the first President of the United States?", options: ["John Adams", "Thomas Jefferson", "Benjamin Franklin", "George Washington"], answer: 3 },
    { question: "The ancient Library of Alexandria was located in which country?", options: ["Greece", "Turkey", "Egypt", "Italy"], answer: 2 },
    { question: "Which painter is famous for water lily paintings?", options: ["Pierre-Auguste Renoir", "Edgar Degas", "Claude Monet", "Paul Cézanne"], answer: 2 },
    { question: "The Meiji Restoration occurred in which country?", options: ["China", "Korea", "Japan", "Vietnam"], answer: 2 },
    { question: "Which ancient civilization developed cuneiform writing?", options: ["Egyptian", "Greek", "Sumerian", "Phoenician"], answer: 2 },
    { question: "The Versailles Palace was built for which French king?", options: ["Louis XIII", "Louis XIV", "Louis XV", "Louis XVI"], answer: 1 },
    { question: "Who was the last Aztec emperor?", options: ["Montezuma I", "Cuauhtémoc", "Itzcoatl", "Moctezuma II"], answer: 3 },
    { question: "The Sistine Chapel is located in which city?", options: ["Rome", "Florence", "Venice", "Naples"], answer: 0 },
    { question: "Which war was sparked by the assassination of Archduke Franz Ferdinand?", options: ["World War II", "Crimean War", "World War I", "Franco-Prussian War"], answer: 2 },
    { question: "El Greco was a painter primarily associated with which country?", options: ["Greece", "Spain", "Italy", "Portugal"], answer: 1 },
  ],

  "Technology & Innovation": [
    { question: "Who is credited with inventing the World Wide Web?", options: ["Vint Cerf", "Tim Berners-Lee", "Bill Gates", "Steve Jobs"], answer: 1 },
    { question: "In which year was the first iPhone released?", options: ["2005", "2006", "2007", "2008"], answer: 2 },
    { question: "Who founded Microsoft?", options: ["Steve Jobs", "Jeff Bezos", "Elon Musk", "Bill Gates and Paul Allen"], answer: 3 },
    { question: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol", "High Transfer Text Protocol", "Hyper Transfer Text Program", "HyperText Transmission Process"], answer: 0 },
    { question: "Which programming language was created by James Gosling?", options: ["Python", "C++", "Java", "Ruby"], answer: 2 },
    { question: "The first commercial jet airliner was the de Havilland Comet, introduced in which year?", options: ["1945", "1949", "1952", "1958"], answer: 2 },
    { question: "Who invented the telephone?", options: ["Nikola Tesla", "Thomas Edison", "Alexander Graham Bell", "Guglielmo Marconi"], answer: 2 },
    { question: "What was the name of the first artificial satellite launched into orbit?", options: ["Explorer 1", "Sputnik 1", "Vanguard 1", "Luna 1"], answer: 1 },
    { question: "Python programming language was created by whom?", options: ["Linus Torvalds", "Guido van Rossum", "Dennis Ritchie", "Bjarne Stroustrup"], answer: 1 },
    { question: "Which company developed the Android operating system?", options: ["Apple", "Microsoft", "Google", "Samsung"], answer: 2 },
    { question: "The first computer bug was discovered in which decade?", options: ["1930s", "1940s", "1950s", "1960s"], answer: 1 },
    { question: "Who invented the steam engine that powered the Industrial Revolution?", options: ["George Stephenson", "James Watt", "Richard Trevithick", "Thomas Newcomen"], answer: 1 },
    { question: "What does 'AI' stand for in technology?", options: ["Automated Intelligence", "Artificial Integration", "Artificial Intelligence", "Automated Integration"], answer: 2 },
    { question: "The Linux operating system kernel was created by whom?", options: ["Richard Stallman", "Linus Torvalds", "Dennis Ritchie", "Ken Thompson"], answer: 1 },
    { question: "In which year was Facebook founded?", options: ["2002", "2003", "2004", "2005"], answer: 2 },
    { question: "Which company manufactured the first commercially successful personal computer?", options: ["IBM", "Apple", "Commodore", "Tandy"], answer: 0 },
    { question: "Who invented the printing press with movable type?", options: ["Leonardo da Vinci", "Johannes Gutenberg", "William Caxton", "Aldus Manutius"], answer: 1 },
    { question: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Power Unit", "Core Processing Utility", "Central Program Unit"], answer: 0 },
    { question: "The first programmable computer, ENIAC, was built in which country?", options: ["United Kingdom", "Germany", "United States", "Soviet Union"], answer: 2 },
    { question: "Who co-founded Apple with Steve Jobs?", options: ["Bill Gates", "Steve Wozniak", "Paul Allen", "Larry Page"], answer: 1 },
    { question: "Which language is primarily used for styling web pages?", options: ["HTML", "JavaScript", "CSS", "PHP"], answer: 2 },
    { question: "The GPS system was originally developed for what purpose?", options: ["Commercial navigation", "Weather forecasting", "Military use", "Scientific research"], answer: 2 },
    { question: "Which company developed the first commercial database system?", options: ["IBM", "Oracle", "Microsoft", "Sybase"], answer: 0 },
    { question: "Who invented the electric light bulb?", options: ["Nikola Tesla", "Alexander Graham Bell", "Thomas Edison", "Joseph Swan"], answer: 2 },
    { question: "What does 'RAM' stand for in computing?", options: ["Read Access Memory", "Random Access Memory", "Rapid Access Module", "Remote Access Memory"], answer: 1 },
    { question: "The ARPANET, precursor to the internet, was developed in which decade?", options: ["1950s", "1960s", "1970s", "1980s"], answer: 1 },
    { question: "Which programming language is named after a 19th-century mathematician?", options: ["Python", "Java", "Ada", "COBOL"], answer: 2 },
    { question: "Who invented the radio?", options: ["Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Nikola Tesla"], answer: 2 },
    { question: "The first moon landing occurred in which year?", options: ["1967", "1968", "1969", "1970"], answer: 2 },
    { question: "Which company created the PlayStation gaming console?", options: ["Nintendo", "Sega", "Microsoft", "Sony"], answer: 3 },
    { question: "What does 'URL' stand for?", options: ["Universal Resource Locator", "Uniform Resource Locator", "Unified Reference Link", "Universal Reference Location"], answer: 1 },
    { question: "Who is known as the 'Father of Computing'?", options: ["Alan Turing", "Charles Babbage", "John von Neumann", "Konrad Zuse"], answer: 1 },
    { question: "Which social media platform is characterized by 280-character posts?", options: ["Instagram", "Facebook", "Twitter/X", "LinkedIn"], answer: 2 },
    { question: "The C programming language was developed by whom?", options: ["James Gosling", "Bjarne Stroustrup", "Dennis Ritchie", "Brian Kernighan"], answer: 2 },
    { question: "In which year was Google founded?", options: ["1996", "1997", "1998", "1999"], answer: 2 },
    { question: "What is the name of Tesla's AI-based autopilot competitor to traditional GPS?", options: ["AutoPilot", "NeuralNet Drive", "FSD (Full Self-Driving)", "Tesla Navigate"], answer: 2 },
    { question: "Who invented the transistor?", options: ["John Bardeen, Walter Brattain, and William Shockley", "Alan Turing", "Jack Kilby", "Robert Noyce"], answer: 0 },
    { question: "Which company developed the Swift programming language?", options: ["Google", "Microsoft", "Apple", "Meta"], answer: 2 },
    { question: "The World's first programmable electronic digital computer was called what?", options: ["UNIVAC", "ENIAC", "Colossus", "Z3"], answer: 1 },
    { question: "What does 'USB' stand for?", options: ["Universal Serial Bus", "Universal System Bus", "Unified Serial Bus", "Universal Storage Bus"], answer: 0 },
    { question: "Who created the Ruby programming language?", options: ["Yukihiro Matsumoto", "Guido van Rossum", "Bjarne Stroustrup", "James Gosling"], answer: 0 },
    { question: "The first commercial email service was developed in which decade?", options: ["1960s", "1970s", "1980s", "1990s"], answer: 1 },
    { question: "Which company invented the magnetic hard disk drive?", options: ["Seagate", "Western Digital", "IBM", "Hitachi"], answer: 2 },
    { question: "What is Moore's Law about?", options: ["Network bandwidth doubling every year", "Number of transistors doubling roughly every two years", "Storage capacity tripling every year", "Processing speed doubling every 18 months"], answer: 1 },
    { question: "Who co-founded Amazon?", options: ["Larry Ellison", "Jeff Bezos", "Elon Musk", "Mark Zuckerberg"], answer: 1 },
    { question: "The first video game console sold commercially was the what?", options: ["Atari 2600", "Magnavox Odyssey", "Fairchild Channel F", "Coleco Telstar"], answer: 1 },
    { question: "What does 'IoT' stand for?", options: ["Internet of Technology", "Internet of Things", "Integration of Technology", "Internet of Transfer"], answer: 1 },
    { question: "Who invented the World Wide Web browser Mosaic?", options: ["Tim Berners-Lee", "Marc Andreessen", "Brendan Eich", "Larry Page"], answer: 1 },
    { question: "Bluetooth technology was named after which historical figure?", options: ["Harald Bluetooth, a Viking king", "Bluetooth the pirate", "Blue Tooth, an ancient inventor", "King Bluetooth of Denmark"], answer: 0 },
    { question: "The programming language JavaScript was created in how many days?", options: ["5 days", "10 days", "15 days", "30 days"], answer: 1 },
    { question: "Which tech giant acquired YouTube in 2006?", options: ["Apple", "Microsoft", "Google", "Yahoo"], answer: 2 },
    { question: "What does 'VR' stand for?", options: ["Virtual Reality", "Visual Reality", "Variable Reality", "Virtual Rendering"], answer: 0 },
    { question: "Who is the founder of SpaceX?", options: ["Jeff Bezos", "Richard Branson", "Elon Musk", "Paul Allen"], answer: 2 },
    { question: "The first domain name ever registered was what?", options: ["google.com", "mit.edu", "symbolics.com", "ibm.com"], answer: 2 },
    { question: "Which company makes the Snapdragon processor?", options: ["Intel", "AMD", "Qualcomm", "NVIDIA"], answer: 2 },
    { question: "What does 'SSD' stand for?", options: ["Solid State Drive", "Super Speed Disk", "Static Storage Device", "Solid Storage Disk"], answer: 0 },
    { question: "Who invented the World Wide Web protocol HTTP?", options: ["Vint Cerf", "Tim Berners-Lee", "Bob Kahn", "Marc Andreessen"], answer: 1 },
    { question: "Which programming language is primarily used for data science and machine learning?", options: ["Java", "C++", "Python", "Ruby"], answer: 2 },
    { question: "The first commercially available smartphone was manufactured by which company?", options: ["Apple", "Nokia", "IBM", "Motorola"], answer: 2 },
    { question: "What does 'API' stand for?", options: ["Application Programming Interface", "Automated Process Integration", "Application Process Interface", "Automated Programming Integration"], answer: 0 },
    { question: "Who invented the airplane?", options: ["Samuel Langley", "Otto Lilienthal", "Orville and Wilbur Wright", "Glenn Curtiss"], answer: 2 },
    { question: "The microprocessor was invented by which company?", options: ["Intel", "Motorola", "Texas Instruments", "AMD"], answer: 0 },
    { question: "What is the name of the first reusable orbital rocket successfully landed?", options: ["Falcon 9", "Atlas V", "Delta IV", "Antares"], answer: 0 },
    { question: "Which company created the Kotlin programming language?", options: ["Google", "JetBrains", "Oracle", "Microsoft"], answer: 1 },
    { question: "JPEG image format stands for what?", options: ["Joint Photographic Experts Group", "Java Photographic Encoding Group", "Joint Picture Encoding Graphics", "Java Picture Exchange Graphics"], answer: 0 },
    { question: "Who is known as the 'Father of the Internet'?", options: ["Tim Berners-Lee", "Vint Cerf", "Bob Kahn", "Both Vint Cerf and Bob Kahn"], answer: 3 },
    { question: "Which company created the first touchscreen smartphone?", options: ["Apple", "Samsung", "LG", "Sony Ericsson"], answer: 0 },
    { question: "The encryption standard RSA is named after its creators. What does the 'S' stand for?", options: ["Secure", "Shamir", "Smith", "Standard"], answer: 1 },
    { question: "Who founded Tesla, Inc.?", options: ["Elon Musk alone", "Martin Eberhard and Marc Tarpenning", "Elon Musk and Peter Thiel", "JB Straubel and Ian Wright"], answer: 1 },
    { question: "What does 'HTML' stand for?", options: ["Hyper Text Markup Language", "High Transfer Markup Language", "Hyper Transfer Markup Language", "High Text Marking Language"], answer: 0 },
  ],

  "Human Body & Health": [
    { question: "How many bones are in the adult human body?", options: ["196", "206", "216", "226"], answer: 1 },
    { question: "What is the largest organ in the human body?", options: ["Liver", "Brain", "Skin", "Lung"], answer: 2 },
    { question: "Which blood type is known as the universal donor?", options: ["A positive", "B negative", "AB positive", "O negative"], answer: 3 },
    { question: "What is the normal resting heart rate for adults?", options: ["40–60 bpm", "60–100 bpm", "100–120 bpm", "120–140 bpm"], answer: 1 },
    { question: "The human brain is approximately what percentage of body weight?", options: ["1%", "2%", "5%", "10%"], answer: 1 },
    { question: "Which vitamin is produced by the skin when exposed to sunlight?", options: ["Vitamin A", "Vitamin B12", "Vitamin C", "Vitamin D"], answer: 3 },
    { question: "How many chambers does the human heart have?", options: ["2", "3", "4", "6"], answer: 2 },
    { question: "What is the longest bone in the human body?", options: ["Tibia", "Humerus", "Femur", "Fibula"], answer: 2 },
    { question: "Which organ produces insulin?", options: ["Liver", "Kidney", "Pancreas", "Spleen"], answer: 2 },
    { question: "The human nervous system is divided into the central nervous system and what?", options: ["Peripheral nervous system", "Autonomic nervous system", "Somatic nervous system", "Enteric nervous system"], answer: 0 },
    { question: "How many pairs of chromosomes do humans have?", options: ["21", "23", "24", "46"], answer: 1 },
    { question: "Which vitamin deficiency causes scurvy?", options: ["Vitamin A", "Vitamin B1", "Vitamin C", "Vitamin D"], answer: 2 },
    { question: "The smallest bone in the human body is found in the?", options: ["Finger", "Toe", "Ear", "Nose"], answer: 2 },
    { question: "What does the acronym DNA stand for?", options: ["Deoxyribonucleic Acid", "Deoxyribose Nucleic Acid", "Dioxynucleic Acid", "Deoxyribose Nitrogen Acid"], answer: 0 },
    { question: "Which part of the brain controls balance and coordination?", options: ["Cerebrum", "Cerebellum", "Brain stem", "Hypothalamus"], answer: 1 },
    { question: "How many teeth does an adult human have (including wisdom teeth)?", options: ["28", "30", "32", "34"], answer: 2 },
    { question: "The process by which cells divide is called?", options: ["Mitosis", "Meiosis", "Osmosis", "Photosynthesis"], answer: 0 },
    { question: "What is the medical term for the collarbone?", options: ["Scapula", "Sternum", "Clavicle", "Ulna"], answer: 2 },
    { question: "Which organ is responsible for filtering blood and producing urine?", options: ["Liver", "Spleen", "Kidney", "Pancreas"], answer: 2 },
    { question: "The human body has how many muscles approximately?", options: ["200", "400", "600", "800"], answer: 2 },
    { question: "What is the medical term for the kneecap?", options: ["Tarsus", "Patella", "Fibula", "Tibia"], answer: 1 },
    { question: "Hemoglobin in red blood cells primarily transports what?", options: ["Carbon dioxide", "Oxygen", "Nutrients", "Hormones"], answer: 1 },
    { question: "Which gland is known as the 'master gland' of the endocrine system?", options: ["Thyroid", "Adrenal", "Pituitary", "Pineal"], answer: 2 },
    { question: "The immune system's B cells produce what?", options: ["Hormones", "Enzymes", "Antibodies", "Red blood cells"], answer: 2 },
    { question: "Which nutrient is the primary source of energy for the body?", options: ["Protein", "Fat", "Carbohydrates", "Vitamins"], answer: 2 },
    { question: "What is the normal human body temperature in Celsius?", options: ["35°C", "36°C", "37°C", "38°C"], answer: 2 },
    { question: "The aorta is the largest what in the human body?", options: ["Vein", "Artery", "Capillary", "Nerve"], answer: 1 },
    { question: "Which part of the eye controls the amount of light entering?", options: ["Cornea", "Retina", "Iris", "Lens"], answer: 2 },
    { question: "What is the medical term for high blood pressure?", options: ["Hypotension", "Hypertension", "Tachycardia", "Bradycardia"], answer: 1 },
    { question: "Which vitamin is essential for blood clotting?", options: ["Vitamin A", "Vitamin C", "Vitamin E", "Vitamin K"], answer: 3 },
    { question: "The human stomach produces which acid for digestion?", options: ["Sulfuric acid", "Acetic acid", "Hydrochloric acid", "Citric acid"], answer: 2 },
    { question: "What is the outer layer of skin called?", options: ["Dermis", "Hypodermis", "Epidermis", "Subcutis"], answer: 2 },
    { question: "Which mental health condition is characterized by persistent sadness and loss of interest?", options: ["Anxiety", "Depression", "Bipolar disorder", "Schizophrenia"], answer: 1 },
    { question: "The lymphatic system is part of which body system?", options: ["Digestive system", "Respiratory system", "Immune system", "Nervous system"], answer: 2 },
    { question: "What is the medical term for the voice box?", options: ["Pharynx", "Trachea", "Larynx", "Epiglottis"], answer: 2 },
    { question: "Which cell type carries oxygen in the blood?", options: ["White blood cells", "Platelets", "Red blood cells", "Plasma cells"], answer: 2 },
    { question: "Insulin regulates which substance in the blood?", options: ["Protein", "Fat", "Glucose", "Calcium"], answer: 2 },
    { question: "The human large intestine is approximately how long?", options: ["0.5 meters", "1.5 meters", "3 meters", "5 meters"], answer: 1 },
    { question: "Which organ is primarily responsible for detoxification?", options: ["Kidney", "Liver", "Spleen", "Pancreas"], answer: 1 },
    { question: "What does BMI stand for?", options: ["Body Mass Index", "Basic Metabolic Indicator", "Body Measurement Index", "Biological Mass Indicator"], answer: 0 },
    { question: "The disease diabetes mellitus involves which organ's dysfunction?", options: ["Liver", "Kidney", "Pancreas", "Thyroid"], answer: 2 },
    { question: "Which part of the brain is responsible for memory formation?", options: ["Cerebellum", "Amygdala", "Hippocampus", "Thalamus"], answer: 2 },
    { question: "What is the medical term for the windpipe?", options: ["Esophagus", "Larynx", "Bronchus", "Trachea"], answer: 3 },
    { question: "How long does it typically take for a broken bone to heal?", options: ["1–2 weeks", "2–4 weeks", "6–8 weeks", "3–6 months"], answer: 2 },
    { question: "Which mineral is most important for bone health?", options: ["Iron", "Calcium", "Potassium", "Magnesium"], answer: 1 },
    { question: "The Achilles tendon connects the calf muscle to which bone?", options: ["Fibula", "Tibia", "Talus", "Calcaneus"], answer: 3 },
    { question: "Which blood cells help in clotting?", options: ["Erythrocytes", "Leukocytes", "Thrombocytes", "Lymphocytes"], answer: 2 },
    { question: "What is the medical term for a heart attack?", options: ["Stroke", "Angina", "Myocardial infarction", "Arrhythmia"], answer: 2 },
    { question: "Which gland regulates metabolism?", options: ["Adrenal gland", "Thyroid gland", "Pituitary gland", "Parathyroid gland"], answer: 1 },
    { question: "The human small intestine is approximately how long?", options: ["2 meters", "4 meters", "6 meters", "8 meters"], answer: 2 },
    { question: "Which vitamin is primarily found in citrus fruits and helps immunity?", options: ["Vitamin A", "Vitamin B6", "Vitamin C", "Vitamin E"], answer: 2 },
    { question: "What is the name of the protein that gives skin and hair their structure?", options: ["Collagen", "Keratin", "Elastin", "Fibrin"], answer: 1 },
    { question: "Which condition involves inflammation of the joints?", options: ["Osteoporosis", "Arthritis", "Sclerosis", "Fibromyalgia"], answer: 1 },
    { question: "How many lobes does the right lung have?", options: ["2", "3", "4", "5"], answer: 1 },
    { question: "The medical term for the eardrum is?", options: ["Cochlea", "Malleus", "Tympanic membrane", "Ossicle"], answer: 2 },
    { question: "Which organ stores bile?", options: ["Liver", "Pancreas", "Gallbladder", "Spleen"], answer: 2 },
    { question: "Omega-3 fatty acids are most commonly found in which food?", options: ["Red meat", "Dairy products", "Fatty fish", "Leafy vegetables"], answer: 2 },
    { question: "What is the medical term for the shoulder blade?", options: ["Clavicle", "Scapula", "Humerus", "Sternum"], answer: 1 },
    { question: "Which condition is characterized by insufficient red blood cells?", options: ["Leukemia", "Anemia", "Hemophilia", "Thrombosis"], answer: 1 },
    { question: "The human body's pH level is normally?", options: ["6.0–6.5", "6.5–7.0", "7.35–7.45", "7.8–8.0"], answer: 2 },
    { question: "Which neurotransmitter is associated with feelings of happiness and wellbeing?", options: ["Dopamine", "Acetylcholine", "GABA", "Serotonin"], answer: 3 },
    { question: "What is the condition called when the body attacks its own tissues?", options: ["Immunodeficiency", "Autoimmune disease", "Allergy", "Inflammation"], answer: 1 },
    { question: "Which mineral is essential for producing hemoglobin?", options: ["Zinc", "Calcium", "Iron", "Magnesium"], answer: 2 },
    { question: "The medical term for nearsightedness is?", options: ["Hyperopia", "Astigmatism", "Myopia", "Presbyopia"], answer: 2 },
    { question: "Which system includes the heart, blood vessels, and blood?", options: ["Lymphatic system", "Respiratory system", "Circulatory system", "Endocrine system"], answer: 2 },
    { question: "What percentage of the human body is water approximately?", options: ["40%", "50%", "60%", "70%"], answer: 2 },
    { question: "The femur connects at the hip to which bone?", options: ["Pelvis", "Tibia", "Fibula", "Sacrum"], answer: 0 },
    { question: "Which type of muscle is found in the heart?", options: ["Skeletal muscle", "Smooth muscle", "Cardiac muscle", "Striated muscle"], answer: 2 },
    { question: "What does the abbreviation 'DNA' stand for in genetics?", options: ["Deoxyribonucleic Acid", "Dinitrogen Amino Acid", "Double Nucleic Acid", "Deoxyribose Nitrogen Acid"], answer: 0 },
    { question: "The BMR stands for what in nutrition science?", options: ["Basal Metabolic Rate", "Basic Mineral Requirement", "Body Mass Ratio", "Basal Mineral Ratio"], answer: 0 },
  ],

  "General Knowledge": [
    { question: "What is the square root of 144?", options: ["10", "11", "12", "13"], answer: 2 },
    { question: "Which country has the largest land area?", options: ["Canada", "China", "United States", "Russia"], answer: 3 },
    { question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
    { question: "How many sides does a hexagon have?", options: ["5", "6", "7", "8"], answer: 1 },
    { question: "What is the currency of Japan?", options: ["Yuan", "Won", "Yen", "Ringgit"], answer: 2 },
    { question: "The speed of light is approximately how many kilometers per second?", options: ["100,000 km/s", "200,000 km/s", "300,000 km/s", "400,000 km/s"], answer: 2 },
    { question: "Which sport uses a shuttlecock?", options: ["Tennis", "Squash", "Badminton", "Ping pong"], answer: 2 },
    { question: "What is the largest ocean on Earth?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], answer: 3 },
    { question: "Who wrote 'Romeo and Juliet'?", options: ["Charles Dickens", "William Shakespeare", "Jane Austen", "Geoffrey Chaucer"], answer: 1 },
    { question: "What is the value of Pi to two decimal places?", options: ["3.12", "3.14", "3.16", "3.18"], answer: 1 },
    { question: "Which country's flag features a maple leaf?", options: ["Australia", "New Zealand", "Canada", "Ireland"], answer: 2 },
    { question: "The world record for the 100m sprint is held by whom?", options: ["Carl Lewis", "Usain Bolt", "Asafa Powell", "Tyson Gay"], answer: 1 },
    { question: "What is the unit of electrical resistance?", options: ["Volt", "Ampere", "Watt", "Ohm"], answer: 3 },
    { question: "How many players are on a standard soccer team on the field?", options: ["9", "10", "11", "12"], answer: 2 },
    { question: "Which element has the chemical symbol 'O'?", options: ["Gold", "Osmium", "Oxygen", "Oganesson"], answer: 2 },
    { question: "What is the currency of the United Kingdom?", options: ["Euro", "Dollar", "Pound Sterling", "Franc"], answer: 2 },
    { question: "The idiom 'break the ice' means to?", options: ["Destroy something", "Initiate conversation in an awkward situation", "Work very hard", "Make a mistake"], answer: 1 },
    { question: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], answer: 2 },
    { question: "Which language has the most native speakers worldwide?", options: ["English", "Spanish", "Hindi", "Mandarin Chinese"], answer: 3 },
    { question: "The Great Barrier Reef is located off the coast of which country?", options: ["South Africa", "New Zealand", "Brazil", "Australia"], answer: 3 },
    { question: "What does the idiom 'bite the bullet' mean?", options: ["Eat something bad", "Endure a painful or difficult situation", "Make a wrong decision", "Be very aggressive"], answer: 1 },
    { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], answer: 2 },
    { question: "Which planet is known as the Red Planet?", options: ["Venus", "Jupiter", "Mars", "Saturn"], answer: 2 },
    { question: "The currency of India is the?", options: ["Taka", "Rupee", "Baht", "Peso"], answer: 1 },
    { question: "What is the highest mountain in the world?", options: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"], answer: 2 },
    { question: "Which sport is played at Wimbledon?", options: ["Cricket", "Golf", "Tennis", "Squash"], answer: 2 },
    { question: "What does the idiom 'cost an arm and a leg' mean?", options: ["Physical injury", "Very expensive", "Hard work", "A long journey"], answer: 1 },
    { question: "How many zeros are in one million?", options: ["4", "5", "6", "7"], answer: 2 },
    { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Brisbane", "Canberra"], answer: 3 },
    { question: "The metric unit of length equal to 1000 meters is called?", options: ["Hectometer", "Decameter", "Kilometer", "Megameter"], answer: 2 },
    { question: "Which flag features a red circle on a white background?", options: ["South Korea", "Japan", "China", "Singapore"], answer: 1 },
    { question: "What is the chemical symbol for water?", options: ["WO", "HO", "H2O", "H2O2"], answer: 2 },
    { question: "Which athlete won the most Olympic gold medals in history?", options: ["Carl Lewis", "Mark Spitz", "Michael Phelps", "Usain Bolt"], answer: 2 },
    { question: "What is 15% of 200?", options: ["25", "30", "35", "40"], answer: 1 },
    { question: "The Amazon River is located on which continent?", options: ["Africa", "Asia", "North America", "South America"], answer: 3 },
    { question: "Pizza originated in which country?", options: ["Greece", "Spain", "France", "Italy"], answer: 3 },
    { question: "What does the idiom 'hit the nail on the head' mean?", options: ["Work with tools", "Be exactly right", "Be aggressive", "Work slowly"], answer: 1 },
    { question: "The currency of Brazil is?", options: ["Peso", "Dollar", "Real", "Sol"], answer: 2 },
    { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], answer: 2 },
    { question: "What is the world's most spoken language by total speakers?", options: ["Spanish", "English", "Mandarin Chinese", "Hindi"], answer: 1 },
    { question: "The Sahara Desert is located on which continent?", options: ["Asia", "Australia", "Africa", "South America"], answer: 2 },
    { question: "Which country invented sushi?", options: ["China", "Korea", "Japan", "Vietnam"], answer: 2 },
    { question: "What does 'e.g.' stand for?", options: ["English grammar", "Exempli gratia (for example)", "Et al (and others)", "Extra generally"], answer: 1 },
    { question: "How many hours are in a week?", options: ["148", "156", "168", "172"], answer: 2 },
    { question: "The currency of China is the?", options: ["Yen", "Won", "Yuan", "Baht"], answer: 2 },
    { question: "Which is the smallest country in the world by area?", options: ["Monaco", "San Marino", "Vatican City", "Liechtenstein"], answer: 2 },
    { question: "What does the idiom 'once in a blue moon' mean?", options: ["During full moon nights", "Very rarely", "During special occasions", "Frequently"], answer: 1 },
    { question: "How many cards are in a standard deck of playing cards?", options: ["48", "52", "54", "56"], answer: 1 },
    { question: "The world's tallest building as of 2024 is?", options: ["One World Trade Center", "Shanghai Tower", "Burj Khalifa", "Merdeka 118"], answer: 2 },
    { question: "Which unit measures the frequency of sound waves?", options: ["Decibel", "Hertz", "Watt", "Lumen"], answer: 1 },
    { question: "Sushi is traditionally made with which grain?", options: ["Wheat", "Barley", "Rice", "Millet"], answer: 2 },
    { question: "What is the acronym 'NASA' for?", options: ["National Aeronautics and Space Administration", "National Aerospace and Science Agency", "National Air and Space Association", "North American Space Administration"], answer: 0 },
    { question: "What does 'i.e.' stand for?", options: ["In example", "In effect", "Id est (that is)", "In essence"], answer: 2 },
    { question: "The Olympic Games are held every how many years?", options: ["2", "3", "4", "5"], answer: 2 },
    { question: "Which country is both a continent and a country?", options: ["Greenland", "Iceland", "New Zealand", "Australia"], answer: 3 },
    { question: "What is the boiling point of water at sea level in Celsius?", options: ["90°C", "95°C", "100°C", "105°C"], answer: 2 },
    { question: "The currency of South Korea is the?", options: ["Yen", "Yuan", "Won", "Baht"], answer: 2 },
    { question: "Which letter is worth 10 points in Scrabble?", options: ["Q", "Z", "X", "J"], answer: 1 },
    { question: "What does the flag of Switzerland look like?", options: ["Blue background with a white cross", "Red background with a white cross", "White background with a red cross", "Red background with a yellow cross"], answer: 1 },
    { question: "How many minutes are in 24 hours?", options: ["1,200", "1,440", "1,620", "1,800"], answer: 1 },
    { question: "Which sport uses a 'puck'?", options: ["Polo", "Lacrosse", "Field hockey", "Ice hockey"], answer: 3 },
    { question: "The idiom 'spill the beans' means to?", options: ["Make a mess", "Reveal a secret", "Waste food", "Cause trouble"], answer: 1 },
    { question: "What is the chemical symbol for iron?", options: ["Ir", "In", "Fe", "Fr"], answer: 2 },
    { question: "How many meters are in a kilometer?", options: ["10", "100", "1,000", "10,000"], answer: 2 },
    { question: "Which country is famous for inventing chocolate?", options: ["Switzerland", "Belgium", "Mexico (cacao origin)", "France"], answer: 2 },
    { question: "The longest river in the world is?", options: ["Amazon", "Mississippi", "Yangtze", "Nile"], answer: 3 },
    { question: "What number is represented by the Roman numeral 'X'?", options: ["5", "8", "10", "12"], answer: 2 },
    { question: "Which gas do plants absorb during photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], answer: 2 },
    { question: "What is the currency of Mexico?", options: ["Dollar", "Real", "Peso", "Sol"], answer: 2 },
    { question: "The idiom 'under the weather' means?", options: ["It is raining", "Feeling ill", "Being outside", "Feeling cold"], answer: 1 },
    { question: "How many players are on a basketball team on the court?", options: ["4", "5", "6", "7"], answer: 1 },
  ],
};
