export const TRIVIA_PART1 = {
  "Science & Space": [
    { question: "What is the speed of light in a vacuum?", options: ["299,792,458 m/s", "199,792,458 m/s", "399,792,458 m/s", "499,792,458 m/s"], answer: 0 },
    { question: "What is the chemical symbol for gold?", options: ["Go", "Gd", "Au", "Ag"], answer: 2 },
    { question: "How many planets are in our solar system?", options: ["7", "8", "9", "10"], answer: 1 },
    { question: "What force keeps planets in orbit around the Sun?", options: ["Magnetism", "Friction", "Gravity", "Electrostatic force"], answer: 2 },
    { question: "What is the largest planet in our solar system?", options: ["Saturn", "Neptune", "Uranus", "Jupiter"], answer: 3 },
    { question: "What is the atomic number of carbon?", options: ["6", "8", "12", "14"], answer: 0 },
    { question: "Which scientist formulated the theory of general relativity?", options: ["Isaac Newton", "Niels Bohr", "Albert Einstein", "Max Planck"], answer: 2 },
    { question: "What is the nearest star to Earth?", options: ["Sirius", "Alpha Centauri A", "Proxima Centauri", "Betelgeuse"], answer: 2 },
    { question: "What is the chemical formula for water?", options: ["HO", "H2O", "H3O", "HO2"], answer: 1 },
    { question: "What planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], answer: 1 },
    { question: "What is DNA an abbreviation for?", options: ["Deoxyribonucleic Acid", "Diribonuclear Acid", "Deoxyribonitric Acid", "Dinucleic Acid"], answer: 0 },
    { question: "How many moons does Mars have?", options: ["0", "1", "2", "4"], answer: 2 },
    { question: "What is the most abundant gas in Earth's atmosphere?", options: ["Oxygen", "Carbon Dioxide", "Argon", "Nitrogen"], answer: 3 },
    { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria", "Golgi apparatus"], answer: 2 },
    { question: "Which element has the symbol 'Fe'?", options: ["Fluorine", "Iron", "Fermium", "Francium"], answer: 1 },
    { question: "What is the boiling point of water at sea level in Celsius?", options: ["90°C", "95°C", "100°C", "105°C"], answer: 2 },
    { question: "What mission first landed humans on the Moon?", options: ["Apollo 10", "Apollo 11", "Apollo 12", "Gemini 7"], answer: 1 },
    { question: "What is the smallest planet in our solar system?", options: ["Mars", "Venus", "Mercury", "Pluto"], answer: 2 },
    { question: "How many bones are in the adult human body?", options: ["186", "196", "206", "216"], answer: 2 },
    { question: "What is the unit of electrical resistance?", options: ["Volt", "Ampere", "Ohm", "Watt"], answer: 2 },
    { question: "Which planet has the most moons?", options: ["Jupiter", "Saturn", "Uranus", "Neptune"], answer: 1 },
    { question: "What is the chemical symbol for oxygen?", options: ["Ox", "O2", "O", "Om"], answer: 2 },
    { question: "What type of galaxy is the Milky Way?", options: ["Elliptical", "Irregular", "Barred spiral", "Ring"], answer: 2 },
    { question: "What is the nucleus of an atom made of?", options: ["Electrons and neutrons", "Protons and electrons", "Protons and neutrons", "Electrons only"], answer: 2 },
    { question: "What is absolute zero in Celsius?", options: ["-100°C", "-173°C", "-273.15°C", "-373°C"], answer: 2 },
    { question: "Who discovered penicillin?", options: ["Marie Curie", "Louis Pasteur", "Alexander Fleming", "Joseph Lister"], answer: 2 },
    { question: "What is the largest organ in the human body?", options: ["Liver", "Lungs", "Skin", "Brain"], answer: 2 },
    { question: "What is the speed of sound in air at 20°C approximately?", options: ["243 m/s", "343 m/s", "443 m/s", "543 m/s"], answer: 1 },
    { question: "How long does light from the Sun take to reach Earth?", options: ["About 4 minutes", "About 8 minutes", "About 12 minutes", "About 20 minutes"], answer: 1 },
    { question: "What is the most abundant element in the universe?", options: ["Helium", "Carbon", "Oxygen", "Hydrogen"], answer: 3 },
    { question: "Which planet is known for its prominent ring system?", options: ["Jupiter", "Uranus", "Saturn", "Neptune"], answer: 2 },
    { question: "What is the chemical symbol for silver?", options: ["Si", "Sv", "Ag", "Au"], answer: 2 },
    { question: "What is Newton's first law of motion called?", options: ["Law of acceleration", "Law of inertia", "Law of action-reaction", "Law of gravity"], answer: 1 },
    { question: "What particle has a negative charge?", options: ["Proton", "Neutron", "Positron", "Electron"], answer: 3 },
    { question: "What does NASA stand for?", options: ["National Aeronautics and Space Administration", "National Air and Space Agency", "North American Space Association", "National Aerospace Science Administration"], answer: 0 },
    { question: "What is the hardest natural substance on Earth?", options: ["Quartz", "Corundum", "Diamond", "Titanium"], answer: 2 },
    { question: "How many chromosomes do humans have?", options: ["23", "44", "46", "48"], answer: 2 },
    { question: "What is the freezing point of water in Fahrenheit?", options: ["0°F", "16°F", "32°F", "48°F"], answer: 2 },
    { question: "What type of bond holds water molecules together (intermolecular)?", options: ["Covalent bond", "Ionic bond", "Hydrogen bond", "Metallic bond"], answer: 2 },
    { question: "What is the closest galaxy to the Milky Way?", options: ["Triangulum Galaxy", "Andromeda Galaxy", "Whirlpool Galaxy", "Sombrero Galaxy"], answer: 1 },
    { question: "Which scientist discovered gravity by observing a falling apple?", options: ["Galileo Galilei", "Albert Einstein", "Isaac Newton", "Nikola Tesla"], answer: 2 },
    { question: "What is the unit of energy?", options: ["Newton", "Pascal", "Joule", "Watt"], answer: 2 },
    { question: "What layer of Earth is the outermost solid layer?", options: ["Mantle", "Core", "Crust", "Asthenosphere"], answer: 2 },
    { question: "Which gas do plants absorb during photosynthesis?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], answer: 2 },
    { question: "What is the most common blood type in humans?", options: ["A+", "B+", "AB+", "O+"], answer: 3 },
    { question: "What is the process by which the Sun produces energy?", options: ["Nuclear fission", "Nuclear fusion", "Combustion", "Radioactive decay"], answer: 1 },
    { question: "What spacecraft was the first to leave our solar system?", options: ["Voyager 2", "Pioneer 10", "Voyager 1", "New Horizons"], answer: 2 },
    { question: "What is the chemical formula for table salt?", options: ["KCl", "NaCl", "CaCl2", "MgCl2"], answer: 1 },
    { question: "How many elements are in the periodic table (as of 2024)?", options: ["108", "112", "118", "120"], answer: 2 },
    { question: "What is the name of the first artificial satellite launched into space?", options: ["Explorer 1", "Sputnik 1", "Vanguard 1", "Luna 1"], answer: 1 },
    { question: "What force is responsible for radioactive decay?", options: ["Gravity", "Electromagnetic force", "Strong nuclear force", "Weak nuclear force"], answer: 3 },
    { question: "What is the pH of pure water?", options: ["5", "6", "7", "8"], answer: 2 },
    { question: "Which planet rotates on its side with an axial tilt of about 98 degrees?", options: ["Neptune", "Saturn", "Uranus", "Venus"], answer: 2 },
    { question: "What is the name of the boundary between Earth's crust and mantle?", options: ["Conrad Discontinuity", "Gutenberg Discontinuity", "Mohorovičić Discontinuity", "Lehmann Discontinuity"], answer: 2 },
    { question: "What is the main component of the Sun?", options: ["Helium", "Hydrogen", "Carbon", "Oxygen"], answer: 1 },
    { question: "What is the name given to a star that has collapsed into an extremely dense point?", options: ["White dwarf", "Neutron star", "Pulsar", "Black hole"], answer: 3 },
    { question: "What is the phenomenon where light bends as it passes through different media?", options: ["Reflection", "Diffraction", "Refraction", "Dispersion"], answer: 2 },
    { question: "What is the average distance from Earth to the Moon?", options: ["284,400 km", "364,400 km", "384,400 km", "404,400 km"], answer: 2 },
    { question: "What is Charles Darwin's theory known as?", options: ["Theory of relativity", "Theory of natural selection", "Theory of spontaneous generation", "Theory of inheritance"], answer: 1 },
    { question: "What is the chemical symbol for potassium?", options: ["Po", "Pt", "K", "Ka"], answer: 2 },
    { question: "What is the smallest unit of life?", options: ["Atom", "Molecule", "Cell", "Organelle"], answer: 2 },
    { question: "What type of radiation has the shortest wavelength?", options: ["Radio waves", "Infrared", "Ultraviolet", "Gamma rays"], answer: 3 },
    { question: "What is the name of the first human in space?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Alan Shepard"], answer: 2 },
    { question: "What is E=mc² known as?", options: ["Newton's second law", "Mass-energy equivalence", "Ohm's law", "Planck's law"], answer: 1 },
    { question: "What is the SI unit of temperature?", options: ["Celsius", "Fahrenheit", "Rankine", "Kelvin"], answer: 3 },
    { question: "What is the largest moon of Saturn?", options: ["Enceladus", "Rhea", "Titan", "Iapetus"], answer: 2 },
    { question: "What type of cell does not have a nucleus?", options: ["Eukaryotic", "Prokaryotic", "Plant cell", "Animal cell"], answer: 1 },
    { question: "What is the process called when a solid turns directly into a gas?", options: ["Evaporation", "Condensation", "Sublimation", "Deposition"], answer: 2 },
    { question: "What is the name of the space telescope launched in 1990?", options: ["Spitzer", "Chandra", "Hubble", "Kepler"], answer: 2 },
    { question: "What is the chemical formula for carbon dioxide?", options: ["CO", "CO2", "C2O", "C2O3"], answer: 1 },
    { question: "What is the name of the force that opposes motion between two surfaces?", options: ["Gravity", "Tension", "Friction", "Normal force"], answer: 2 },
    { question: "Which planet has the shortest day in our solar system?", options: ["Earth", "Jupiter", "Saturn", "Mars"], answer: 1 },
    { question: "What is the main function of red blood cells?", options: ["Fight infections", "Carry oxygen", "Produce antibodies", "Aid in clotting"], answer: 1 },
    { question: "What is the name of the galaxy collision expected between Milky Way and Andromeda?", options: ["Milkomeda", "Andromilk", "Milkdromeda", "Galactia"], answer: 0 },
    { question: "What quantum physicist developed the uncertainty principle?", options: ["Erwin Schrödinger", "Max Planck", "Werner Heisenberg", "Paul Dirac"], answer: 2 },
    { question: "What is the outermost layer of the Sun called?", options: ["Photosphere", "Chromosphere", "Corona", "Convection zone"], answer: 2 },
    { question: "What is the name of the positively charged particle in an atom's nucleus?", options: ["Electron", "Neutron", "Proton", "Positron"], answer: 2 },
    { question: "What gas makes up about 21% of Earth's atmosphere?", options: ["Nitrogen", "Argon", "Oxygen", "Carbon dioxide"], answer: 2 },
    { question: "What is the study of fossils called?", options: ["Archaeology", "Geology", "Palaeontology", "Mineralogy"], answer: 2 },
  ],

  "Nature & Animals": [
    { question: "What is the fastest land animal?", options: ["Lion", "Cheetah", "Greyhound", "Pronghorn"], answer: 1 },
    { question: "How many legs does a spider have?", options: ["6", "8", "10", "12"], answer: 1 },
    { question: "What is the largest animal on Earth?", options: ["African Elephant", "Blue Whale", "Giant Squid", "Whale Shark"], answer: 1 },
    { question: "What is the process by which caterpillars transform into butterflies?", options: ["Metamorphosis", "Mitosis", "Photosynthesis", "Hibernation"], answer: 0 },
    { question: "Which bird is known for its inability to fly and lives in Antarctica?", options: ["Emu", "Ostrich", "Penguin", "Kiwi"], answer: 2 },
    { question: "What is the largest land animal?", options: ["Hippopotamus", "White Rhinoceros", "African Elephant", "Giraffe"], answer: 2 },
    { question: "How do bees communicate the location of food to other bees?", options: ["By sound", "By scent alone", "By the waggle dance", "By touch"], answer: 2 },
    { question: "What is the name of the largest rainforest in the world?", options: ["Congo Rainforest", "Amazon Rainforest", "Daintree Rainforest", "Tongass Rainforest"], answer: 1 },
    { question: "What is the tallest animal in the world?", options: ["Elephant", "Giraffe", "Camel", "Moose"], answer: 1 },
    { question: "What is a group of lions called?", options: ["Pack", "Herd", "Pride", "Flock"], answer: 2 },
    { question: "How many hearts does an octopus have?", options: ["1", "2", "3", "4"], answer: 2 },
    { question: "What is the largest species of shark?", options: ["Bull shark", "Great white shark", "Tiger shark", "Whale shark"], answer: 3 },
    { question: "Which mammal can fly?", options: ["Flying squirrel", "Bat", "Flying fish", "Sugar glider"], answer: 1 },
    { question: "What is the most venomous snake in the world?", options: ["King cobra", "Inland taipan", "Black mamba", "Rattlesnake"], answer: 1 },
    { question: "What is the largest desert in the world?", options: ["Sahara Desert", "Arabian Desert", "Antarctic Desert", "Gobi Desert"], answer: 2 },
    { question: "What is the smallest bird in the world?", options: ["Bee hummingbird", "Goldcrest", "Weebill", "Brown gerygone"], answer: 0 },
    { question: "How many teeth does an adult human have (excluding wisdom teeth)?", options: ["24", "28", "32", "36"], answer: 1 },
    { question: "What is the name of the world's largest coral reef system?", options: ["Belize Barrier Reef", "Mesoamerican Reef", "Great Barrier Reef", "New Caledonia Barrier Reef"], answer: 2 },
    { question: "What is a young kangaroo called?", options: ["Cub", "Pup", "Joey", "Kit"], answer: 2 },
    { question: "Which animal has the longest lifespan?", options: ["Greenland shark", "Ocean quahog clam", "Bowhead whale", "Giant tortoise"], answer: 1 },
    { question: "What is the collective term for a group of wolves?", options: ["Pride", "Pack", "Herd", "School"], answer: 1 },
    { question: "What is the largest species of penguin?", options: ["King penguin", "Emperor penguin", "Gentoo penguin", "Chinstrap penguin"], answer: 1 },
    { question: "What is the process by which plants make food using sunlight?", options: ["Respiration", "Transpiration", "Photosynthesis", "Fermentation"], answer: 2 },
    { question: "What do you call an animal that eats only plants?", options: ["Carnivore", "Omnivore", "Herbivore", "Insectivore"], answer: 2 },
    { question: "Which animal is known as the 'King of the Jungle'?", options: ["Tiger", "Cheetah", "Leopard", "Lion"], answer: 3 },
    { question: "What is the largest species of big cat?", options: ["Lion", "Jaguar", "Tiger", "Leopard"], answer: 2 },
    { question: "What is a group of fish called?", options: ["Flock", "Pack", "School", "Colony"], answer: 2 },
    { question: "What is the most poisonous frog in the world?", options: ["Red-eyed tree frog", "Poison dart frog", "Golden poison frog", "Blue poison frog"], answer: 2 },
    { question: "How many legs does an insect have?", options: ["4", "6", "8", "10"], answer: 1 },
    { question: "What is the name of the largest living reptile?", options: ["Komodo dragon", "Saltwater crocodile", "Green anaconda", "Leatherback sea turtle"], answer: 1 },
    { question: "What is the migration route of monarch butterflies?", options: ["South America to North America", "North America to Mexico", "Europe to Africa", "Australia to Asia"], answer: 1 },
    { question: "What is the world's largest living structure?", options: ["Amazon Rainforest", "Great Barrier Reef", "Sequoia National Forest", "Daintree Rainforest"], answer: 1 },
    { question: "Which animal can regrow its limbs?", options: ["Gecko", "Salamander", "Axolotl", "Both B and C"], answer: 3 },
    { question: "What is the name for the layer of the ocean that receives no sunlight?", options: ["Photic zone", "Mesopelagic zone", "Aphotic zone", "Littoral zone"], answer: 2 },
    { question: "What is the gestation period of an elephant?", options: ["12 months", "16 months", "22 months", "28 months"], answer: 2 },
    { question: "Which bird has the largest wingspan?", options: ["Bald eagle", "Condor", "Wandering albatross", "Pelican"], answer: 2 },
    { question: "What is a baby deer called?", options: ["Calf", "Foal", "Fawn", "Kid"], answer: 2 },
    { question: "What is the most endangered big cat in the world?", options: ["Snow leopard", "Amur leopard", "Sumatran tiger", "Cheetah"], answer: 1 },
    { question: "What type of ecosystem is characterized by permafrost and very little precipitation?", options: ["Taiga", "Tundra", "Steppe", "Desert"], answer: 1 },
    { question: "What is the loudest animal on Earth?", options: ["Blue whale", "Sperm whale", "Howler monkey", "Pistol shrimp"], answer: 0 },
    { question: "What is the name of the world's most venomous jellyfish?", options: ["Portuguese man o' war", "Lion's mane jellyfish", "Box jellyfish", "Moon jellyfish"], answer: 2 },
    { question: "Which animal has the highest blood pressure?", options: ["Elephant", "Giraffe", "Blue whale", "Cheetah"], answer: 1 },
    { question: "What is the deepest part of the ocean called?", options: ["Mariana Trench", "Puerto Rico Trench", "Java Trench", "Philippine Trench"], answer: 0 },
    { question: "What is the name of the study of birds?", options: ["Herpetology", "Entomology", "Ornithology", "Ichthyology"], answer: 2 },
    { question: "What is the term for animals that are active at night?", options: ["Diurnal", "Crepuscular", "Nocturnal", "Cathemeral"], answer: 2 },
    { question: "Which animal produces the most milk relative to its body weight?", options: ["Cow", "Goat", "Rat", "Rabbit"], answer: 2 },
    { question: "What is the world's largest flower?", options: ["Titan arum", "Rafflesia arnoldii", "Victoria amazonica", "Sunflower"], answer: 1 },
    { question: "How many stomachs does a cow have?", options: ["1", "2", "3", "4"], answer: 3 },
    { question: "What is the scientific name for the snow leopard?", options: ["Panthera leo", "Panthera tigris", "Panthera uncia", "Panthera onca"], answer: 2 },
    { question: "What do pandas primarily eat?", options: ["Fish", "Bamboo", "Berries", "Insects"], answer: 1 },
    { question: "What is a group of crows called?", options: ["Flock", "Colony", "Murder", "Gaggle"], answer: 2 },
    { question: "What is the name of the world's oldest known living tree?", options: ["Methuselah", "Sherman", "Prometheus", "Jomon Sugi"], answer: 0 },
    { question: "Which sea creature has three hearts and blue blood?", options: ["Nautilus", "Horseshoe crab", "Octopus", "Cuttlefish"], answer: 2 },
    { question: "What is the fastest bird in level flight?", options: ["Peregrine falcon", "Spine-tailed swift", "Common swift", "White-throated needletail"], answer: 3 },
    { question: "Which biome is known as the 'lungs of the Earth'?", options: ["Grassland", "Coral reef", "Rainforest", "Wetlands"], answer: 2 },
    { question: "What is the name of the bird that cannot walk?", options: ["Hummingbird", "Swift", "Kingfisher", "Frigatebird"], answer: 1 },
    { question: "What animal has the longest tongue relative to its body size?", options: ["Chameleon", "Pangolin", "Tube-lipped nectar bat", "Anteater"], answer: 2 },
    { question: "How many species of bats are there approximately?", options: ["Over 200", "Over 700", "Over 1,400", "Over 2,000"], answer: 2 },
    { question: "What is the name for a female fox?", options: ["Vixen", "Vix", "She-fox", "Vixe"], answer: 0 },
    { question: "What is the process by which animals become more adapted to their environment over generations?", options: ["Evolution", "Mutation", "Adaptation", "Natural selection"], answer: 3 },
    { question: "What is the name of the world's most dangerous bird?", options: ["Ostrich", "Harpy eagle", "Cassowary", "Shoebill"], answer: 2 },
    { question: "What is the scientific study of fungi called?", options: ["Botany", "Mycology", "Phycology", "Lichenology"], answer: 1 },
    { question: "Which marine animal is known to navigate using Earth's magnetic field?", options: ["Dolphin", "Sea turtle", "Seahorse", "Clownfish"], answer: 1 },
    { question: "What is the name of the world's only venomous primate?", options: ["Slow loris", "Aye-aye", "Tarsier", "Potoo"], answer: 0 },
    { question: "What is a group of geese on land called?", options: ["Flock", "Gaggle", "Skein", "Wedge"], answer: 1 },
    { question: "What is the primary diet of the giant panda?", options: ["Fish and berries", "Bamboo shoots and leaves", "Fruits and nuts", "Insects and honey"], answer: 1 },
    { question: "What is the name for a baby swan?", options: ["Chick", "Gosling", "Cygnet", "Squab"], answer: 2 },
    { question: "Which insect is the best flier, capable of flying in all directions?", options: ["Butterfly", "Bee", "Dragonfly", "Horsefly"], answer: 2 },
    { question: "What animal has the most powerful bite force?", options: ["Lion", "Hippopotamus", "Saltwater crocodile", "Spotted hyena"], answer: 2 },
    { question: "What is the term for an ecosystem that is transitional between two biomes?", options: ["Niche", "Ecotone", "Habitat", "Microbiome"], answer: 1 },
    { question: "What color is a polar bear's skin?", options: ["White", "Pink", "Black", "Gray"], answer: 2 },
    { question: "What is the world's deadliest animal (most human deaths per year)?", options: ["Saltwater crocodile", "Hippopotamus", "Mosquito", "African lion"], answer: 2 },
    { question: "What type of animal is a Komodo dragon?", options: ["Crocodilian", "Monitor lizard", "Iguana", "Gecko"], answer: 1 },
    { question: "How do sharks detect prey in the water?", options: ["Only by sight", "Only by smell", "Electroreception and lateral line", "Only by sound"], answer: 2 },
    { question: "What is the world's largest fish?", options: ["Great white shark", "Basking shark", "Whale shark", "Giant oarfish"], answer: 2 },
    { question: "What is the name for the mass migration of wildebeest across the Serengeti?", options: ["The Great Migration", "The Serengeti Run", "The Annual Trek", "The Wildebeest Journey"], answer: 0 },
    { question: "What is the name of the process by which dead organic matter is broken down by microorganisms?", options: ["Photosynthesis", "Decomposition", "Fermentation", "Oxidation"], answer: 1 },
    { question: "Which tree produces acorns?", options: ["Maple", "Birch", "Oak", "Beech"], answer: 2 },
  ],

  "Geography & World": [
    { question: "What is the capital of Australia?", options: ["Sydney", "Melbourne", "Brisbane", "Canberra"], answer: 3 },
    { question: "What is the longest river in the world?", options: ["Amazon River", "Congo River", "Nile River", "Yangtze River"], answer: 2 },
    { question: "What is the highest mountain in the world?", options: ["K2", "Mount Kangchenjunga", "Mount Everest", "Lhotse"], answer: 2 },
    { question: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], answer: 2 },
    { question: "What is the smallest country in the world?", options: ["Monaco", "San Marino", "Liechtenstein", "Vatican City"], answer: 3 },
    { question: "What is the capital of Japan?", options: ["Osaka", "Kyoto", "Tokyo", "Hiroshima"], answer: 2 },
    { question: "Which ocean is the largest?", options: ["Atlantic Ocean", "Indian Ocean", "Arctic Ocean", "Pacific Ocean"], answer: 3 },
    { question: "What is the capital of Brazil?", options: ["Rio de Janeiro", "São Paulo", "Salvador", "Brasília"], answer: 3 },
    { question: "What is the largest country in the world by land area?", options: ["Canada", "China", "United States", "Russia"], answer: 3 },
    { question: "What is the capital of Canada?", options: ["Toronto", "Vancouver", "Ottawa", "Montreal"], answer: 2 },
    { question: "Which country has the largest population in the world?", options: ["United States", "India", "China", "Indonesia"], answer: 1 },
    { question: "What is the capital of Egypt?", options: ["Alexandria", "Luxor", "Giza", "Cairo"], answer: 3 },
    { question: "What is the longest mountain range in the world?", options: ["Himalayas", "Rocky Mountains", "Andes", "Alps"], answer: 2 },
    { question: "What is the capital of Argentina?", options: ["Montevideo", "Santiago", "Lima", "Buenos Aires"], answer: 3 },
    { question: "What is the deepest lake in the world?", options: ["Lake Superior", "Caspian Sea", "Lake Baikal", "Lake Tanganyika"], answer: 2 },
    { question: "What is the capital of South Africa?", options: ["Cape Town only", "Johannesburg", "Pretoria (executive)", "Durban"], answer: 2 },
    { question: "Which country has the most natural lakes?", options: ["Russia", "United States", "Finland", "Canada"], answer: 3 },
    { question: "What is the capital of Germany?", options: ["Munich", "Hamburg", "Frankfurt", "Berlin"], answer: 3 },
    { question: "What is the largest lake in Africa?", options: ["Lake Tanganyika", "Lake Malawi", "Lake Victoria", "Lake Turkana"], answer: 2 },
    { question: "What is the capital of India?", options: ["Mumbai", "Kolkata", "New Delhi", "Chennai"], answer: 2 },
    { question: "Which country is both a continent and a country?", options: ["Greenland", "Iceland", "Australia", "New Zealand"], answer: 2 },
    { question: "What is the capital of Mexico?", options: ["Guadalajara", "Monterrey", "Puebla", "Mexico City"], answer: 3 },
    { question: "What is the most spoken language in the world by number of native speakers?", options: ["English", "Spanish", "Mandarin Chinese", "Hindi"], answer: 2 },
    { question: "What is the capital of Russia?", options: ["St. Petersburg", "Moscow", "Novosibirsk", "Vladivostok"], answer: 1 },
    { question: "What is the Sahara Desert primarily located in?", options: ["The Middle East", "Northern Africa", "Southern Africa", "Central Africa"], answer: 1 },
    { question: "What is the capital of France?", options: ["Lyon", "Marseille", "Nice", "Paris"], answer: 3 },
    { question: "What is the largest island in the world?", options: ["Borneo", "Greenland", "Madagascar", "New Guinea"], answer: 1 },
    { question: "What is the capital of China?", options: ["Shanghai", "Guangzhou", "Beijing", "Shenzhen"], answer: 2 },
    { question: "What is the world's most visited country by international tourists?", options: ["United States", "Spain", "China", "France"], answer: 3 },
    { question: "What is the capital of Italy?", options: ["Milan", "Venice", "Florence", "Rome"], answer: 3 },
    { question: "How many countries are there in Africa?", options: ["48", "52", "54", "58"], answer: 2 },
    { question: "What is the capital of the United Kingdom?", options: ["Edinburgh", "Manchester", "Birmingham", "London"], answer: 3 },
    { question: "Which country is home to Machu Picchu?", options: ["Bolivia", "Chile", "Colombia", "Peru"], answer: 3 },
    { question: "What is the capital of Nigeria?", options: ["Lagos", "Kano", "Abuja", "Ibadan"], answer: 2 },
    { question: "What is the longest wall in the world?", options: ["Hadrian's Wall", "Great Wall of China", "Berlin Wall", "Aurelian Wall"], answer: 1 },
    { question: "What is the capital of Turkey?", options: ["Istanbul", "Izmir", "Antalya", "Ankara"], answer: 3 },
    { question: "Which river runs through Egypt?", options: ["Congo", "Zambezi", "Niger", "Nile"], answer: 3 },
    { question: "What is the capital of Spain?", options: ["Barcelona", "Seville", "Valencia", "Madrid"], answer: 3 },
    { question: "What is the smallest continent by area?", options: ["Europe", "Antarctica", "Australia", "South America"], answer: 2 },
    { question: "What is the capital of Saudi Arabia?", options: ["Jeddah", "Mecca", "Medina", "Riyadh"], answer: 3 },
    { question: "Which country owns the Galápagos Islands?", options: ["Peru", "Colombia", "Ecuador", "Chile"], answer: 2 },
    { question: "What is the capital of South Korea?", options: ["Busan", "Incheon", "Daegu", "Seoul"], answer: 3 },
    { question: "What is the name of the world's largest hot desert?", options: ["Arabian Desert", "Sahara Desert", "Gobi Desert", "Kalahari Desert"], answer: 1 },
    { question: "What is the capital of Kenya?", options: ["Mombasa", "Kisumu", "Nakuru", "Nairobi"], answer: 3 },
    { question: "What is the name of the strait between Europe and Africa?", options: ["Bosphorus", "Strait of Hormuz", "Strait of Gibraltar", "Strait of Malacca"], answer: 2 },
    { question: "What is the capital of Pakistan?", options: ["Karachi", "Lahore", "Islamabad", "Peshawar"], answer: 2 },
    { question: "Which country has the most time zones?", options: ["Russia", "United States", "China", "France"], answer: 3 },
    { question: "What is the capital of Indonesia?", options: ["Surabaya", "Bandung", "Medan", "Jakarta"], answer: 3 },
    { question: "What is the name of the largest ocean trench?", options: ["Puerto Rico Trench", "Java Trench", "Philippine Trench", "Mariana Trench"], answer: 3 },
    { question: "What is the capital of Thailand?", options: ["Chiang Mai", "Phuket", "Pattaya", "Bangkok"], answer: 3 },
    { question: "Which country has the longest coastline in the world?", options: ["Russia", "Australia", "Norway", "Canada"], answer: 3 },
    { question: "What is the capital of Sweden?", options: ["Gothenburg", "Malmö", "Uppsala", "Stockholm"], answer: 3 },
    { question: "What is the name of the world's largest archipelago?", options: ["Japan", "Philippines", "Indonesia", "Caribbean Islands"], answer: 2 },
    { question: "What is the capital of Ethiopia?", options: ["Dire Dawa", "Gondar", "Mekele", "Addis Ababa"], answer: 3 },
    { question: "What is the name of the channel between England and France?", options: ["North Sea", "Irish Sea", "English Channel", "Bay of Biscay"], answer: 2 },
    { question: "What is the capital of Norway?", options: ["Bergen", "Trondheim", "Stavanger", "Oslo"], answer: 3 },
    { question: "Which country is home to the Amazon River's mouth?", options: ["Peru", "Colombia", "Venezuela", "Brazil"], answer: 3 },
    { question: "What is the capital of Poland?", options: ["Kraków", "Gdańsk", "Wrocław", "Warsaw"], answer: 3 },
    { question: "What is the tallest waterfall in the world?", options: ["Niagara Falls", "Victoria Falls", "Iguazu Falls", "Angel Falls"], answer: 3 },
    { question: "What is the capital of Ukraine?", options: ["Lviv", "Kharkiv", "Odessa", "Kyiv"], answer: 3 },
    { question: "Which desert is the driest non-polar desert in the world?", options: ["Sahara", "Gobi", "Atacama", "Arabian"], answer: 2 },
    { question: "What is the capital of Argentina's neighbor, Chile?", options: ["Valparaíso", "Concepción", "Antofagasta", "Santiago"], answer: 3 },
    { question: "What is the name of the world's largest salt flat?", options: ["Bonneville Salt Flats", "Etosha Pan", "Salar de Atacama", "Salar de Uyuni"], answer: 3 },
    { question: "What is the capital of Vietnam?", options: ["Ho Chi Minh City", "Da Nang", "Hue", "Hanoi"], answer: 3 },
    { question: "Which African country has the largest land area?", options: ["Sudan", "Libya", "Democratic Republic of Congo", "Algeria"], answer: 3 },
    { question: "What is the capital of Peru?", options: ["Cusco", "Arequipa", "Trujillo", "Lima"], answer: 3 },
    { question: "What is the name of the strait between Alaska and Russia?", options: ["Hudson Strait", "Bering Strait", "Davis Strait", "Cook Strait"], answer: 1 },
    { question: "What is the capital of the Netherlands?", options: ["Rotterdam", "The Hague", "Utrecht", "Amsterdam"], answer: 3 },
    { question: "Which mountain range separates Europe from Asia?", options: ["Caucasus Mountains", "Carpathian Mountains", "Ural Mountains", "Alps"], answer: 2 },
    { question: "What is the capital of Colombia?", options: ["Medellín", "Cali", "Cartagena", "Bogotá"], answer: 3 },
    { question: "What is the name of the largest bay in the world?", options: ["Hudson Bay", "Bay of Bengal", "Gulf of Mexico", "Gulf of Guinea"], answer: 1 },
    { question: "What is the capital of Portugal?", options: ["Porto", "Braga", "Coimbra", "Lisbon"], answer: 3 },
    { question: "Which country has the most UNESCO World Heritage Sites?", options: ["France", "China", "Spain", "Italy"], answer: 3 },
    { question: "What is the capital of Morocco?", options: ["Casablanca", "Marrakech", "Fez", "Rabat"], answer: 3 },
    { question: "What is the name of the famous fjord country of Scandinavia?", options: ["Sweden", "Denmark", "Finland", "Norway"], answer: 3 },
    { question: "What is the capital of Greece?", options: ["Thessaloniki", "Patras", "Heraklion", "Athens"], answer: 3 },
    { question: "What is the world's second-largest continent by area?", options: ["North America", "Asia", "Africa", "South America"], answer: 2 },
    { question: "What is the capital of Denmark?", options: ["Aarhus", "Odense", "Aalborg", "Copenhagen"], answer: 3 },
  ],
};
