export const TRIVIA_PART4 = {
  "Music & Artists": [
    { question: "Which Beatles album features the song 'Come Together'?", options: ["Revolver", "Abbey Road", "Let It Be", "Help!"], answer: 1 },
    { question: "What year did the Beatles release 'Sgt. Pepper's Lonely Hearts Club Band'?", options: ["1965", "1966", "1967", "1968"], answer: 2 },
    { question: "Which Beatles member wrote 'Yesterday'?", options: ["John Lennon", "George Harrison", "Ringo Starr", "Paul McCartney"], answer: 3 },
    { question: "Michael Jackson's 'Thriller' album was released in which year?", options: ["1980", "1981", "1982", "1983"], answer: 2 },
    { question: "How many weeks did 'Thriller' spend at number one on the Billboard 200?", options: ["27", "37", "47", "57"], answer: 1 },
    { question: "Which Michael Jackson album contains the song 'Billie Jean'?", options: ["Off the Wall", "Bad", "Thriller", "Dangerous"], answer: 2 },
    { question: "Madonna's debut album was released in which year?", options: ["1981", "1982", "1983", "1984"], answer: 2 },
    { question: "Which Madonna album features 'Like a Prayer'?", options: ["True Blue", "Like a Prayer", "Ray of Light", "Music"], answer: 1 },
    { question: "What is Madonna's full birth name?", options: ["Madonna Louise Ciccone", "Madonna Ann Ciccone", "Madonna Rose Ciccone", "Madonna Grace Ciccone"], answer: 0 },
    { question: "Which album won the Grammy for Album of the Year in 2000?", options: ["Supernatural by Santana", "The Slim Shady LP", "Fly Away by Lenny Kravitz", "Back to Basics by Christina Aguilera"], answer: 0 },
    { question: "Which artist holds the record for most Grammy wins in a single night (28 total)?", options: ["Beyoncé", "Michael Jackson", "Adele", "Taylor Swift"], answer: 0 },
    { question: "What genre of music originated in Jamaica in the late 1960s?", options: ["Ska", "Reggae", "Dancehall", "Calypso"], answer: 1 },
    { question: "Hip-hop music originated in which New York City borough?", options: ["Manhattan", "Brooklyn", "Queens", "The Bronx"], answer: 3 },
    { question: "Which famous music duo was Simon & Garfunkel?", options: ["Paul Simon and Art Garfunkel", "Simon Cowell and Art Garfunkel", "Paul Simon and Garth Brooks", "Simon Le Bon and Art Garfunkel"], answer: 0 },
    { question: "Who was the lead guitarist of Led Zeppelin?", options: ["Robert Plant", "John Paul Jones", "Jimmy Page", "John Bonham"], answer: 2 },
    { question: "Which band featured Mick Jagger and Keith Richards?", options: ["The Who", "The Rolling Stones", "The Kinks", "The Animals"], answer: 1 },
    { question: "What instrument is Yo-Yo Ma famous for playing?", options: ["Violin", "Viola", "Cello", "Double Bass"], answer: 2 },
    { question: "Which song by Queen reached #1 in the UK in 1975 and 1992?", options: ["We Are the Champions", "Somebody to Love", "Bohemian Rhapsody", "Don't Stop Me Now"], answer: 2 },
    { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], answer: 2 },
    { question: "What musical term means 'gradually getting louder'?", options: ["Diminuendo", "Crescendo", "Fortissimo", "Rallentando"], answer: 1 },
    { question: "Which album by Pink Floyd features 'The Dark Side of the Moon'?", options: ["Wish You Were Here", "Animals", "The Dark Side of the Moon", "The Wall"], answer: 2 },
    { question: "Woodstock music festival took place in which year?", options: ["1967", "1968", "1969", "1970"], answer: 2 },
    { question: "Who is known as the 'King of Blues'?", options: ["Muddy Waters", "B.B. King", "Robert Johnson", "John Lee Hooker"], answer: 1 },
    { question: "What does 'BPM' stand for in music?", options: ["Bass Per Measure", "Beats Per Minute", "Bass Per Minute", "Beats Per Measure"], answer: 1 },
    { question: "Which Elton John song was rewritten as a tribute to Princess Diana?", options: ["Rocket Man", "Tiny Dancer", "Candle in the Wind", "Crocodile Rock"], answer: 2 },
    { question: "David Bowie's alter ego was known as?", options: ["Ziggy Stardust", "Major Tom", "Aladdin Sane", "The Thin White Duke"], answer: 0 },
    { question: "Which female artist recorded 'Respect' in 1967?", options: ["Diana Ross", "Tina Turner", "Aretha Franklin", "Gladys Knight"], answer: 2 },
    { question: "What key is a standard piano tuned to?", options: ["A440", "C440", "A432", "C432"], answer: 0 },
    { question: "The opera 'La Traviata' was composed by whom?", options: ["Puccini", "Mozart", "Verdi", "Rossini"], answer: 2 },
    { question: "Which band was Kurt Cobain the frontman of?", options: ["Pearl Jam", "Soundgarden", "Nirvana", "Alice in Chains"], answer: 2 },
    { question: "What is a 'cappella' singing?", options: ["Singing with full orchestra", "Singing without instrumental accompaniment", "Singing in Italian", "Singing in church only"], answer: 1 },
    { question: "Jimi Hendrix was known for playing the guitar in what distinctive way?", options: ["With his feet", "Left-handed on a right-handed guitar", "Behind his back only", "With a bow"], answer: 1 },
    { question: "Which artist released the album 'Purple Rain' in 1984?", options: ["Michael Jackson", "Prince", "David Bowie", "Madonna"], answer: 1 },
    { question: "What is the lowest-pitched brass instrument in a standard orchestra?", options: ["Trombone", "Tuba", "French Horn", "Euphonium"], answer: 1 },
    { question: "Which decade saw the birth of rock and roll music?", options: ["1930s", "1940s", "1950s", "1960s"], answer: 2 },
    { question: "Stevie Wonder was born blind. What is his real name?", options: ["Stevland Morris", "Stevland Jackson", "Stevland Williams", "Stevland Johnson"], answer: 0 },
    { question: "Which British band had hits with 'Wonderwall' and 'Don't Look Back in Anger'?", options: ["Blur", "Radiohead", "Oasis", "Pulp"], answer: 2 },
    { question: "What instrument does a percussionist play?", options: ["Only drums", "Any instrument struck or shaken", "Wind instruments", "String instruments"], answer: 1 },
    { question: "Which classical composer was deaf when he wrote his 9th Symphony?", options: ["Mozart", "Bach", "Beethoven", "Handel"], answer: 2 },
    { question: "The Grammy Award is named after which invention?", options: ["The phonograph", "The gramophone", "The microphone", "The radio"], answer: 1 },
    { question: "Which artist has the best-selling album of all time with 'Thriller'?", options: ["Elvis Presley", "The Beatles", "Michael Jackson", "AC/DC"], answer: 2 },
    { question: "What does 'forte' mean in music?", options: ["Soft", "Loud", "Fast", "Slow"], answer: 1 },
    { question: "Which band released 'Hotel California' in 1977?", options: ["Fleetwood Mac", "The Eagles", "Crosby, Stills & Nash", "Jackson Browne"], answer: 1 },
    { question: "What is the name of the scale with no sharps or flats?", options: ["A major", "G major", "C major", "D major"], answer: 2 },
    { question: "Which artist is known as the 'Queen of Pop'?", options: ["Celine Dion", "Whitney Houston", "Madonna", "Mariah Carey"], answer: 2 },
    { question: "The famous concert 'Live Aid' was held in which year?", options: ["1983", "1984", "1985", "1986"], answer: 2 },
    { question: "Which rap duo made up Run-DMC?", options: ["Run, DMC, and Jam Master Jay", "Jay-Z and Kanye West", "Outkast", "Eric B. and Rakim"], answer: 0 },
    { question: "What is the name of Taylor Swift's debut album?", options: ["Fearless", "Taylor Swift", "Speak Now", "Red"], answer: 1 },
    { question: "Adele's album '21' is named after what?", options: ["Her favorite number", "Her age when she recorded it", "A street address", "A lucky number"], answer: 1 },
    { question: "Who wrote 'A Whiter Shade of Pale' for Procol Harum?", options: ["Keith Reid", "Gary Brooker", "Matthew Fisher", "Robin Trower"], answer: 0 },
    { question: "What is the time signature of a waltz?", options: ["2/4", "4/4", "3/4", "6/8"], answer: 2 },
    { question: "Bob Dylan won the Nobel Prize in which field?", options: ["Peace", "Literature", "Music", "Arts"], answer: 1 },
    { question: "Which Beatles song is the longest studio recording?", options: ["Hey Jude", "A Day in the Life", "Let It Be", "Revolution 9"], answer: 0 },
    { question: "What instrument is most associated with Scott Joplin?", options: ["Trumpet", "Guitar", "Piano", "Saxophone"], answer: 2 },
    { question: "Which country is reggaeton music most associated with?", options: ["Cuba", "Jamaica", "Puerto Rico", "Dominican Republic"], answer: 2 },
    { question: "The rock band U2 is from which country?", options: ["England", "Scotland", "Australia", "Ireland"], answer: 3 },
    { question: "What does 'MP3' stand for?", options: ["MPEG-1 Audio Layer III", "Music Player 3", "Media Player 3", "Musical Protocol 3"], answer: 0 },
    { question: "Which composer wrote 'The Four Seasons'?", options: ["Bach", "Handel", "Vivaldi", "Telemann"], answer: 2 },
    { question: "Elvis Presley's first hit single was?", options: ["Hound Dog", "Heartbreak Hotel", "Jailhouse Rock", "That's All Right"], answer: 3 },
    { question: "What type of guitar has a hollow body that amplifies sound acoustically?", options: ["Electric guitar", "Bass guitar", "Acoustic guitar", "Classical guitar"], answer: 2 },
  ],

  "Sports & Athletes": [
    { question: "In which year did Usain Bolt set the 100m world record of 9.58 seconds?", options: ["2007", "2008", "2009", "2010"], answer: 2 },
    { question: "How many Olympic gold medals did Michael Phelps win in his career?", options: ["18", "20", "23", "28"], answer: 2 },
    { question: "Muhammad Ali's birth name was?", options: ["Cassius Clay", "Cassius Muhammad", "Ali Jones", "Muhammad Jones"], answer: 0 },
    { question: "Michael Jordan played for which NBA team for most of his career?", options: ["Los Angeles Lakers", "Boston Celtics", "Chicago Bulls", "New York Knicks"], answer: 2 },
    { question: "How many FIFA World Cups has Brazil won?", options: ["3", "4", "5", "6"], answer: 2 },
    { question: "In which city were the first modern Olympic Games held in 1896?", options: ["Rome", "Paris", "London", "Athens"], answer: 3 },
    { question: "Who holds the men's marathon world record?", options: ["Eliud Kipchoge", "Haile Gebrselassie", "Dennis Kimetto", "Wilson Kipsang"], answer: 0 },
    { question: "Cristiano Ronaldo is from which country?", options: ["Spain", "Brazil", "Portugal", "Argentina"], answer: 2 },
    { question: "How many Grand Slam titles has Serena Williams won?", options: ["19", "21", "23", "25"], answer: 2 },
    { question: "The Super Bowl is the championship game of which sport?", options: ["Basketball", "Baseball", "American Football", "Ice Hockey"], answer: 2 },
    { question: "Which country has won the most FIFA World Cup titles?", options: ["Germany", "Italy", "Argentina", "Brazil"], answer: 3 },
    { question: "Who was the first woman to win four consecutive Olympic gold medals in figure skating?", options: ["Sonja Henie", "Peggy Fleming", "Katarina Witt", "Michelle Kwan"], answer: 0 },
    { question: "Which tennis player is known as 'The GOAT' by many fans with 24 Grand Slam titles?", options: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras"], answer: 0 },
    { question: "How many players are on a basketball team on the court at once?", options: ["4", "5", "6", "7"], answer: 1 },
    { question: "In which sport do you perform a 'slam dunk'?", options: ["Volleyball", "Basketball", "Tennis", "Handball"], answer: 1 },
    { question: "The 2016 Summer Olympics were held in which city?", options: ["Tokyo", "London", "Rio de Janeiro", "Beijing"], answer: 2 },
    { question: "Which athlete is known as 'The Greatest' in boxing?", options: ["Mike Tyson", "Joe Frazier", "Muhammad Ali", "George Foreman"], answer: 2 },
    { question: "Who scored the 'Hand of God' goal at the 1986 World Cup?", options: ["Pelé", "Diego Maradona", "Ronaldo", "Zidane"], answer: 1 },
    { question: "How many events make up the decathlon?", options: ["8", "9", "10", "12"], answer: 2 },
    { question: "In which year did Tiger Woods first win the Masters?", options: ["1995", "1996", "1997", "1998"], answer: 2 },
    { question: "The NHL Stanley Cup is the championship trophy for which sport?", options: ["Basketball", "Baseball", "American Football", "Ice Hockey"], answer: 3 },
    { question: "Which country invented cricket?", options: ["Australia", "India", "England", "West Indies"], answer: 2 },
    { question: "How many laps is a standard Olympic swimming pool race of 400m?", options: ["4", "6", "8", "16"], answer: 2 },
    { question: "Who holds the record for most Tour de France wins?", options: ["Eddy Merckx", "Bernard Hinault", "Lance Armstrong (stripped)", "Chris Froome"], answer: 0 },
    { question: "What sport uses a 'puck'?", options: ["Field Hockey", "Ice Hockey", "Lacrosse", "Polo"], answer: 1 },
    { question: "Lionel Messi is from which country?", options: ["Spain", "Brazil", "Uruguay", "Argentina"], answer: 3 },
    { question: "How many sets are in a standard men's tennis Grand Slam match?", options: ["3", "4", "5", "7"], answer: 2 },
    { question: "Which country has hosted the most Summer Olympics?", options: ["France", "USA", "UK", "Germany"], answer: 1 },
    { question: "In boxing, what is a 'TKO'?", options: ["Total Knockout", "Technical Knockout", "Temporary Knockout", "Triple Knockout"], answer: 1 },
    { question: "Who was the first person to run a mile in under 4 minutes?", options: ["Jim Ryun", "Roger Bannister", "Herb Elliott", "Sebastian Coe"], answer: 1 },
    { question: "The 'Miracle on Ice' refers to the USA hockey victory at which Olympics?", options: ["1976 Innsbruck", "1980 Lake Placid", "1984 Sarajevo", "1988 Calgary"], answer: 1 },
    { question: "How many gold medals did Jesse Owens win at the 1936 Berlin Olympics?", options: ["2", "3", "4", "5"], answer: 2 },
    { question: "What is the standard distance of a marathon?", options: ["26.1 miles", "26.2 miles", "26.3 miles", "26.4 miles"], answer: 1 },
    { question: "In which sport is the 'Ryder Cup' contested?", options: ["Tennis", "Cricket", "Golf", "Polo"], answer: 2 },
    { question: "How many players are on a soccer/football team on the field?", options: ["9", "10", "11", "12"], answer: 2 },
    { question: "Pelé played club football for which Brazilian team?", options: ["Flamengo", "Santos", "Corinthians", "São Paulo"], answer: 1 },
    { question: "The 'Fosbury Flop' is a technique in which athletics event?", options: ["Long Jump", "Pole Vault", "High Jump", "Triple Jump"], answer: 2 },
    { question: "Which country won the first FIFA World Cup in 1930?", options: ["Brazil", "Italy", "Argentina", "Uruguay"], answer: 3 },
    { question: "Michael Phelps competed in which sport?", options: ["Diving", "Water Polo", "Swimming", "Synchronized Swimming"], answer: 2 },
    { question: "The Kentucky Derby is a famous race in which sport?", options: ["Greyhound Racing", "Motorsport", "Thoroughbred Horse Racing", "Harness Racing"], answer: 2 },
    { question: "Who has won the most Grand Slam singles titles in men's tennis history?", options: ["Roger Federer", "Rafael Nadal", "Novak Djokovic", "Pete Sampras"], answer: 2 },
    { question: "Which sport features the 'butterfly stroke'?", options: ["Water Polo", "Diving", "Swimming", "Synchronized Swimming"], answer: 2 },
    { question: "How many points is a touchdown worth in American Football?", options: ["5", "6", "7", "8"], answer: 1 },
    { question: "In which year were women first allowed to compete in the Olympics?", options: ["1896", "1900", "1908", "1912"], answer: 1 },
    { question: "Usain Bolt is from which country?", options: ["Trinidad and Tobago", "Bahamas", "Jamaica", "Barbados"], answer: 2 },
    { question: "The 'Golden State Warriors' play in which American city?", options: ["Los Angeles", "San Francisco Bay Area", "Sacramento", "San Diego"], answer: 1 },
    { question: "In baseball, how many strikes result in a strikeout?", options: ["2", "3", "4", "5"], answer: 1 },
    { question: "Which country has won the most Olympic gold medals overall?", options: ["Russia", "China", "Germany", "United States"], answer: 3 },
    { question: "What is the highest score achievable in ten-pin bowling?", options: ["200", "250", "275", "300"], answer: 3 },
    { question: "Who was the first gymnast to score a perfect 10 at the Olympics?", options: ["Mary Lou Retton", "Nadia Comaneci", "Olga Korbut", "Larisa Latynina"], answer: 1 },
    { question: "The 'Ashes' cricket series is contested between England and which country?", options: ["India", "South Africa", "New Zealand", "Australia"], answer: 3 },
    { question: "In which year did LeBron James win his first NBA championship?", options: ["2010", "2011", "2012", "2013"], answer: 2 },
    { question: "How many holes are played in a standard round of golf?", options: ["9", "12", "18", "24"], answer: 2 },
    { question: "Simone Biles competes in which Olympic sport?", options: ["Figure Skating", "Rhythmic Gymnastics", "Artistic Gymnastics", "Acrobatic Gymnastics"], answer: 2 },
    { question: "The 'All Blacks' is the rugby team of which country?", options: ["Australia", "South Africa", "New Zealand", "England"], answer: 2 },
    { question: "How many players are on a volleyball team on the court?", options: ["5", "6", "7", "8"], answer: 1 },
    { question: "Who was the first African-American to win Wimbledon?", options: ["Venus Williams", "Arthur Ashe", "Althea Gibson", "James Blake"], answer: 2 },
    { question: "The Boston Celtics won how many consecutive NBA championships from 1959 to 1966?", options: ["6", "7", "8", "9"], answer: 2 },
    { question: "Roger Federer won a record-tying 20 Grand Slams. He is from which country?", options: ["Austria", "Germany", "Switzerland", "Sweden"], answer: 2 },
    { question: "What is the term for three consecutive strikes in bowling?", options: ["Triple", "Hat-trick", "Turkey", "Three-bagger"], answer: 2 },
    { question: "The FIFA World Cup is held every how many years?", options: ["2", "3", "4", "5"], answer: 2 },
  ],

  "Food & Cuisine": [
    { question: "Which country is the origin of sushi?", options: ["China", "Korea", "Japan", "Vietnam"], answer: 2 },
    { question: "What is 'umami'?", options: ["A Japanese spice", "The fifth basic taste", "A cooking technique", "A type of seaweed"], answer: 1 },
    { question: "Gordon Ramsay is a celebrity chef from which country?", options: ["United States", "Australia", "Scotland", "Canada"], answer: 2 },
    { question: "Julia Child was famous for introducing which cuisine to American audiences?", options: ["Italian", "Chinese", "Mexican", "French"], answer: 3 },
    { question: "'Mise en place' is a French culinary term meaning?", options: ["Everything is cooked", "Everything in its place", "Cook slowly", "Season well"], answer: 1 },
    { question: "What is 'braising'?", options: ["Cooking in dry heat in an oven", "Slow cooking in a small amount of liquid", "Rapidly cooking in hot oil", "Cooking over open flame"], answer: 1 },
    { question: "Which spice is derived from the Crocus sativus flower?", options: ["Turmeric", "Saffron", "Paprika", "Cardamom"], answer: 1 },
    { question: "Paella is the national dish of which country?", options: ["Portugal", "Italy", "Mexico", "Spain"], answer: 3 },
    { question: "What is the main ingredient in hummus?", options: ["Lentils", "Chickpeas", "Black beans", "White beans"], answer: 1 },
    { question: "Which wine region is famous for Champagne?", options: ["Bordeaux", "Burgundy", "Champagne", "Alsace"], answer: 2 },
    { question: "What is 'sautéing'?", options: ["Cooking in water", "Cooking quickly in a small amount of fat over high heat", "Baking in an oven", "Steaming food"], answer: 1 },
    { question: "The Margherita pizza represents the colors of which country's flag?", options: ["France", "Spain", "Italy", "Greece"], answer: 2 },
    { question: "Which cocktail is made with vodka, lime juice, and ginger beer?", options: ["Moscow Mule", "Cosmopolitan", "Bloody Mary", "Gimlet"], answer: 0 },
    { question: "What is the French term for a complete set of cooking equipment?", options: ["Batterie de cuisine", "Mise en place", "Sous vide", "En papillote"], answer: 0 },
    { question: "Croissants originated in which country?", options: ["France", "Austria", "Germany", "Belgium"], answer: 1 },
    { question: "Which street food is most associated with Mexico City?", options: ["Burritos", "Tacos", "Enchiladas", "Quesadillas"], answer: 1 },
    { question: "What cheese is used in a traditional Greek salad?", options: ["Mozzarella", "Brie", "Feta", "Halloumi"], answer: 2 },
    { question: "Tiramisu is a dessert originating from which country?", options: ["Spain", "France", "Greece", "Italy"], answer: 3 },
    { question: "What is the main flavor in a traditional Béarnaise sauce?", options: ["Lemon and cream", "Tarragon and butter", "Mustard and wine", "Garlic and olive oil"], answer: 1 },
    { question: "Which country produces the most wine in the world?", options: ["France", "Spain", "Italy", "USA"], answer: 2 },
    { question: "What is a 'Roux' in cooking?", options: ["A type of French bread", "A mixture of fat and flour used as a thickener", "A reduction sauce", "A type of pastry"], answer: 1 },
    { question: "Mole sauce is a traditional sauce from which country?", options: ["Spain", "Colombia", "Mexico", "Peru"], answer: 2 },
    { question: "Which spice is known as 'black gold' historically?", options: ["Cinnamon", "Nutmeg", "Pepper", "Saffron"], answer: 2 },
    { question: "What is the primary ingredient in guacamole?", options: ["Tomato", "Lime", "Avocado", "Onion"], answer: 2 },
    { question: "The Margarita cocktail is traditionally made with which spirit?", options: ["Rum", "Vodka", "Gin", "Tequila"], answer: 3 },
    { question: "What is 'charcuterie'?", options: ["Cheese making", "The art of preparing cured meats", "French pastry making", "Wine making"], answer: 1 },
    { question: "Kimchi is a fermented dish originating from which country?", options: ["Japan", "China", "Thailand", "Korea"], answer: 3 },
    { question: "What is the key ingredient that gives Coca-Cola its characteristic color?", options: ["Caramel coloring", "Coffee extract", "Molasses", "Licorice extract"], answer: 0 },
    { question: "Borscht is a traditional soup from which region?", options: ["Middle East", "Eastern Europe", "Scandinavia", "Central Asia"], answer: 1 },
    { question: "What does 'al dente' mean in Italian cooking?", options: ["Well done", "Cooked to the tooth (slightly firm)", "Very soft", "Half cooked"], answer: 1 },
    { question: "Prosciutto is an Italian cured meat made from which part of the pig?", options: ["Belly", "Shoulder", "Leg/Ham", "Cheek"], answer: 2 },
    { question: "Which French chef is credited with modernizing French cuisine in the 20th century?", options: ["Jacques Pépin", "Paul Bocuse", "Alain Ducasse", "Joel Robuchon"], answer: 1 },
    { question: "What is 'tempura' in Japanese cuisine?", options: ["Pickled vegetables", "Raw fish", "Battered and deep-fried seafood or vegetables", "Grilled meat on skewers"], answer: 2 },
    { question: "Cheddar cheese originates from which country?", options: ["France", "Netherlands", "USA", "England"], answer: 3 },
    { question: "What is the main ingredient in traditional Worcestershire sauce?", options: ["Tomatoes", "Anchovies", "Mushrooms", "Vinegar only"], answer: 1 },
    { question: "Bordeaux wine comes from which country?", options: ["Italy", "Spain", "Argentina", "France"], answer: 3 },
    { question: "Which nut is used to make marzipan?", options: ["Cashew", "Walnut", "Almond", "Hazelnut"], answer: 2 },
    { question: "What cooking technique involves cooking food sealed in a bag in water at low temperature?", options: ["Blanching", "Poaching", "Sous vide", "Confit"], answer: 2 },
    { question: "Pad Thai is a national dish of which country?", options: ["Vietnam", "Cambodia", "Indonesia", "Thailand"], answer: 3 },
    { question: "Which country is the largest producer of olive oil?", options: ["Greece", "Italy", "Tunisia", "Spain"], answer: 3 },
    { question: "A 'ganache' in pastry making is made from?", options: ["Butter and sugar", "Cream and chocolate", "Eggs and milk", "Flour and water"], answer: 1 },
    { question: "Mojito is a cocktail originating from which country?", options: ["Brazil", "Puerto Rico", "Cuba", "Mexico"], answer: 2 },
    { question: "What is 'pho'?", options: ["Vietnamese rice dish", "Vietnamese noodle soup", "Filipino stew", "Thai curry"], answer: 1 },
    { question: "Which spice gives turmeric its yellow color?", options: ["Beta-carotene", "Curcumin", "Anthocyanin", "Lycopene"], answer: 1 },
    { function: "Which dessert consists of meringue topped with cream and fresh fruit?", options: ["Éclairs", "Pavlova", "Trifle", "Eton Mess"], answer: 1, question: "Which dessert consists of meringue topped with cream and fresh fruit?" },
    { question: "What is the origin of the Old Fashioned cocktail?", options: ["France", "England", "United States", "Ireland"], answer: 2 },
    { question: "Which cooking method involves cooking food in its own fat?", options: ["Confit", "Braise", "Sauté", "Poach"], answer: 0 },
    { question: "What is 'bruschetta' in Italian cuisine?", options: ["A type of pasta", "Grilled bread rubbed with garlic and olive oil", "A cold pasta salad", "A type of pizza"], answer: 1 },
    { question: "The 'Maillard reaction' in cooking refers to?", options: ["Food turning rancid", "Browning of food when heated", "Fermentation process", "Emulsification of fats"], answer: 1 },
    { question: "Which country is home to the dish 'jollof rice'?", options: ["Ethiopia", "Kenya", "West Africa (multiple countries)", "South Africa"], answer: 2 },
    { question: "What gives sourdough bread its distinctive sour taste?", options: ["Vinegar", "Lemon juice", "Lactic and acetic acids from fermentation", "Citric acid"], answer: 2 },
    { question: "What is 'blanching' in cooking?", options: ["Cooking slowly in fat", "Briefly boiling then transferring to ice water", "Cooking in a covered pot", "Cooking in steam"], answer: 1 },
    { question: "Naan bread is associated with which cuisine?", options: ["Thai", "Chinese", "Indian/South Asian", "Middle Eastern"], answer: 2 },
    { question: "What is 'fromage blanc'?", options: ["A type of wine", "A fresh French cheese", "A pastry cream", "A type of baguette"], answer: 1 },
    { question: "Which pepper is used to make traditional Hungarian goulash?", options: ["Black pepper", "Cayenne pepper", "Paprika", "White pepper"], answer: 2 },
    { question: "What is 'tempeh'?", options: ["A type of tofu", "Fermented soybean cake", "A Thai spice blend", "A type of noodle"], answer: 1 },
    { question: "Caipirinha is the national cocktail of which country?", options: ["Argentina", "Colombia", "Venezuela", "Brazil"], answer: 3 },
    { question: "What is the traditional Japanese alcoholic beverage made from rice?", options: ["Shochu", "Sake", "Soju", "Baijiu"], answer: 1 },
    { question: "Which country is famous for its dish 'rendang'?", options: ["Thailand", "Vietnam", "Indonesia", "Philippines"], answer: 2 },
    { question: "What is 'gastrique' in French cooking?", options: ["A stomach remedy", "A sweet-sour reduction of sugar and vinegar", "A type of pastry", "A reduction of red wine"], answer: 1 },
  ],

  "Mythology & Folklore": [
    { question: "Who is the king of the Greek gods?", options: ["Poseidon", "Apollo", "Hades", "Zeus"], answer: 3 },
    { question: "What is the Roman equivalent of the Greek god Zeus?", options: ["Mars", "Neptune", "Jupiter", "Mercury"], answer: 2 },
    { question: "In Norse mythology, who is the god of thunder?", options: ["Odin", "Loki", "Freyr", "Thor"], answer: 3 },
    { question: "In Greek mythology, who is the goddess of wisdom?", options: ["Hera", "Aphrodite", "Athena", "Artemis"], answer: 2 },
    { question: "The Egyptian god Anubis is associated with what?", options: ["Sun and creation", "War and strength", "Death and mummification", "Fertility and harvest"], answer: 2 },
    { question: "Who is the Norse god of mischief?", options: ["Odin", "Loki", "Freyr", "Baldur"], answer: 1 },
    { question: "In Greek mythology, how many labors did Hercules perform?", options: ["10", "11", "12", "13"], answer: 2 },
    { question: "The Trojan War was fought over which woman?", options: ["Cleopatra", "Aphrodite", "Helen of Troy", "Penelope"], answer: 2 },
    { question: "Who turned people to stone with her gaze in Greek mythology?", options: ["Circe", "Scylla", "Medusa", "Charybdis"], answer: 2 },
    { question: "Ra is the sun god of which ancient mythology?", options: ["Greek", "Roman", "Norse", "Egyptian"], answer: 3 },
    { question: "Amaterasu is the sun goddess of which mythology?", options: ["Chinese", "Korean", "Japanese", "Filipino"], answer: 2 },
    { question: "In Greek mythology, who is the god of the sea?", options: ["Zeus", "Hades", "Apollo", "Poseidon"], answer: 3 },
    { question: "What is the name of Thor's hammer?", options: ["Gungnir", "Mjolnir", "Excalibur", "Durandal"], answer: 1 },
    { question: "In Norse mythology, what is the name of the world tree?", options: ["Bifrost", "Yggdrasil", "Valhalla", "Asgard"], answer: 1 },
    { question: "Osiris is the Egyptian god of what?", options: ["Sun and light", "War and conquest", "The afterlife and resurrection", "Rivers and floods"], answer: 2 },
    { question: "In Greek mythology, who flew too close to the sun and fell into the sea?", options: ["Daedalus", "Perseus", "Icarus", "Theseus"], answer: 2 },
    { question: "The Minotaur lived in what structure?", options: ["A pyramid", "A labyrinth", "A cave", "A dungeon"], answer: 1 },
    { question: "In Roman mythology, who is the goddess of love?", options: ["Juno", "Diana", "Venus", "Minerva"], answer: 2 },
    { question: "What is the name of Odin's spear?", options: ["Mjolnir", "Gungnir", "Excalibur", "Tyrfing"], answer: 1 },
    { question: "In Celtic mythology, what is the Otherworld called in Irish tradition?", options: ["Avalon", "Tír na nÓg", "Valhalla", "Elysium"], answer: 1 },
    { question: "Susanoo is the Japanese god of what?", options: ["Sun and light", "War and swords", "Storms and sea", "Rice and agriculture"], answer: 2 },
    { question: "In Greek mythology, who is Achilles' mother?", options: ["Hera", "Thetis", "Demeter", "Hestia"], answer: 1 },
    { question: "What creature has the head of a man and body of a lion in Egyptian mythology?", options: ["Manticore", "Griffin", "Sphinx", "Chimera"], answer: 2 },
    { question: "In Norse mythology, what is the realm of the dead ruled by Hel?", options: ["Niflheim", "Helheim", "Muspelheim", "Jotunheim"], answer: 1 },
    { question: "Which Greek hero killed the Minotaur?", options: ["Perseus", "Heracles", "Theseus", "Achilles"], answer: 2 },
    { question: "The phoenix is a mythological bird associated with what?", options: ["Ice and winter", "Rain and water", "Fire and rebirth", "Thunder and storms"], answer: 2 },
    { question: "In Greek mythology, who was condemned to push a boulder up a hill for eternity?", options: ["Tantalus", "Prometheus", "Sisyphus", "Ixion"], answer: 2 },
    { question: "What is the Roman equivalent of the Greek god Ares?", options: ["Jupiter", "Mars", "Mercury", "Neptune"], answer: 1 },
    { question: "In Japanese mythology, Amaterasu hid in a cave after a conflict with which god?", options: ["Tsukuyomi", "Raijin", "Fujin", "Susanoo"], answer: 3 },
    { question: "What does the Valkyrie do in Norse mythology?", options: ["Guard the Rainbow Bridge", "Choose which warriors go to Valhalla", "Weave the threads of fate", "Guard Yggdrasil"], answer: 1 },
    { question: "In Greek mythology, Prometheus stole what from the gods to give to humans?", options: ["Water", "Wheat", "Fire", "Knowledge"], answer: 2 },
    { question: "The legendary King Arthur was associated with which country?", options: ["Scotland", "Wales", "France", "Britain/England"], answer: 3 },
    { question: "In Egyptian mythology, what is the feather of Ma'at used for?", options: ["Writing scrolls", "Weighing the heart of the deceased", "Casting spells", "Marking royal decrees"], answer: 1 },
    { question: "What is a 'banshee' in Irish folklore?", options: ["A water spirit", "A forest demon", "A wailing spirit that foretells death", "A trickster fairy"], answer: 2 },
    { question: "Hel in Norse mythology is the goddess of what?", options: ["War", "Love", "The underworld", "Wisdom"], answer: 2 },
    { question: "In Greek mythology, the three Fates were called the?", options: ["Graces", "Moirai", "Erinyes", "Muses"], answer: 1 },
    { question: "What creature is half-horse and half-human in Greek mythology?", options: ["Satyr", "Minotaur", "Chimera", "Centaur"], answer: 3 },
    { question: "The labors of Hercules were assigned by which king?", options: ["Minos", "Agamemnon", "Eurystheus", "Priam"], answer: 2 },
    { question: "In Norse mythology, Bifrost is a?", options: ["Sacred mountain", "Rainbow bridge between realms", "Great sea", "Dark forest"], answer: 1 },
    { question: "Which Greek Titan held up the sky?", options: ["Kronos", "Prometheus", "Atlas", "Epimetheus"], answer: 2 },
    { question: "In Greek mythology, who is the god of the underworld?", options: ["Ares", "Zeus", "Poseidon", "Hades"], answer: 3 },
    { question: "The 'Kitsune' in Japanese folklore is a magical?", options: ["Wolf", "Bear", "Fox", "Raccoon dog"], answer: 2 },
    { question: "In Greek mythology, what is the River Styx?", options: ["A river of fire", "The boundary between Earth and the underworld", "A river of wine", "A sacred spring"], answer: 1 },
    { question: "Loki is the father (or mother in some myths) of which monstrous creature?", options: ["The Minotaur", "Cerberus", "Fenrir the wolf", "The Sphinx"], answer: 2 },
    { question: "In Celtic myth, the Dagda is associated with what?", options: ["War and destruction", "The sea and storms", "Earth, fertility, and agriculture", "Death and rebirth"], answer: 2 },
    { question: "What is a 'changeling' in European folklore?", options: ["A shape-shifter", "A fairy child left in place of a stolen human child", "A vampire hybrid", "A ghost that changes form"], answer: 1 },
    { question: "In Greek mythology, who is the messenger of the gods?", options: ["Apollo", "Hermes", "Ares", "Hephaestus"], answer: 1 },
    { question: "The Egyptian god Set is associated with what?", options: ["Sun and order", "Chaos and desert storms", "Rivers and fertility", "Death and mummification"], answer: 1 },
    { question: "Which hero defeated the Gorgon Medusa?", options: ["Theseus", "Achilles", "Perseus", "Bellerophon"], answer: 2 },
    { question: "In Norse mythology, what are the giants called?", options: ["Dwarves", "Elves", "Jotunn (Jotnar)", "Trolls"], answer: 2 },
    { question: "Excalibur is the legendary sword of which king?", options: ["Charlemagne", "Richard the Lionheart", "King Arthur", "Alfred the Great"], answer: 2 },
    { question: "What is the 'Elysian Fields' in Greek mythology?", options: ["A battlefield", "The realm of the Titans", "A paradise for the heroic dead", "The garden of the gods"], answer: 2 },
    { question: "In Japanese mythology, Izanagi and Izanami are associated with the creation of?", options: ["Fire and water", "The islands of Japan", "Heaven and stars", "Animals and plants"], answer: 1 },
    { question: "What is a 'druid' in Celtic tradition?", options: ["A warrior class", "A priestly/learned class", "A merchant class", "A royal class"], answer: 1 },
    { question: "The Hydra in Greek mythology was a serpent with how many heads?", options: ["5", "7", "9", "It regenerated new heads when cut"], answer: 3 },
    { question: "Who is the Roman equivalent of the Greek goddess Athena?", options: ["Juno", "Venus", "Diana", "Minerva"], answer: 3 },
    { question: "In Norse mythology, who are the Norns?", options: ["Female warriors", "Weavers of fate/destiny", "Sea goddesses", "Goddesses of harvest"], answer: 1 },
    { question: "The Golden Fleece in Greek mythology was sought by which hero?", options: ["Odysseus", "Jason", "Hercules", "Perseus"], answer: 1 },
    { question: "In Hawaiian mythology, Pele is the goddess of?", options: ["Ocean and fish", "Sky and rain", "Volcanoes and fire", "Forests and animals"], answer: 2 },
    { question: "What is the 'Maui' figure in Polynesian mythology known for?", options: ["Creating storms", "Pulling islands from the sea and slowing the sun", "Building the first canoes", "Teaching humans to farm"], answer: 1 },
    { question: "In Greek mythology, Cerberus guards what?", options: ["Mount Olympus", "The Gates of the Underworld", "The Garden of the Hesperides", "The Oracle at Delphi"], answer: 1 },
  ],

  "Literature & Poetry": [
    { question: "Who wrote 'Romeo and Juliet'?", options: ["Christopher Marlowe", "Ben Jonson", "John Milton", "William Shakespeare"], answer: 3 },
    { question: "Which Shakespeare play features the character Hamlet?", options: ["Othello", "King Lear", "Hamlet", "Macbeth"], answer: 2 },
    { question: "Charles Dickens wrote which novel featuring the character Oliver Twist?", options: ["Great Expectations", "Oliver Twist", "David Copperfield", "A Tale of Two Cities"], answer: 1 },
    { question: "Jane Austen's 'Pride and Prejudice' features which female protagonist?", options: ["Emma Woodhouse", "Anne Elliot", "Elinor Dashwood", "Elizabeth Bennet"], answer: 3 },
    { question: "F. Scott Fitzgerald wrote which famous novel set in the Jazz Age?", options: ["The Sun Also Rises", "This Side of Paradise", "The Great Gatsby", "Tender Is the Night"], answer: 2 },
    { question: "George Orwell's '1984' features a totalitarian ruler known as?", options: ["The Party Leader", "Big Brother", "The Inner Circle", "O'Brien"], answer: 1 },
    { question: "Ernest Hemingway received the Nobel Prize in Literature in which year?", options: ["1950", "1952", "1954", "1956"], answer: 2 },
    { question: "Toni Morrison won the Nobel Prize in Literature in which year?", options: ["1989", "1991", "1993", "1995"], answer: 2 },
    { question: "What is a 'metaphor'?", options: ["A direct comparison using 'like' or 'as'", "An indirect comparison without 'like' or 'as'", "An exaggeration for effect", "A reference to another work"], answer: 1 },
    { question: "What is 'iambic pentameter'?", options: ["A rhyme scheme ABAB", "A line of five iambic feet (ten syllables)", "A type of free verse", "A stanza of eight lines"], answer: 1 },
    { question: "Which of George Orwell's novels features the pig Napoleon?", options: ["1984", "Keep the Aspidistra Flying", "Animal Farm", "Burmese Days"], answer: 2 },
    { question: "Which Shakespeare play includes the line 'To be or not to be'?", options: ["Macbeth", "King Lear", "Othello", "Hamlet"], answer: 3 },
    { question: "Who wrote 'To Kill a Mockingbird'?", options: ["Truman Capote", "John Steinbeck", "Harper Lee", "William Faulkner"], answer: 2 },
    { question: "What is an 'allegory'?", options: ["A story that uses symbols to represent deeper meanings", "A direct moral lesson at the end of a story", "A story told in reverse", "A comparison using 'like' or 'as'"], answer: 0 },
    { question: "Which poet wrote 'The Waste Land'?", options: ["W.B. Yeats", "Ezra Pound", "T.S. Eliot", "W.H. Auden"], answer: 2 },
    { question: "Jane Austen's 'Sense and Sensibility' was first published in which year?", options: ["1795", "1811", "1813", "1815"], answer: 1 },
    { question: "Which novel begins with 'Call me Ishmael'?", options: ["The Old Man and the Sea", "Lord Jim", "Moby-Dick", "Billy Budd"], answer: 2 },
    { question: "Who wrote 'The Canterbury Tales'?", options: ["John Gower", "Geoffrey Chaucer", "William Langland", "Thomas Malory"], answer: 1 },
    { question: "Which Russian author wrote 'War and Peace'?", options: ["Fyodor Dostoevsky", "Anton Chekhov", "Ivan Turgenev", "Leo Tolstoy"], answer: 3 },
    { question: "'One Hundred Years of Solitude' was written by which Nobel laureate?", options: ["Pablo Neruda", "Mario Vargas Llosa", "Gabriel García Márquez", "Jorge Luis Borges"], answer: 2 },
    { question: "Shakespeare's Macbeth features three witches who are also known as?", options: ["The Three Graces", "The Weird Sisters", "The Three Fates", "The Dark Sisters"], answer: 1 },
    { question: "Which banned book was written by J.D. Salinger?", options: ["Brave New World", "The Catcher in the Rye", "Lady Chatterley's Lover", "Ulysses"], answer: 1 },
    { question: "Who wrote the classic children's novel 'Alice's Adventures in Wonderland'?", options: ["Lewis Carroll", "J.M. Barrie", "Roald Dahl", "A.A. Milne"], answer: 0 },
    { question: "What is 'free verse' in poetry?", options: ["Poetry with a strict rhyme scheme", "Poetry that uses ABAB rhyme", "Poetry without regular meter or rhyme", "Poetry in sonnet form"], answer: 2 },
    { question: "Charles Dickens' novel 'A Christmas Carol' features which miser?", options: ["Mr. Gradgrind", "Uriah Heep", "Ebenezer Scrooge", "Mr. Bumble"], answer: 2 },
    { question: "Who wrote 'The Old Man and the Sea'?", options: ["F. Scott Fitzgerald", "John Steinbeck", "William Faulkner", "Ernest Hemingway"], answer: 3 },
    { question: "What literary device is used when a non-human character is given human qualities?", options: ["Metaphor", "Personification", "Alliteration", "Hyperbole"], answer: 1 },
    { question: "Which poet wrote 'Ode to a Nightingale'?", options: ["Percy Bysshe Shelley", "Lord Byron", "William Wordsworth", "John Keats"], answer: 3 },
    { question: "Virginia Woolf wrote which stream-of-consciousness novel about a single day in London?", options: ["To the Lighthouse", "Orlando", "The Waves", "Mrs Dalloway"], answer: 3 },
    { question: "Who wrote the Pulitzer Prize-winning novel 'Beloved'?", options: ["Alice Walker", "Zora Neale Hurston", "Toni Morrison", "Maya Angelou"], answer: 2 },
    { question: "Which classic children's book features characters named Bilbo and Gandalf?", options: ["The Chronicles of Narnia", "The Hobbit", "A Wrinkle in Time", "His Dark Materials"], answer: 1 },
    { question: "What is a 'sonnet'?", options: ["A 14-line poem with a specific rhyme scheme", "A 16-line poem", "An unrhymed poem about nature", "A long narrative poem"], answer: 0 },
    { question: "Gabriel García Márquez received the Nobel Prize in Literature in which year?", options: ["1980", "1982", "1984", "1986"], answer: 1 },
    { question: "Who wrote 'The Divine Comedy'?", options: ["Petrarch", "Boccaccio", "Virgil", "Dante Alighieri"], answer: 3 },
    { question: "Which Hemingway novel is set during the Spanish Civil War?", options: ["A Farewell to Arms", "The Sun Also Rises", "For Whom the Bell Tolls", "Islands in the Stream"], answer: 2 },
    { question: "Who wrote 'Brave New World'?", options: ["George Orwell", "Ray Bradbury", "Aldous Huxley", "H.G. Wells"], answer: 2 },
    { question: "What is 'hyperbole'?", options: ["Understatement for effect", "Deliberate exaggeration for effect", "A comparison using 'like' or 'as'", "A contradiction that reveals truth"], answer: 1 },
    { question: "Shakespeare's 'A Midsummer Night's Dream' is set primarily where?", options: ["In a castle", "In a forest near Athens", "In the court of Denmark", "In Venice"], answer: 1 },
    { question: "Who wrote 'Middlemarch', considered one of the greatest English novels?", options: ["Charlotte Brontë", "Thomas Hardy", "George Eliot", "Anthony Trollope"], answer: 2 },
    { question: "Which poet wrote 'I Wandered Lonely as a Cloud'?", options: ["Samuel Taylor Coleridge", "John Keats", "Percy Bysshe Shelley", "William Wordsworth"], answer: 3 },
    { question: "Fyodor Dostoevsky wrote which novel exploring guilt and redemption?", options: ["Anna Karenina", "The Brothers Karamazov", "Dead Souls", "Fathers and Sons"], answer: 1 },
    { question: "What is 'alliteration'?", options: ["Words that sound like what they mean", "Repetition of the same consonant sound at the start of words", "A comparison without using 'like' or 'as'", "A repeated phrase or line in a poem"], answer: 1 },
    { question: "Which novel by Charlotte Brontë features a governess narrator?", options: ["Wuthering Heights", "The Tenant of Wildfell Hall", "Jane Eyre", "Shirley"], answer: 2 },
    { question: "Homer's 'Iliad' is centered on which event?", options: ["The founding of Rome", "The Trojan War", "The journey of Odysseus", "The adventures of Heracles"], answer: 1 },
    { question: "Who won the Nobel Prize in Literature in 2016?", options: ["Alice Munro", "Mo Yan", "Bob Dylan", "Kazuo Ishiguro"], answer: 2 },
    { question: "Which Shakespeare play features the character Iago?", options: ["King Lear", "Macbeth", "Hamlet", "Othello"], answer: 3 },
    { question: "What classic novel begins with the line 'It was the best of times, it was the worst of times'?", options: ["Great Expectations", "A Tale of Two Cities", "Oliver Twist", "Bleak House"], answer: 1 },
    { question: "Who wrote 'The Odyssey'?", options: ["Sophocles", "Virgil", "Homer", "Ovid"], answer: 2 },
    { question: "Which children's classic features a boy who never grows up?", options: ["The Jungle Book", "Peter Pan", "Treasure Island", "The Wind in the Willows"], answer: 1 },
    { question: "What is an 'oxymoron'?", options: ["An exaggeration for effect", "A figure of speech combining two contradictory terms", "A reference to another text", "A comparison using 'like'"], answer: 1 },
    { question: "Maya Angelou wrote which autobiographical novel about her childhood?", options: ["Their Eyes Were Watching God", "Beloved", "I Know Why the Caged Bird Sings", "The Color Purple"], answer: 2 },
    { question: "Who wrote 'Ulysses', a modernist novel set in a single day in Dublin?", options: ["Samuel Beckett", "W.B. Yeats", "James Joyce", "Oscar Wilde"], answer: 2 },
    { question: "Which poem by Rudyard Kipling is addressed to his son?", options: ["Gunga Din", "The Road to Mandalay", "Danny Deever", "If—"], answer: 3 },
    { question: "What is 'enjambment' in poetry?", options: ["A rhyme scheme using alternate lines", "The continuation of a sentence across a line break", "A stanza of exactly four lines", "Repeating the same vowel sounds"], answer: 1 },
    { question: "Which dystopian novel features the Handmaid Offred?", options: ["The Giver", "Brave New World", "We", "The Handmaid's Tale"], answer: 3 },
    { question: "Who wrote 'Don Quixote', often called the first modern novel?", options: ["Lope de Vega", "Miguel de Cervantes", "Francisco de Quevedo", "Tirso de Molina"], answer: 1 },
    { question: "Which Shakespeare play features the 'To thine own self be true' line?", options: ["Othello", "King Lear", "Hamlet", "Macbeth"], answer: 2 },
    { question: "Sylvia Plath's semi-autobiographical novel is?", options: ["The Hours", "Wide Sargasso Sea", "The Bell Jar", "The Golden Notebook"], answer: 2 },
    { question: "Who wrote 'Things Fall Apart', a landmark African novel?", options: ["Ngugi wa Thiong'o", "Wole Soyinka", "Chinua Achebe", "Ben Okri"], answer: 2 },
    { question: "'The Road Not Taken' is a famous poem by which American poet?", options: ["Walt Whitman", "Emily Dickinson", "Robert Frost", "Carl Sandburg"], answer: 2 },
    { question: "Which Nobel laureate wrote 'Midnight's Children'?", options: ["V.S. Naipaul", "Kazuo Ishiguro", "Salman Rushdie", "Arundhati Roy"], answer: 2 },
  ],
};
