export const WYR_PART2 = {
  "Food & Senses": [
    { optionA: "Only eat sweet foods for the rest of your life", optionB: "Only eat savory foods for the rest of your life" },
    { optionA: "Never eat pizza again", optionB: "Never eat burgers again" },
    { optionA: "Always smell fresh cookies baking", optionB: "Always smell freshly cut grass" },
    { optionA: "Eat the same meal every day but love it", optionB: "Eat a different meal every day but find it mediocre" },
    { optionA: "Food always tastes twice as good but costs twice as much", optionB: "Food always tastes half as good but costs nothing" },
    { optionA: "Only drink water for beverages forever", optionB: "Never drink water — only other liquids" },
    { optionA: "Cook every meal from scratch", optionB: "Always order takeout but it's always slightly wrong" },
    { optionA: "Everything you eat is slightly too salty", optionB: "Everything you eat is slightly too sweet" },
    { optionA: "Eat your least favorite food once a week", optionB: "Never eat your favorite food again" },
    { optionA: "Always hear faint elevator music while eating", optionB: "Always smell someone else's food while eating your own" },
    { optionA: "Food loses all color but tastes perfect", optionB: "Food looks stunning but tastes like cardboard" },
    { optionA: "Only eat crunchy textures forever", optionB: "Only eat soft textures forever" },
    { optionA: "Every meal is perfectly seasoned but cold", optionB: "Every meal is piping hot but completely bland" },
    { optionA: "Lose your sense of taste permanently", optionB: "Lose your sense of smell permanently" },
    { optionA: "Always feel full after two bites", optionB: "Never feel full no matter how much you eat" },
    { optionA: "Eat only foods that are beige-colored", optionB: "Eat only foods that are green-colored" },
    { optionA: "Your drinks are always the wrong temperature", optionB: "Your food is always the wrong temperature" },
    { optionA: "Have a personal chef who hates you", optionB: "Cook every meal yourself with limited ingredients" },
    { optionA: "Every food tastes like its smell suggests", optionB: "Every food tastes completely opposite to its smell" },
    { optionA: "Only eat raw foods forever", optionB: "Only eat cooked foods forever" },
    { optionA: "Gain the ability to taste colors", optionB: "Gain the ability to hear flavors" },
    { optionA: "Always sneeze directly after your first bite", optionB: "Always hiccup throughout every meal" },
    { optionA: "Every dessert you eat turns savory mid-bite", optionB: "Every savory dish turns sweet mid-bite" },
    { optionA: "Never eat anything that required more than 5 ingredients", optionB: "Never eat anything that required fewer than 20 ingredients" },
    { optionA: "Eat a mystery meal every day — could be amazing or terrible", optionB: "Eat a guaranteed decent meal you already know" },
    { optionA: "Always taste a faint hint of soap in your food", optionB: "Always taste a faint hint of metal in your food" },
    { optionA: "Be allergic to your current favorite food", optionB: "Be forced to eat your least favorite food daily" },
    { optionA: "Never eat at restaurants again", optionB: "Never cook at home again" },
    { optionA: "Every meal comes with a 10-minute wait", optionB: "Every meal must be eaten in under 2 minutes" },
    { optionA: "Permanently have the taste buds of a picky 6-year-old", optionB: "Permanently crave extremely exotic and rare foods only" },
    { optionA: "Always smell garbage faintly while eating", optionB: "Always hear someone chewing loudly nearby while eating" },
    { optionA: "Food nourishes you perfectly but has no flavor", optionB: "Food is delicious but provides zero nutrition" },
    { optionA: "Only eat food you grew or made yourself", optionB: "Only eat food prepared by strangers" },
    { optionA: "All liquids taste like water", optionB: "Water tastes like medicine" },
    { optionA: "Never eat bread or grains again", optionB: "Never eat meat or fish again" },
    { optionA: "Have a stomach that digests everything in 5 minutes — always hungry", optionB: "Feel full for 12 hours after one meal — but miss enjoying food" },
    { optionA: "Only eat foods that are circular in shape", optionB: "Only eat foods that are rectangular in shape" },
    { optionA: "Your sense of taste is 10x stronger — flavor is overwhelming", optionB: "Your sense of taste is 10x weaker — everything is faint" },
    { optionA: "Eat a five-course meal every day with strangers", optionB: "Eat a simple sandwich alone every day" },
    { optionA: "Every food you eat has the texture of jello", optionB: "Every food you eat has the texture of dry crackers" },
    { optionA: "Always drink your meals as smoothies", optionB: "Always eat your drinks as solids" },
    { optionA: "Only eat food that was fashionable in the 1970s", optionB: "Only eat food that is currently a trendy superfood" },
    { optionA: "Never season food again", optionB: "Never eat unseasoned food again — every dish is intensely spiced" },
    { optionA: "Every bite you take is slightly too big", optionB: "Every bite you take is annoyingly small" },
    { optionA: "Eat ice cream that melts the moment you touch it", optionB: "Eat soup that's always on the verge of burning your tongue" },
    { optionA: "Always taste phantom sweetness after every meal", optionB: "Always taste phantom bitterness after every meal" },
    { optionA: "Only eat foods beginning with the letter 'C'", optionB: "Only eat foods beginning with the letter 'S'" },
    { optionA: "Gain perfect memory of every meal you've ever eaten", optionB: "Forget every meal the moment you finish it" },
    { optionA: "Every drink you consume makes a loud slurping sound regardless", optionB: "Every time you eat, you involuntarily hum" },
    { optionA: "Eat unlimited amounts of mediocre food", optionB: "Eat a tiny portion of the most incredible food once a day" },
    { optionA: "Only eat breakfast foods for every meal", optionB: "Only eat dinner foods for every meal including breakfast" },
    { optionA: "All vegetables taste like candy", optionB: "All candy tastes like vegetables" },
    { optionA: "Never use utensils again — eat everything with your hands", optionB: "Always need two forks to eat everything, even soup" },
    { optionA: "Every meal is interrupted by someone describing their diet", optionB: "Every meal is interrupted by someone asking if you're going to finish that" },
    { optionA: "Have a new food allergy every month that rotates", optionB: "Have one permanent severe food allergy to something you love" },
    { optionA: "Only eat foods that are white or pale in color", optionB: "Only eat foods that are bright red" },
    { optionA: "Eat in complete darkness for every meal", optionB: "Eat only while being watched by a small audience" },
    { optionA: "Every meal appears to be something else visually — you never know what you're getting", optionB: "Every meal is exactly what it looks like — perfectly predictable" },
    { optionA: "Always cry while eating spicy food even if it's mild", optionB: "Always laugh uncontrollably while eating sour food" },
    { optionA: "Never experience food coma again but also never experience food satisfaction", optionB: "Always feel food coma after every meal no matter how small" },
    { optionA: "Eat a meal that smells incredible but tastes average", optionB: "Eat a meal that tastes incredible but smells terrible" },
    { optionA: "Every food you eat turns slightly purple in your mouth", optionB: "Every food you eat crackles like pop rocks when you chew it" },
    { optionA: "Gain the ability to cook any dish perfectly from memory", optionB: "Gain the ability to identify any ingredient by taste alone" },
    { optionA: "Only eat foods that take over 2 hours to prepare", optionB: "Only eat foods that can be made in under 5 minutes" },
    { optionA: "Be a world-class chef but hate eating", optionB: "Love eating more than anything but be unable to cook" },
    { optionA: "Every meal must be eaten standing up", optionB: "Every meal must be eaten lying down" },
    { optionA: "Always feel like you're eating at a fancy restaurant", optionB: "Always feel like you're eating at a gas station" },
    { optionA: "Have your meals rated aloud by Gordon Ramsay every day", optionB: "Have your meals silently judged and scored by a panel of strangers" },
    { optionA: "Food can only satisfy you if it's shared with others", optionB: "Food can only satisfy you if eaten completely alone" },
    { optionA: "Only eat foods that float", optionB: "Only eat foods that sink in water" },
    { optionA: "Every meal comes with a dramatic backstory you must listen to", optionB: "Every meal must be eaten in complete silence or it tastes worse" },
    { optionA: "Taste every dish as if it's your first time experiencing flavor", optionB: "Taste every dish as if you've had it thousands of times and are bored" },
    { optionA: "Never eat hot food again", optionB: "Never eat cold food again" },
    { optionA: "Always feel slight guilt after eating something delicious", optionB: "Never enjoy guilty pleasures — healthy food is the only thing satisfying" },
    { optionA: "Your food always arrives 30 minutes late but is perfect", optionB: "Your food always arrives instantly but is slightly off" },
    { optionA: "Chew every bite exactly 32 times by compulsion", optionB: "Swallow every bite whole like a snake — painlessly but still weird" },
    { optionA: "Only drink beverages that are carbonated", optionB: "Only drink beverages that are completely flat" },
    { optionA: "Always eat your dessert before your meal", optionB: "Never eat dessert at all" },
    { optionA: "Have unlimited access to every food but it all must be shared", optionB: "Have limited access to food but every bite is exclusively yours" },
  ],

  "Silly & Bizarre": [
    { optionA: "Hiccup confetti every time you're surprised", optionB: "Sneeze glitter every time you laugh" },
    { optionA: "Have jazz hands permanently — your hands shake rhythmically non-stop", optionB: "Have jazz music play faintly whenever you enter a room" },
    { optionA: "Only be able to travel by office chair — no other seated transportation", optionB: "Only be able to travel by shopping cart pushed by a stranger" },
    { optionA: "Randomly quack like a duck once a day at an unpredictable moment", optionB: "Randomly moonwalk for 10 seconds once a day involuntarily" },
    { optionA: "Speak in a different accent every hour that you can't control", optionB: "Speak in a dramatic movie trailer voice for 10 seconds every hour" },
    { optionA: "Wear a cape everywhere but no one can know why", optionB: "Wear a top hat everywhere but it falls off whenever someone looks at you" },
    { optionA: "Every time you sit down, you make a dramatic exhale sound", optionB: "Every time you stand up, you say 'and we're back' quietly to yourself" },
    { optionA: "Your shadow does a slightly different dance than what you're doing", optionB: "Your reflection waves at you half a second after you do" },
    { optionA: "Only be able to open doors by kicking them gently with one foot", optionB: "Only be able to open doors by saying 'open sesame' — and it works" },
    { optionA: "Gain an entourage of five pigeons that follow you everywhere", optionB: "Gain a single very judgmental squirrel that sits on your shoulder all day" },
    { optionA: "Your phone autocorrects every message to be about cheese", optionB: "Your phone autocorrects every message to be about boats" },
    { optionA: "Every time you sneeze, flower petals come out instead of normal sneeze things", optionB: "Every time you yawn, tiny bubbles float out of your mouth" },
    { optionA: "Your laugh is perfectly silent but your body shakes violently", optionB: "Your laugh is the loudest sound in any room but completely deadpan face" },
    { optionA: "Walk into every room like you're in a slow-motion movie scene", optionB: "Exit every room as if leaving a stage — backwards, with flair" },
    { optionA: "Narrate your own life in third person out loud for 10 minutes daily", optionB: "Have someone else narrate your life in third person 10 minutes a day" },
    { optionA: "Carry a briefcase everywhere but it's always empty and you refuse to explain", optionB: "Carry an umbrella everywhere but never use it and refuse to explain" },
    { optionA: "Every time you walk through a doorway you forget what you were doing — always", optionB: "Every time you walk down stairs you feel the urge to narrate each step" },
    { optionA: "Your sneezes sound like a dial-up modem connecting", optionB: "Your coughs sound like a tiny car engine starting up" },
    { optionA: "Randomly sprout tiny fairy wings for exactly one minute per day", optionB: "Randomly glow faintly for exactly one minute per day" },
    { optionA: "Always have dramatic wind blowing your hair even indoors", optionB: "Always have cinematic lighting following you wherever you go" },
    { optionA: "Every time you're confident, a spotlight appears on you from nowhere", optionB: "Every time you're nervous, soft rain falls only on you" },
    { optionA: "Have the ability to communicate with inanimate objects — but they're boring", optionB: "Have inanimate objects communicate with you — but they're rude" },
    { optionA: "Your footsteps sound like high heels no matter what shoes you're wearing", optionB: "Your footsteps sound like squeaky toys no matter what you're wearing" },
    { optionA: "Involuntarily do a tiny bow after everything you say", optionB: "Involuntarily do finger guns after everything someone says to you" },
    { optionA: "Your name is mispronounced differently by every single person you meet", optionB: "Everyone you meet calls you a slightly different wrong name" },
    { optionA: "Be followed by a documentary crew for one week but they never explain why", optionB: "Be subtly followed by a single photographer for one week — only candid shots" },
    { optionA: "Every email you send arrives with a tiny illustration you didn't make", optionB: "Every email you receive comes with a random poem attached" },
    { optionA: "Your chair spins slightly every time you sit in it regardless of type", optionB: "Any chair you sit on is always slightly too high or too low" },
    { optionA: "Gain the ability to make any sound effect with your mouth — involuntarily during meetings", optionB: "Gain the ability to beatbox — but only when you're trying to be serious" },
    { optionA: "Every time you type, typewriter sounds play at full volume", optionB: "Every time you scroll on your phone, a cash register ding plays" },
    { optionA: "Have a personal theme song that plays softly only when you're confident", optionB: "Have sad trombone music play softly only when you're embarrassed" },
    { optionA: "All your food arrives with tiny flags stuck in it", optionB: "All your drinks come with a tiny umbrella regardless of context" },
    { optionA: "For one hour a day, walk with an exaggerated villain stride", optionB: "For one hour a day, walk with an exaggerated superhero landing pose" },
    { optionA: "Every time you're excited, confetti falls from your hands", optionB: "Every time you're bored, a tumbleweed rolls past" },
    { optionA: "Have a laugh track play after everything you say for one day a week", optionB: "Have dramatic orchestral stings play after everything you say for one day a week" },
    { optionA: "Be unable to say the word 'yes' — must use an enthusiastic synonym every time", optionB: "Be unable to say the word 'no' — must use a dramatic synonym every time" },
    { optionA: "Your alarm clock plays a different bizarre sound every morning", optionB: "Your alarm clock plays one very specific 8-bit song every morning forever" },
    { optionA: "Every photo of you looks like you're posing for a yearbook despite doing nothing", optionB: "Every photo of you looks like a Renaissance portrait regardless of setting" },
    { optionA: "For one day a week, your inner monologue is audible to only animals", optionB: "For one day a week, animals' thoughts are audible only to you" },
    { optionA: "Your handshakes always result in a tiny electric spark — not painful, just weird", optionB: "Your high-fives always produce a tiny puff of smoke — dramatic but harmless" },
    { optionA: "Always be introduced by an announcer — even in casual situations", optionB: "Always receive a round of applause when you enter a room — from everyone" },
    { optionA: "Have a tiny thunderstorm cloud that follows just you indoors once a week", optionB: "Have a ray of sunshine follow just you indoors once a week" },
    { optionA: "Your grocery bags always have exactly one thing sticking out awkwardly", optionB: "Your grocery bags always rip at the most inconvenient moment" },
    { optionA: "Every time you lose at something, a tiny parade plays for the winner in front of you", optionB: "Every time you win at something, sad music plays quietly for everyone else" },
    { optionA: "Have a tiny fan blowing your hair dramatically whenever you make a decision", optionB: "Have a tiny spotlight on you whenever you deliver news to someone" },
    { optionA: "Every selfie you take has a photobomber you never see coming", optionB: "Every group photo you're in, you blink at the exact wrong moment" },
    { optionA: "Your sneezes reset every electronic device in a 3-foot radius", optionB: "Your burps briefly scramble all nearby Bluetooth connections" },
    { optionA: "Have the coordination of a golden retriever puppy for one hour a day", optionB: "Have the grace of a seasoned ballet dancer but only when carrying fragile things" },
    { optionA: "Speak exclusively in questions for one full day per week", optionB: "Speak exclusively in statements that sound like questions for one full day per week" },
    { optionA: "Every door you open plays a dramatic sound effect", optionB: "Every time you close a door, someone nearby applauds" },
    { optionA: "Wear an invisible crown that everyone can somehow sense and respect", optionB: "Carry an invisible briefcase that everyone somehow respects you for" },
    { optionA: "Involuntarily announce the weather out loud every time you step outside", optionB: "Involuntarily announce the time out loud every hour on the hour" },
    { optionA: "Have a parrot that repeats only your most embarrassing statements", optionB: "Have a parrot that narrates your daily activities in suspenseful tones" },
    { optionA: "Every list you write comes back sorted alphabetically by someone", optionB: "Every list you write is mysteriously rearranged by someone overnight" },
    { optionA: "Make a dramatic entrance to every room even if you're just getting a glass of water", optionB: "Make a dramatic exit from every room even if you're coming right back" },
    { optionA: "Have a butler who is incredibly passive-aggressive", optionB: "Have a butler who is wildly over-enthusiastic about every tiny task" },
    { optionA: "Every time you win an argument, a tiny trophy appears and then vanishes", optionB: "Every time you lose an argument, a scoreboard briefly appears in the air" },
    { optionA: "Accidentally use emojis in professional emails that you can't delete", optionB: "Accidentally send voice messages instead of texts — always at the wrong time" },
    { optionA: "Your GPS gives directions in the voice of a very dramatic Shakespearean actor", optionB: "Your GPS gives directions using only song lyrics" },
    { optionA: "Have an alarm for everything — including when to blink", optionB: "Forget every alarm you set the moment you set it" },
    { optionA: "Your shopping cart always veers dramatically to the left", optionB: "Your shopping cart always has one wheel that squeaks at maximum volume" },
    { optionA: "Every mirror you look in briefly shows a slightly cooler version of you", optionB: "Every mirror shows you in the exact outfit you wore on your most embarrassing day" },
    { optionA: "Have a tiny marching band that follows you on major life decisions", optionB: "Have a tiny cheering squad that appears whenever you complete a chore" },
    { optionA: "Your sneezes make nearby plants lean slightly toward you", optionB: "Your laughter makes nearby electronics dim briefly" },
    { optionA: "Every pencil you pick up is always in need of sharpening", optionB: "Every pen you pick up is always running out of ink" },
    { optionA: "Your resting face looks like you just remembered something mildly embarrassing", optionB: "Your resting face looks like you're judging a poorly-made sandwich" },
    { optionA: "Have the ability to summon pigeons by whistling — one too many always show up", optionB: "Have the ability to summon cats by snapping — they always judge you" },
    { optionA: "Carry a boombox on your shoulder playing your perfect theme song", optionB: "Have a string quartet follow you playing ambient background music all day" },
    { optionA: "Every time you're late, time slows down just for you so others notice more", optionB: "Every time you're early, time speeds up so you still seem late" },
    { optionA: "Have a floating name tag that everyone can see but you cannot change", optionB: "Have a floating thought bubble that shows your last dream — just for one hour daily" },
    { optionA: "Your socks are always slightly mismatched — even if you buy identical pairs", optionB: "Your shoes are always on the correct feet — impossibly, satisfyingly correct" },
    { optionA: "Have an invisible coin that lands on tails every single time", optionB: "Have an invisible die that always rolls a 3" },
    { optionA: "Every time you solve a problem, a tiny firework pops quietly nearby", optionB: "Every time you cause a problem, a tiny sad trombone plays quietly nearby" },
    { optionA: "Involuntarily narrate actions as if writing stage directions", optionB: "Involuntarily add sound effects out loud for actions as you do them" },
    { optionA: "Your morning alarm is a crowd of tiny robots cheering you on", optionB: "Your morning alarm is a disappointed life coach delivering a motivational speech" },
    { optionA: "Blink in slow motion exactly once every hour", optionB: "Yawn in fast forward exactly once every hour" },
    { optionA: "Every time you lie, your left eyebrow raises involuntarily", optionB: "Every time you exaggerate, glitter falls from your hair" },
    { optionA: "Have a dramatic orchestral swell play every time you open a fridge", optionB: "Have a crowd gasp every time you open a package" },
    { optionA: "Your umbrella inverts every time it's windy — but nowhere else", optionB: "Your umbrella opens itself whenever it's sunny — never when it rains" },
  ],

  "Relationships & Social": [
    { optionA: "Have one best friend who always shows up for you", optionB: "Have a large social circle that's always fun but not deeply close" },
    { optionA: "Know every secret about your friends", optionB: "Have your friends know every secret about you" },
    { optionA: "Be the person everyone calls when they need advice", optionB: "Be the person everyone calls when they want to have fun" },
    { optionA: "Always say exactly what you're thinking in social situations", optionB: "Never be able to say what you're really thinking in social situations" },
    { optionA: "Have a close friend group that shrinks every year", optionB: "Have a growing social circle where no relationship ever deepens" },
    { optionA: "Be loved by strangers but misunderstood by people close to you", optionB: "Be deeply understood by those close to you but overlooked by the world" },
    { optionA: "Have perfect online communication but struggle in person", optionB: "Be magnetic in person but completely awkward in digital communication" },
    { optionA: "Attend one large social event per week that energizes you", optionB: "Have one meaningful one-on-one conversation per week that fulfills you" },
    { optionA: "Always be the first to reach out in friendships", optionB: "Always wait to be reached out to — and people always do" },
    { optionA: "Have a family that's chaotic and loud but deeply supportive", optionB: "Have a family that's calm and quiet but emotionally distant" },
    { optionA: "Have a partner who is your opposite in every way", optionB: "Have a partner who is exactly like you in every way" },
    { optionA: "Be famous in your close community but unknown everywhere else", optionB: "Be anonymous in your community but recognized globally" },
    { optionA: "Always be the one who plans gatherings", optionB: "Always be the one who never plans but always shows up" },
    { optionA: "Have friends who always challenge you intellectually", optionB: "Have friends who always make you laugh without fail" },
    { optionA: "Know everyone at a party but have no deep conversations", optionB: "Know no one at a party but have one life-changing conversation" },
    { optionA: "Be the most popular person in a small town", optionB: "Be completely unknown in a big city" },
    { optionA: "Have a group chat that's always active and slightly overwhelming", optionB: "Have a completely silent group chat that somehow makes everyone feel connected" },
    { optionA: "Always forgive too easily in relationships", optionB: "Never forgive easily — hold boundaries firmly but miss reconciliation" },
    { optionA: "Be the person your friends vent to but never vent yourself", optionB: "Be the person who vents freely but whose friends never open up" },
    { optionA: "Have deep connections that require a lot of maintenance", optionB: "Have easy friendships that never go very deep" },
    { optionA: "Lose touch with your childhood friends completely", optionB: "Stay in contact with every childhood friend even though you've both changed" },
    { optionA: "Have a sibling who is your best friend and constant presence", optionB: "Be an only child with complete independence and privacy" },
    { optionA: "Be irresistibly charming at parties but exhausted afterward", optionB: "Be quiet at parties but genuinely recharged and fulfilled afterward" },
    { optionA: "Have a romantic partner who never says how they feel but always shows it", optionB: "Have a romantic partner who always says how they feel but rarely shows it" },
    { optionA: "Have friends who push you to grow even when it's uncomfortable", optionB: "Have friends who accept you as you are without pushing for change" },
    { optionA: "Be in a friend group where everyone is wildly different from you", optionB: "Be in a friend group where everyone shares your values and interests" },
    { optionA: "Always know when a friendship is fading and be unable to stop it", optionB: "Never notice when a friendship is fading — it just quietly ends" },
    { optionA: "Have the social memory of everyone you've met — every detail", optionB: "Have zero memory of social interactions but always make a great impression" },
    { optionA: "Be invited to everything but never the first choice", optionB: "Be rarely invited but always the first choice when you are" },
    { optionA: "Have a mentor who's brutally honest and incredibly helpful", optionB: "Have a mentor who's always kind but rarely says anything useful" },
    { optionA: "Have friends who always show up physically but are emotionally absent", optionB: "Have friends who are always emotionally present but rarely physically available" },
    { optionA: "Be the person in your group who always keeps secrets perfectly", optionB: "Be the person in your group who always accidentally spills small secrets" },
    { optionA: "Have social anxiety that fades completely once you arrive", optionB: "Feel perfectly comfortable anticipating events but anxious once you're there" },
    { optionA: "Always know the right thing to say but say it too late", optionB: "Always speak immediately but sometimes say the wrong thing" },
    { optionA: "Have a partner who is your greatest fan but your harshest critic", optionB: "Have a partner who is your constant cheerleader but never gives real feedback" },
    { optionA: "Be the most reliable person everyone knows — to your own detriment", optionB: "Be the most spontaneous person everyone knows — to everyone else's occasional detriment" },
    { optionA: "Have your personal life completely private but your professional life public", optionB: "Have your professional life completely private but your personal life public" },
    { optionA: "Be deeply vulnerable with a few people", optionB: "Be slightly open with many people" },
    { optionA: "Have a romantic partner who everyone loves but you have doubts about", optionB: "Have a romantic partner you love completely but others don't understand" },
    { optionA: "Have friends who are honest even when it hurts", optionB: "Have friends who protect your feelings even if not always truthful" },
    { optionA: "Always be the one to apologize first even when not at fault", optionB: "Never apologize first — always wait for the other person" },
    { optionA: "Live in a community where everyone knows your name and story", optionB: "Live in a community where you're anonymous and independent" },
    { optionA: "Have a very active social media presence that's a curated version of you", optionB: "Have no social media presence — exist entirely in real life" },
    { optionA: "Have all your friendships survive every life change", optionB: "Naturally outgrow friendships and find better-fitting ones" },
    { optionA: "Be the person who makes every gathering memorable", optionB: "Be the person who makes every gathering comfortable and easy" },
    { optionA: "Have a close friend tell you a hard truth that changes your life", optionB: "Have a close friend keep a hard truth from you to protect your feelings" },
    { optionA: "Always be the last to leave social gatherings", optionB: "Always be the first to leave social gatherings" },
    { optionA: "Have your relationships defined by shared experiences", optionB: "Have your relationships defined by shared values" },
    { optionA: "Be the person who always initiates but never needs to reciprocate", optionB: "Be the person who never initiates but is always warmly welcomed when they do" },
    { optionA: "Have a partner who challenges your worldview constantly", optionB: "Have a partner who shares your worldview completely" },
    { optionA: "Be surrounded by people who admire you from a distance", optionB: "Be surrounded by people who know you imperfectly but love you anyway" },
    { optionA: "Have a large family gathering every holiday", optionB: "Have a quiet holiday alone or with one or two people" },
    { optionA: "Know every person in your life will stay loyal forever", optionB: "Not know who will stay loyal — but the ones who do are extraordinary" },
    { optionA: "Have a friendship that feels like home", optionB: "Have a friendship that feels like an adventure" },
    { optionA: "Be deeply rooted in one community your whole life", optionB: "Build new communities everywhere you go" },
    { optionA: "Have a partner who loves grand romantic gestures", optionB: "Have a partner who expresses love through small consistent actions" },
    { optionA: "Always feel slightly out of place in social settings but still welcomed", optionB: "Always feel perfectly at ease socially but never feel truly seen" },
    { optionA: "Reconnect with every lost friendship at once", optionB: "Completely close the chapter on every past relationship cleanly" },
    { optionA: "Have people who truly know you but you rarely see them", optionB: "Have people you see constantly but who don't truly know you" },
    { optionA: "Be the kind of friend people call in crisis", optionB: "Be the kind of friend people call to celebrate" },
    { optionA: "Have every acquaintance turn into a deep friendship eventually", optionB: "Have every deep friendship slowly become a warm acquaintance" },
    { optionA: "Be someone others depend on heavily", optionB: "Be someone others admire from a distance but never lean on" },
    { optionA: "Have a social life that revolves around activities and doing", optionB: "Have a social life that revolves around talking and being" },
    { optionA: "Have strangers like you instantly but friends take time to warm up", optionB: "Have friends love you deeply but struggle to make good first impressions" },
    { optionA: "Know every relationship in your life has an expiration date", optionB: "Believe every relationship could last forever but live with uncertainty" },
    { optionA: "Be the glue that holds your friend group together", optionB: "Be the wildcard that makes your friend group interesting" },
    { optionA: "Have a partner who never forgets anything about you", optionB: "Have a partner who always surprises you with new things they notice" },
    { optionA: "Value loyalty above all else in friendships", optionB: "Value growth above all else in friendships" },
    { optionA: "Have relationships built on radical honesty", optionB: "Have relationships built on radical acceptance" },
    { optionA: "Always know how your friends truly feel about you", optionB: "Never know — but always assume the best" },
    { optionA: "Have a big chosen family you built yourself", optionB: "Have a tight biological family that's always there" },
    { optionA: "Be the first person your friends call with good news", optionB: "Be the first person your friends call with bad news" },
    { optionA: "Have friends who celebrate your wins loudly", optionB: "Have friends who support your losses quietly" },
    { optionA: "Have a social life that looks boring but feels deeply rich", optionB: "Have a social life that looks exciting but feels quietly lonely" },
    { optionA: "Know your presence always changes the energy of a room", optionB: "Move through rooms invisibly but observe everything" },
    { optionA: "Have relationships that require vulnerability from the start", optionB: "Have relationships that build slowly into vulnerability over time" },
    { optionA: "Be unconditionally loved by a small number of people", optionB: "Be conditionally appreciated by a large number of people" },
  ],

  "Philosophy & Morality": [
    { optionA: "Save one person you love from certain death", optionB: "Save five strangers from certain death" },
    { optionA: "Live in a world with perfect justice but no mercy", optionB: "Live in a world with infinite mercy but no justice" },
    { optionA: "Always know the truth even when it's devastating", optionB: "Believe comforting lies that make life more bearable" },
    { optionA: "Have complete free will with unpredictable outcomes", optionB: "Have a predetermined destiny that's guaranteed to be good" },
    { optionA: "Be remembered forever for something morally ambiguous", optionB: "Be forgotten completely despite living an impeccably good life" },
    { optionA: "Have enormous power with great responsibility and consequence", optionB: "Have no power with no responsibility and no consequence" },
    { optionA: "Know the exact date of your death", optionB: "Never know when you'll die but have no way to prepare" },
    { optionA: "Live a short life of extraordinary impact", optionB: "Live a long life of quiet contentment with little impact" },
    { optionA: "Do the right thing and suffer for it", optionB: "Do the wrong thing and prosper quietly" },
    { optionA: "Know every answer to every question but be unable to share them", optionB: "Never know any answers but have the gift of perfect questions" },
    { optionA: "Sacrifice your happiness for the world's benefit", optionB: "Prioritize your happiness knowing the world is slightly worse for it" },
    { optionA: "Live in a just world with no freedom", optionB: "Live in a free world with no justice" },
    { optionA: "Have complete knowledge of your own moral failures", optionB: "Have complete blindness to your own moral failures" },
    { optionA: "Be the judge of what's right for everyone", optionB: "Have no say in what's right — follow rules set by someone wiser" },
    { optionA: "Prevent a great injustice by becoming a liar permanently", optionB: "Remain honest forever while a great injustice continues unchecked" },
    { optionA: "Forgive someone undeserving to free yourself", optionB: "Withhold forgiveness and carry the weight forever" },
    { optionA: "Know that your choices are fully determined by prior causes", optionB: "Believe you have free will but frequently make choices you regret" },
    { optionA: "Have your entire moral philosophy proven correct after you die", optionB: "Live to see your moral philosophy proven wrong" },
    { optionA: "Change one historical atrocity but alter the present unpredictably", optionB: "Leave history as is and guarantee a stable but imperfect present" },
    { optionA: "Live according to strict rules that always lead to good outcomes", optionB: "Live by pure intuition that sometimes leads to great and sometimes terrible outcomes" },
    { optionA: "Know that consciousness ends at death", optionB: "Believe in an afterlife but never know for certain" },
    { optionA: "Have everyone treated equally regardless of circumstance", optionB: "Have everyone treated according to their unique circumstance" },
    { optionA: "Expose a painful truth that helps many but destroys one person", optionB: "Protect one person by keeping a truth that harms many" },
    { optionA: "Eliminate suffering by eliminating joy — they come as a pair", optionB: "Keep both suffering and joy — inseparable and defining" },
    { optionA: "Live in a world where every action has a visible moral score", optionB: "Live in a world where every action's moral weight is completely hidden" },
    { optionA: "Have the ability to end an unjust war with one lie", optionB: "Speak only truth and watch the war continue" },
    { optionA: "Be fully responsible for every choice you've ever made", optionB: "Partially absolve your choices because of circumstances you didn't choose" },
    { optionA: "Know that good intentions always justify harmful outcomes", optionB: "Know that good outcomes always justify harmful intentions" },
    { optionA: "Have the world remember you as a villain for a heroic act", optionB: "Have the world remember you as a hero for a selfish one" },
    { optionA: "Live a life that means nothing to history but everything to those around you", optionB: "Live a life that shapes history but means little to those closest to you" },
    { optionA: "Have perfect moral clarity in every situation", optionB: "Live with moral ambiguity but deep empathy" },
    { optionA: "Be punished for a crime you didn't commit to save a system that works", optionB: "Go free for a crime you did commit and watch the system fail" },
    { optionA: "Cause harm unintentionally and face consequences", optionB: "Intend harm but cause no damage and face no consequences" },
    { optionA: "Know that morality is objective and universal", optionB: "Know that morality is subjective and constructed — and act accordingly" },
    { optionA: "Give up your identity to serve a cause greater than yourself", optionB: "Preserve your identity while contributing in smaller, personal ways" },
    { optionA: "Have full knowledge of every life your choices affected", optionB: "Have zero knowledge of how your choices affected others" },
    { optionA: "Live in a world where lying is impossible", optionB: "Live in a world where complete honesty is illegal" },
    { optionA: "Be the trolley problem conductor — choose who lives", optionB: "Be a bystander to the trolley problem — watch and do nothing" },
    { optionA: "Rewrite history to save millions at the cost of erasing your existence", optionB: "Preserve your existence knowing millions suffered unnecessarily" },
    { optionA: "Have the wisdom to always know what's right but lack the courage to act", optionB: "Have the courage to always act but lack the wisdom to know if it's right" },
    { optionA: "Live by a moral code inherited from your culture unquestioned", optionB: "Build your moral code from scratch through painful experience" },
    { optionA: "Have the power to read minds but lose all privacy yourself", optionB: "Have complete privacy but never understand another person's true intentions" },
    { optionA: "Sacrifice the few for the many — always", optionB: "Protect the few regardless — always" },
    { optionA: "Know that your life has a pre-written purpose", optionB: "Create your purpose in a universe of complete indifference" },
    { optionA: "Destroy something beautiful to save something functional", optionB: "Preserve something beautiful at the cost of something functional" },
    { optionA: "Have complete control over your mind but none over your circumstances", optionB: "Have complete control over your circumstances but none over your mind" },
    { optionA: "Know with certainty that you are a good person", optionB: "Strive forever to be good without ever knowing if you've succeeded" },
    { optionA: "Be judged by your intentions alone", optionB: "Be judged by your actions alone" },
    { optionA: "End poverty globally but eliminate all art permanently", optionB: "Keep art alive but accept that poverty is permanent" },
    { optionA: "Have justice that is swift and sometimes wrong", optionB: "Have justice that is slow and always right" },
    { optionA: "Carry the full weight of a past mistake that shaped you positively", optionB: "Forget the mistake entirely and lose everything it taught you" },
    { optionA: "Know exactly what legacy you'll leave before you die", optionB: "Never know your legacy but live with complete authenticity" },
    { optionA: "Have humanity united under a single moral code with zero freedom of belief", optionB: "Have humanity fractured into infinite moral perspectives — sometimes violently" },
    { optionA: "Live in a world that rewards virtue consistently", optionB: "Live in a world that rewards virtue randomly — sometimes not at all" },
    { optionA: "Have peace at the cost of truth", optionB: "Have truth at the cost of peace" },
    { optionA: "Know that your suffering has a greater purpose", optionB: "Know that your suffering is meaningless — and find peace with that" },
    { optionA: "Have absolute moral authority over your own life only", optionB: "Have partial moral authority over many lives" },
    { optionA: "Live according to what you believe rather than what works", optionB: "Live according to what works rather than what you believe" },
    { optionA: "Have full consciousness of every moral dilemma you face", optionB: "Make every moral choice intuitively — never aware of the dilemma" },
    { optionA: "Be someone who changes the world's institutions", optionB: "Be someone who changes individual hearts and minds" },
    { optionA: "Know that humans are fundamentally good", optionB: "Know that humans are fundamentally self-interested — and make peace with that" },
    { optionA: "Have a just society built by unjust means", optionB: "Have an unjust society built by perfectly moral means" },
    { optionA: "Hold a belief that makes your life harder but the world better", optionB: "Hold a belief that makes your life easier but the world slightly worse" },
    { optionA: "Be the last person on earth to maintain a principle no one else holds", optionB: "Abandon the principle knowing it's right but unworkable alone" },
    { optionA: "Have knowledge without wisdom", optionB: "Have wisdom without knowledge" },
    { optionA: "Die for something you believe in knowing it won't change anything", optionB: "Live compromised but ensure your cause survives" },
    { optionA: "Have a world where every person knows their moral worth", optionB: "Have a world where moral worth is never assigned or measured" },
    { optionA: "Be the judge at the end of time reviewing all of humanity", optionB: "Be judged at the end of time by a perfect arbiter" },
    { optionA: "Understand the universe completely but find no meaning in it", optionB: "Find profound meaning in the universe without understanding it at all" },
    { optionA: "Have your moral choices matter only to you", optionB: "Have your moral choices matter to everyone but yourself" },
    { optionA: "Live with total moral consistency even when it's harmful", optionB: "Live with moral flexibility that serves the moment but undermines principles" },
    { optionA: "Have a world where accountability is perfect and mercy is absent", optionB: "Have a world where mercy is perfect and accountability is absent" },
    { optionA: "Know that your values will outlive you by centuries", optionB: "Know your values die with you but were perfectly lived" },
    { optionA: "Lose everything in pursuit of justice", optionB: "Keep everything by accepting an unjust compromise" },
    { optionA: "Have clarity about what you owe others", optionB: "Have clarity about what you owe yourself" },
    { optionA: "Be morally ahead of your time and suffer for it", optionB: "Be morally aligned with your time and live comfortably" },
  ],
};
