export const WYR_PART3 = {
  "Tech & Gaming": [
    { optionA: "Play on PC forever", optionB: "Play on console forever" },
    { optionA: "Live in an MMO with thousands of players", optionB: "Only play single-player games for life" },
    { optionA: "Be always connected to the internet", optionB: "Be always offline" },
    { optionA: "Have a perfect AI assistant 24/7", optionB: "Figure everything out yourself" },
    { optionA: "Live in full-time VR", optionB: "Never use VR at all" },
    { optionA: "Have massive social media fame", optionB: "Be completely anonymous online" },
    { optionA: "Stream your entire life 24/7", optionB: "Leave zero digital footprint" },
    { optionA: "Code every project from scratch", optionB: "Let AI write all your code" },
    { optionA: "Only play retro games (pre-2000)", optionB: "Only play modern games (post-2015)" },
    { optionA: "Subscribe to every service but own nothing", optionB: "Own everything but no subscriptions" },
    { optionA: "Have a mechanical keyboard that never breaks", optionB: "Have a monitor with perfect infinite resolution" },
    { optionA: "Be the world's best speedrunner", optionB: "Be the world's best game developer" },
    { optionA: "Play games with no HUD ever", optionB: "Play games with max HUD and guides always on" },
    { optionA: "Have every game ever made but no internet", optionB: "Have only 5 games but the fastest internet" },
    { optionA: "Win every online match", optionB: "Never lose a single co-op run" },
    { optionA: "Always play on the hardest difficulty", optionB: "Always play on easy mode but enjoy every game" },
    { optionA: "Be trapped in your favorite video game world", optionB: "Have your favorite game characters exist in real life" },
    { optionA: "Have photographic memory for every game mechanic", optionB: "Have perfect aim in every shooter" },
    { optionA: "Be a top esports athlete", optionB: "Be the most-watched gaming streamer" },
    { optionA: "Get every game for free forever", optionB: "Get paid to play games but only ones you hate" },
    { optionA: "Have a robot that does all your chores", optionB: "Have an AI that handles all your emails and messages" },
    { optionA: "Experience the internet in 1995", optionB: "Experience the internet in 2050" },
    { optionA: "Have unlimited cloud storage", optionB: "Have a device that never runs out of battery" },
    { optionA: "Be first to use every new technology", optionB: "Wait and always get the perfected version" },
    { optionA: "Use only open-source software", optionB: "Use only proprietary premium software" },
    { optionA: "Have a self-driving car", optionB: "Have a flying personal drone" },
    { optionA: "Work on the team that built the first AGI", optionB: "Be the first human to live digitally" },
    { optionA: "Have perfect cybersecurity that can never be hacked", optionB: "Be able to hack any system in the world" },
    { optionA: "Only use a phone with a 1-week battery", optionB: "Only use a phone that charges in 10 seconds" },
    { optionA: "Have a 3D printer that can make anything", optionB: "Have a scanner that can replicate any physical object digitally" },
    { optionA: "Live in a fully smart home", optionB: "Live in a tech-free cabin with no devices" },
    { optionA: "Have your brain backed up to the cloud", optionB: "Have your memories deleted and start fresh" },
    { optionA: "Type at 300 words per minute", optionB: "Read code 10x faster than any human" },
    { optionA: "Only ever use voice commands for your devices", optionB: "Only ever use text input, no voice or touch" },
    { optionA: "Be a legendary game designer nobody knows", optionB: "Be a mediocre game designer the whole world loves" },
    { optionA: "Have Wi-Fi everywhere on Earth", optionB: "Have clean water everywhere on Earth" },
    { optionA: "Play a game where every NPC has real feelings", optionB: "Play a game where the world changes based on your real emotions" },
    { optionA: "Have augmented reality glasses you can never take off", optionB: "Have a neural chip that lets you learn any skill instantly" },
    { optionA: "Use tech from 20 years in the future", optionB: "Fully understand all tech available right now" },
    { optionA: "Always have the newest phone model", optionB: "Have a phone that never breaks or slows down" },
    { optionA: "Be a top modder for your favorite game", optionB: "Be an official game designer at a AAA studio" },
    { optionA: "Have infinite in-game currency in one game", optionB: "Have max level characters in every game you play" },
    { optionA: "Only game with strangers online", optionB: "Only game with people you know in person" },
    { optionA: "Experience a game glitch that breaks reality", optionB: "Find an easter egg nobody else has ever found" },
    { optionA: "Have a gaming setup worth $100,000", optionB: "Have a $500 setup but play better than anyone with any hardware" },
    { optionA: "Be able to pause real life like a game", optionB: "Be able to save and reload moments in your life" },
    { optionA: "Program in only one language forever (your choice)", optionB: "Know every programming language but master none" },
    { optionA: "Have a drone that can fly anywhere legally", optionB: "Have a submarine drone that can go anywhere underwater" },
    { optionA: "Have your favorite game updated with infinite new content", optionB: "Have your favorite game preserved exactly as it was at launch" },
    { optionA: "Be able to delete any app from existence", optionB: "Be able to make any app you imagine instantly" },
    { optionA: "Have infinite save slots in real life", optionB: "Have a mini-map of wherever you are in real life" },
    { optionA: "Only play games solo, never online", optionB: "Only play games in teams, never alone" },
    { optionA: "Have a smartwatch that predicts your health", optionB: "Have glasses that show you info about anything you look at" },
    { optionA: "Be a game journalist who shapes the industry", optionB: "Be an indie developer whose game changes culture" },
    { optionA: "Live through every era of gaming history in order", optionB: "Skip straight to gaming technology 50 years from now" },
    { optionA: "Have a perfect memory of every game you played", optionB: "Play every game for the first time again, fresh" },
    { optionA: "Own the original hardware for every console ever", optionB: "Have digital access to every game ever made" },
    { optionA: "Design the UI for the most-used app in the world", optionB: "Write the algorithm that runs the most-used app in the world" },
    { optionA: "Have a tech startup that fails but teaches you everything", optionB: "Work at a big tech company with no risk but limited learning" },
    { optionA: "Build a game in 48 hours that goes viral", optionB: "Spend 5 years on a masterpiece only critics love" },
    { optionA: "Have your data fully private from every company", optionB: "Share all your data but get personalized everything" },
    { optionA: "Only game on handheld devices", optionB: "Only game on full desktop setups" },
    { optionA: "Be the person who invented social media", optionB: "Be the person who ends social media addiction" },
    { optionA: "Have the ability to instantly learn any software", optionB: "Have the ability to debug any code by just looking at it" },
    { optionA: "Have unlimited free cloud gaming", optionB: "Have unlimited free local hardware upgrades every year" },
    { optionA: "Play a game that perfectly simulates your life", optionB: "Live a life that feels like a perfectly designed game" },
    { optionA: "Get notified every time someone talks about you online", optionB: "Have all mentions of you scrubbed from the internet" },
    { optionA: "Be the last human gamer in a world of AI players", optionB: "Be an AI player pretending to be human in competitive gaming" },
    { optionA: "Have a device that translates thoughts to text", optionB: "Have a device that lets you feel what characters in games feel" },
    { optionA: "Only use technology from your birth year forever", optionB: "Always use cutting-edge tech but relearn everything every year" },
  ],

  "Travel & Adventure": [
    { optionA: "Backpack solo through every continent", optionB: "Take luxury group tours to 10 iconic destinations" },
    { optionA: "Live in the same city your entire life", optionB: "Move to a new city every two years forever" },
    { optionA: "Speak every language fluently", optionB: "Teleport to any country instantly" },
    { optionA: "Visit every country once", optionB: "Return to one favorite country every year for life" },
    { optionA: "Summit the world's highest mountain peaks", optionB: "Explore the deepest parts of the ocean" },
    { optionA: "Survive extreme Arctic cold", optionB: "Survive extreme Saharan heat" },
    { optionA: "Go on a space tourism trip", optionB: "Go on a deep sea exploration mission" },
    { optionA: "Travel with unlimited budget but no photos allowed", optionB: "Travel on $10/day but document everything" },
    { optionA: "Travel to any place in history", optionB: "Travel to any place in the future" },
    { optionA: "Live on a sailboat crossing every ocean", optionB: "Live in a van exploring every road on Earth" },
    { optionA: "Visit every UNESCO World Heritage Site", optionB: "Visit every natural wonder of the world" },
    { optionA: "Travel alone forever but go anywhere", optionB: "Always travel with others but go where they choose" },
    { optionA: "Have a travel companion who plans everything", optionB: "Always travel spontaneously with zero plans" },
    { optionA: "Be a travel writer who influences millions", optionB: "Travel privately and tell no one" },
    { optionA: "Live in the mountains year-round", optionB: "Live on a tropical island year-round" },
    { optionA: "Experience zero gravity on a parachute jump", optionB: "Experience zero gravity on a space station" },
    { optionA: "Travel everywhere by train", optionB: "Travel everywhere by boat" },
    { optionA: "See the Northern Lights every night", optionB: "See a perfect sunset every single day" },
    { optionA: "Have a passport that grants visa-free access to every country", optionB: "Have a universal translator for every language" },
    { optionA: "Camp in the wild for a year", optionB: "Stay in luxury hotels for a year" },
    { optionA: "Be an archaeologist discovering ancient ruins", optionB: "Be an explorer mapping uncharted territories" },
    { optionA: "Hike the entire Appalachian Trail", optionB: "Kayak around the entire coastline of a continent" },
    { optionA: "Visit Antarctica before it changes", optionB: "Visit the Amazon before it changes" },
    { optionA: "Travel as a tourist with a guide", optionB: "Travel as a local wherever you go" },
    { optionA: "Always know the best hidden spots in any city", optionB: "Always find the best food in any country" },
    { optionA: "Cross every desert on Earth on foot", optionB: "Climb every volcano on Earth" },
    { optionA: "Be a pilot who flies to every country", optionB: "Be a ship captain who sails every sea" },
    { optionA: "Have a personal jet with no range limit", optionB: "Have a submarine that can go anywhere underwater" },
    { optionA: "Spend a month in total isolation in nature", optionB: "Spend a month in the most densely populated city" },
    { optionA: "Travel back in time to ancient Rome", optionB: "Travel forward to see Earth in 500 years" },
    { optionA: "Survive in the jungle for 30 days", optionB: "Survive in the Arctic for 30 days" },
    { optionA: "Experience every climate on Earth in one year", optionB: "Find your perfect climate and stay there forever" },
    { optionA: "Walk the Camino de Santiago alone", optionB: "Walk the Great Wall of China end to end" },
    { optionA: "Live as a digital nomad with no fixed home", optionB: "Have a dream home base and travel 3 months a year" },
    { optionA: "Be a travel photographer capturing the world", optionB: "Be a travel chef discovering cuisines everywhere" },
    { optionA: "Travel during the age of exploration with modern safety gear", optionB: "Travel the modern world with no technology at all" },
    { optionA: "See the Earth from orbit once", optionB: "Walk to the most remote place on Earth" },
    { optionA: "Speak no languages but travel freely", optionB: "Speak every language but never leave your country" },
    { optionA: "Live in a new country every 6 months for 10 years", optionB: "Live in one perfect foreign country for 10 years" },
    { optionA: "Swim with sharks in the open ocean", optionB: "Hike through a territory with wild predators" },
    { optionA: "Watch a solar eclipse from the ideal location", optionB: "Watch a total lunar eclipse from the Moon's surface" },
    { optionA: "Attend every major cultural festival on Earth", optionB: "Find and attend a festival nobody knows about" },
    { optionA: "Fly first class on every flight forever", optionB: "Have a private jet but economy seat quality inside" },
    { optionA: "Travel only with a backpack that fits under an airplane seat", optionB: "Travel with unlimited luggage anywhere you go" },
    { optionA: "Be the first person to set foot on every continent in one year", optionB: "Be the most deeply knowledgeable person about one country" },
    { optionA: "Drive Route 66 end to end on a motorcycle", optionB: "Drive the Pan-American Highway end to end" },
    { optionA: "Travel through post-apocalyptic ruins safely", optionB: "Travel to a hidden civilization nobody else knows about" },
    { optionA: "Have infinite frequent flyer miles", optionB: "Have free accommodation anywhere in the world forever" },
    { optionA: "See every major city skyline from above", optionB: "See every major city from street level up close" },
    { optionA: "Experience weightlessness in the ocean's depths", optionB: "Experience weightlessness in Earth's orbit" },
    { optionA: "Sleep under the stars every night for a year", optionB: "Sleep in a new hotel every night for a year" },
    { optionA: "Witness every natural phenomenon: tornado, eclipse, aurora, eruption", optionB: "Witness every human wonder: largest parade, biggest crowd, tallest structure" },
    { optionA: "Trek across the Silk Road historically", optionB: "Trek across the Silk Road today" },
    { optionA: "Run every major marathon on every continent", optionB: "Cycle across every continent" },
    { optionA: "Be lost in a new city with no phone and find your way", optionB: "Navigate remote wilderness with only a compass" },
    { optionA: "Be a cruise ship captain sailing the world", optionB: "Be a solo sailor circumnavigating the globe" },
    { optionA: "Visit every active volcano safely", optionB: "Visit every deep cave system safely" },
    { optionA: "Travel as a humanitarian to regions in need", optionB: "Travel as a scientist to the most extreme environments" },
    { optionA: "Spend a night in every type of unique accommodation: igloo, treehouse, underwater hotel", optionB: "Stay in the world's most iconic hotel for a month" },
    { optionA: "Ride every famous train route in the world", optionB: "Ride every famous river on Earth by boat" },
    { optionA: "Have a teleporter but can only use it once a week", optionB: "Travel by conventional means but with zero delays ever" },
    { optionA: "Explore the ocean floor in a personal submarine", optionB: "Explore Earth's atmosphere in a personal aircraft" },
    { optionA: "Be given a ticket to travel anywhere but must leave in 24 hours", optionB: "Plan your dream trip for a year with unlimited budget" },
    { optionA: "Travel to every country but forget all memories after", optionB: "Travel to only 5 countries with perfect lifelong memories" },
    { optionA: "Be a travel guide for extreme adventures", optionB: "Be a travel guide for cultural and culinary experiences" },
    { optionA: "Explore every country's most off-limits location", optionB: "Explore every country's most beloved hidden gem" },
    { optionA: "Live in a floating house on the ocean", optionB: "Live in a cliff-side house above a valley" },
    { optionA: "Walk every pilgrimage trail on Earth", optionB: "Walk every ancient trade route on Earth" },
    { optionA: "Travel to witness every endangered landscape before it disappears", optionB: "Travel only to thriving ecosystems and vibrant cultures" },
  ],

  "Career & Ambition": [
    { optionA: "Have your dream job but earn minimum wage", optionB: "Have a boring job but earn 10x your current salary" },
    { optionA: "Work from anywhere in the world", optionB: "Have the world's most perfect office environment" },
    { optionA: "Be famous and respected in your specific field", optionB: "Be universally famous but for something unrelated to your skills" },
    { optionA: "Retire at 40 with just enough money", optionB: "Work until 70 doing work you love every day" },
    { optionA: "Be remembered for your professional work", optionB: "Be remembered for your kindness and relationships" },
    { optionA: "Lead a large team toward a meaningful goal", optionB: "Work completely alone on projects you own fully" },
    { optionA: "Fail publicly and learn everything", optionB: "Succeed quietly and tell no one" },
    { optionA: "Build a startup that changes the world", optionB: "Work at an institution that has changed the world for centuries" },
    { optionA: "Master one skill beyond anyone alive", optionB: "Be competent in 50 diverse skills" },
    { optionA: "Be the youngest person to achieve your goal", optionB: "Be the oldest person to achieve your goal" },
    { optionA: "Have a mentor who shapes your entire career", optionB: "Be entirely self-taught and self-made" },
    { optionA: "Have a career that peaks early and fades", optionB: "Have a career that slowly grows your entire life" },
    { optionA: "Be a founder of a company you eventually lose control of", optionB: "Be employee #1 at a company that becomes the biggest in the world" },
    { optionA: "Have job security forever but no growth", optionB: "Have unlimited growth potential but constant uncertainty" },
    { optionA: "Be paid exactly what you're worth", optionB: "Be paid far more than you're worth but for meaningless work" },
    { optionA: "Write the book that defines your industry", optionB: "Give the speech that changes your industry" },
    { optionA: "Be a pioneer in a field nobody believes in yet", optionB: "Be the best in a field everyone already values" },
    { optionA: "Achieve your biggest career goal at 25", optionB: "Achieve your biggest career goal at 65" },
    { optionA: "Have the respect of your peers with no public recognition", optionB: "Have massive public recognition but be dismissed by peers" },
    { optionA: "Create something that outlives you by 100 years", optionB: "Create something massively impactful that disappears in 10 years" },
    { optionA: "Be promoted beyond your competence", optionB: "Be kept in a role below your true ability" },
    { optionA: "Work 80 hours a week on your passion", optionB: "Work 20 hours a week on something you tolerate" },
    { optionA: "Have a career that involves constant travel", optionB: "Have a career that lets you never leave your home" },
    { optionA: "Change careers completely every 10 years", optionB: "Dedicate your entire life to one career path" },
    { optionA: "Be a CEO of a small company you fully control", optionB: "Be a VP at a Fortune 500 company with massive resources" },
    { optionA: "Negotiate your salary perfectly every time", optionB: "Never negotiate but always be paid fairly automatically" },
    { optionA: "Have a job that makes headlines", optionB: "Have a job that makes a quiet but real difference" },
    { optionA: "Have unlimited resources but strict constraints", optionB: "Have unlimited freedom but minimal resources" },
    { optionA: "Be known as the hardest worker in your field", optionB: "Be known as the most creative thinker in your field" },
    { optionA: "Turn your hobby into your career", optionB: "Keep your hobby separate and love it forever" },
    { optionA: "Have every job interview go perfectly", optionB: "Never need another job interview again" },
    { optionA: "Be the person who fixes broken organizations", optionB: "Be the person who builds new organizations from zero" },
    { optionA: "Have a job that gives you summers off", optionB: "Have a job that gives you every Friday off year-round" },
    { optionA: "Be a consultant everyone wants", optionB: "Be a full-timer who builds something permanent" },
    { optionA: "Get your dream job at 22 and outgrow it by 30", optionB: "Spend your 20s figuring it out and find your calling at 35" },
    { optionA: "Have a career that crosses industries constantly", optionB: "Become the deepest expert in a single niche" },
    { optionA: "Win a Nobel Prize or equivalent in your field", optionB: "Quietly solve a problem that saves a million lives" },
    { optionA: "Have a boss who challenges you constantly", optionB: "Be your own boss with full accountability" },
    { optionA: "Do meaningful work for a corrupt organization", optionB: "Do ordinary work for an extraordinarily ethical organization" },
    { optionA: "Have a career that's misunderstood while you're alive but celebrated after", optionB: "Have a career celebrated now but forgotten in 50 years" },
    { optionA: "Be a trailblazer in your industry", optionB: "Be the person who perfects what trailblazers started" },
    { optionA: "Earn recognition from one person you deeply respect", optionB: "Earn recognition from a million strangers" },
    { optionA: "Have complete work-life balance but slower progress", optionB: "Sacrifice personal time and achieve your biggest goals faster" },
    { optionA: "Have a career that gives back to your community", optionB: "Have a career that changes policy at a national level" },
    { optionA: "Be hired for a role you're underqualified for and rise to it", optionB: "Be hired for a role you're overqualified for and transform it" },
    { optionA: "Never get fired but also never get a raise", optionB: "Be fired once but promoted dramatically after" },
    { optionA: "Have a job title everyone understands", optionB: "Have a job title nobody understands but everyone wants" },
    { optionA: "Have infinite patience with difficult colleagues", optionB: "Have the confidence to set limits with anyone at work" },
    { optionA: "Work in a field that saves lives", optionB: "Work in a field that enriches lives" },
    { optionA: "Be an entrepreneur who never stops building", optionB: "Be an intrapreneur who changes things from inside" },
    { optionA: "Have a career that makes your family proud", optionB: "Have a career that makes you proud regardless of what others think" },
    { optionA: "Get 10 job offers a year and pick freely", optionB: "Never job search again because opportunities always find you" },
    { optionA: "Have a career with a clear ladder to climb", optionB: "Have a career with no ladder but unlimited sideways exploration" },
    { optionA: "Fail fast and iterate at a startup", optionB: "Move carefully and build lasting things at a legacy institution" },
    { optionA: "Be mentored by the best in your field", optionB: "Have the freedom to make mistakes and learn your own way" },
    { optionA: "Be the best at a job nobody knows exists", optionB: "Be average at a job everyone admires" },
    { optionA: "Work in a collaborative, open office culture", optionB: "Work in complete solitude with full focus" },
    { optionA: "Be the person who makes the final call", optionB: "Be the person who gives the advice behind the final call" },
    { optionA: "Have your career driven by passion", optionB: "Have your career driven by purpose beyond yourself" },
    { optionA: "Build a career that earns you wealth", optionB: "Build a career that earns you legacy" },
    { optionA: "Have the corner office with the view", optionB: "Have the freedom to work from anywhere at any time" },
    { optionA: "Be on the Forbes 30 Under 30 list", optionB: "Be the mentor who puts 30 others on that list" },
    { optionA: "Lead a revolution in your industry", optionB: "Sustain and protect what makes your industry great" },
    { optionA: "Have a career with high highs and crushing lows", optionB: "Have a career of consistent moderate success with no failures" },
    { optionA: "Do the most visible work on your team", optionB: "Do the most essential work on your team that nobody notices" },
    { optionA: "Be overworked but paid extremely well", optionB: "Be relaxed but earning just enough" },
    { optionA: "Have every project you lead succeed", optionB: "Have the freedom to fail on a big project without consequence" },
    { optionA: "Be a specialist the world depends on", optionB: "Be a generalist who can thrive in any situation" },
    { optionA: "Have a career that started with a lucky break", optionB: "Have a career built entirely from grit with no luck at all" },
    { optionA: "Work at the intersection of two fields nobody has combined before", optionB: "Work at the core of the most established field in the world" },
  ],

  "Pop Culture": [
    { optionA: "Live in the Marvel Cinematic Universe", optionB: "Live in the DC Universe" },
    { optionA: "Be a beloved side character in your favorite show", optionB: "Be the main character of a critically panned show" },
    { optionA: "Have your favorite musician play your birthday party", optionB: "Attend the front row of their biggest stadium concert" },
    { optionA: "Live in Hogwarts", optionB: "Live in Middle Earth" },
    { optionA: "Be the last survivor in a horror film", optionB: "Never appear in a horror film at all" },
    { optionA: "Meet your favorite fictional character in real life", optionB: "Step into your favorite fictional world for one day" },
    { optionA: "Have a cameo in your favorite film", optionB: "Write the sequel to your favorite film" },
    { optionA: "Be the actor who played your favorite role", optionB: "Be the director who made your favorite film" },
    { optionA: "Live in Westeros before dragons died out", optionB: "Live in the Star Wars galaxy with no Force ability" },
    { optionA: "Be a contestant on the most popular reality TV show", optionB: "Be the producer who shapes what reality TV shows become" },
    { optionA: "Have every song you hum become a hit", optionB: "Have every idea you pitch get greenlit immediately" },
    { optionA: "Go viral for something you did intentionally", optionB: "Go viral for something accidental and harmless" },
    { optionA: "Win an Oscar for a film you wrote", optionB: "Win a Grammy for an album you produced" },
    { optionA: "Be best friends with the most iconic celebrity of your era", optionB: "Be the most iconic celebrity of your era" },
    { optionA: "Have your own Netflix documentary", optionB: "Have your own Netflix scripted series based on your life" },
    { optionA: "Be a beloved character in a video game universe", optionB: "Be a beloved character in an animated universe" },
    { optionA: "Be the last surviving member of your favorite band", optionB: "Be the newest member of your favorite band in its prime" },
    { optionA: "Know how every major TV show ends before it airs", optionB: "Never have anything spoiled but lose access to fan communities" },
    { optionA: "Star in a superhero blockbuster", optionB: "Star in an indie film that wins every award" },
    { optionA: "Be cast as a villain everyone loves to hate", optionB: "Be cast as a hero nobody appreciates" },
    { optionA: "Be a legendary music producer nobody knows", optionB: "Be a famous pop star everyone knows but who lacks depth" },
    { optionA: "Have your fan theory about a show turn out to be exactly right", optionB: "Have a show's creators base a storyline entirely on your idea" },
    { optionA: "Live in Wakanda", optionB: "Live in Panem from The Hunger Games" },
    { optionA: "Have the most-streamed song of the decade", optionB: "Write the most-quoted movie line of the decade" },
    { optionA: "Attend every major award show for free", optionB: "Attend every major music festival backstage for free" },
    { optionA: "Be a character who gets the best arc in a series", optionB: "Be a character who appears in every major franchise" },
    { optionA: "Have your book turned into a perfect film adaptation", optionB: "Have your screenplay turned into a film that wins Best Picture" },
    { optionA: "Have a fashion line that defines a decade", optionB: "Have a hairstyle that becomes the most iconic of the era" },
    { optionA: "Be the host of the most-watched late night show", optionB: "Be the most-listened-to podcast host of your time" },
    { optionA: "Live in Springfield (The Simpsons universe)", optionB: "Live in Pawnee (Parks and Recreation universe)" },
    { optionA: "Have a fictional character modeled after you", optionB: "Have a real person play a fictionalized version of you" },
    { optionA: "Be the most beloved contestant in game show history", optionB: "Be the most legendary game show host in history" },
    { optionA: "Experience the 1970s music scene at its peak", optionB: "Experience the 1990s pop culture at its peak" },
    { optionA: "Meet every character from your favorite childhood show", optionB: "Have your childhood show rebooted exactly how you'd want it" },
    { optionA: "Play yourself in a biographical film", optionB: "Have a major star play you in a biographical film" },
    { optionA: "Have the ability to enter any movie and watch it from inside", optionB: "Have the ability to bring any fictional character into real life for a day" },
    { optionA: "Be a legend in hip-hop history", optionB: "Be a legend in rock history" },
    { optionA: "Be in the writers' room for the greatest TV show ever made", optionB: "Be the showrunner of a show that runs for 20 successful seasons" },
    { optionA: "Have the world's largest autograph collection", optionB: "Have personal phone numbers of every celebrity you admire" },
    { optionA: "Star in a beloved cult classic nobody sees for 10 years", optionB: "Star in a massive blockbuster everyone forgets in 5 years" },
    { optionA: "Be the most-followed creator on every social platform", optionB: "Create content for a tiny loyal audience who changes their lives" },
    { optionA: "Be the face of the most iconic ad campaign of the century", optionB: "Voice the most iconic cartoon character of the century" },
    { optionA: "Live in Gotham City", optionB: "Live in Metropolis" },
    { optionA: "Be part of the cast that defined a generation", optionB: "Be the writer who crafted the story that defined a generation" },
    { optionA: "Have a star named after you on the Hollywood Walk of Fame", optionB: "Have a school or library named after you in your hometown" },
    { optionA: "Be in the most meme-able moment in internet history", optionB: "Create the most viral challenge in internet history" },
    { optionA: "Interview your favorite celebrity for an hour", optionB: "Have your favorite celebrity interview you about your life" },
    { optionA: "Be in a crossover episode of your two favorite shows", optionB: "See your favorite cancelled show renewed and done perfectly" },
    { optionA: "Have perfect taste in pop culture that everyone eventually agrees with", optionB: "Have controversial taste that drives passionate debate" },
    { optionA: "Voice a Pixar character", optionB: "Score a Pixar film" },
    { optionA: "Be at Woodstock in 1969", optionB: "Be at Live Aid in 1985" },
    { optionA: "Win on Jeopardy! against the best contestants ever", optionB: "Win on a game show that gives you life-changing money" },
    { optionA: "Live in the universe of your favorite book series", optionB: "Be the author of your favorite book series" },
    { optionA: "Have the most views on a single YouTube video ever", optionB: "Have the most consistently watched YouTube channel for a decade" },
    { optionA: "Be in a band that breaks up dramatically but legendarily", optionB: "Be in a band that stays together for 40 years and keeps touring" },
    { optionA: "Design the costume for the most iconic superhero film", optionB: "Score the most iconic film soundtrack of the decade" },
    { optionA: "Have the best seats at every sporting event for life", optionB: "Meet every star athlete you admire exactly once" },
    { optionA: "Be part of an ensemble cast in a beloved sitcom", optionB: "Be the lead in a dramatic prestige miniseries" },
    { optionA: "Have your life story told as an anime", optionB: "Have your life story told as a graphic novel" },
    { optionA: "Be in the most-GIF'd scene in TV history", optionB: "Deliver the most-quoted line in film history" },
    { optionA: "Have creative control over your favorite franchise reboot", optionB: "Protect your favorite franchise from ever being rebooted" },
    { optionA: "See every leaked alternate ending of your favorite films", optionB: "Have every deleted scene from your favorite films restored" },
    { optionA: "Have a cameo in every major Marvel film going forward", optionB: "Write the story for one landmark Marvel film" },
    { optionA: "Be the DJ at the most legendary party in music history", optionB: "Be the headliner at the most legendary music festival ever" },
    { optionA: "Have your favorite show get a perfect finale", optionB: "Have your favorite cancelled show get a proper season of closure" },
    { optionA: "Appear in the background of a famous paparazzi photo", optionB: "Be the photographer who takes the most iconic photo of the year" },
    { optionA: "Have a catchphrase that enters the cultural vocabulary", optionB: "Create a character that becomes a cultural icon" },
    { optionA: "Watch every Oscar Best Picture winner in a single weekend", optionB: "Watch every Cannes Palme d'Or winner in a month" },
    { optionA: "Live during the golden age of Hollywood", optionB: "Live during the streaming peak of prestige television" },
  ],

  "Nature & Environment": [
    { optionA: "Live deep in a forest for the rest of your life", optionB: "Live by the ocean for the rest of your life" },
    { optionA: "Hibernate in winter like a bear", optionB: "Never need sleep at all" },
    { optionA: "Be able to photosynthesize sunlight for energy", optionB: "Never need to drink water" },
    { optionA: "Communicate with plants", optionB: "Communicate with weather patterns" },
    { optionA: "Save one entire ancient forest", optionB: "Clean all the oceans of plastic and pollution" },
    { optionA: "Live 100% off-grid in nature", optionB: "Live in the heart of a thriving city forever" },
    { optionA: "Be able to understand every animal's communication", optionB: "Be able to feel what every plant feels" },
    { optionA: "Control the rain whenever you need it", optionB: "Control the wind wherever you go" },
    { optionA: "Witness the Earth 1 million years ago", optionB: "Witness the Earth 1 million years from now" },
    { optionA: "Have a perfect garden that never dies", optionB: "Have a wild meadow you never have to tend" },
    { optionA: "Breathe underwater indefinitely", optionB: "Fly through the air without equipment" },
    { optionA: "Live in a treehouse above the rainforest canopy", optionB: "Live in an underwater habitat on the ocean floor" },
    { optionA: "Have the ability to see perfectly in the dark", optionB: "Have the ability to sense oncoming natural disasters" },
    { optionA: "Be part of the team that reverses climate change", optionB: "Be part of the team that discovers a new clean energy source" },
    { optionA: "Grow any plant instantly from seed to full bloom", optionB: "Heal any sick or dying animal with your touch" },
    { optionA: "Survive any natural disaster unharmed", optionB: "Predict every natural disaster before it happens" },
    { optionA: "Live with a wolf pack in the wild", optionB: "Live with a pod of dolphins in the ocean" },
    { optionA: "Have rain follow you everywhere on hot days", optionB: "Have sunlight follow you everywhere on cold days" },
    { optionA: "Walk through fire without being burned", optionB: "Swim in frozen water without getting cold" },
    { optionA: "See every endangered species before they're gone", optionB: "Be the person who saves every endangered species" },
    { optionA: "Plant a forest that grows over 100 years", optionB: "Restore a coral reef that thrives for centuries" },
    { optionA: "Be a naturalist who discovers 100 new species", optionB: "Be the scientist who invents technology that heals ecosystems" },
    { optionA: "Hear the Earth's natural sounds with no human noise forever", optionB: "Experience nature in total sensory silence and stillness" },
    { optionA: "Have the strength of a bear", optionB: "Have the endurance of a migratory bird" },
    { optionA: "Live in the world's oldest rainforest", optionB: "Live on the world's oldest coral reef" },
    { optionA: "Watch a glacier form from droplets over 10,000 years", optionB: "Watch a canyon carved by a river over a million years" },
    { optionA: "Have a pet elephant who lives a natural happy life", optionB: "Have a pet whale you only ever meet in the open ocean" },
    { optionA: "Experience every season simultaneously in different zones of your backyard", optionB: "Live in a place where the season is always your favorite" },
    { optionA: "Be the world's best wildlife photographer", optionB: "Be the world's most effective environmental lawyer" },
    { optionA: "Grow food for an entire community from your land", optionB: "Build a water system that provides clean water to thousands" },
    { optionA: "Have the ability to sense ley lines and magnetic fields", optionB: "Have the ability to find underground water and minerals" },
    { optionA: "See every bioluminescent event on Earth: oceans, caves, forests", optionB: "See every volcanic eruption from a safe and perfect vantage point" },
    { optionA: "Only eat what you grow or forage", optionB: "Only eat food that has zero environmental impact" },
    { optionA: "Replenish any body of water you touch", optionB: "Purify any polluted land you walk through" },
    { optionA: "Experience a year in the life of an apex predator", optionB: "Experience a year in the life of a keystone species" },
    { optionA: "Have a sanctuary forest that can never be developed", optionB: "Have an ocean zone declared permanently protected" },
    { optionA: "Know the location of every rare mineral on Earth", optionB: "Know the location of every underground freshwater reserve on Earth" },
    { optionA: "Spend a year documenting life in the deep ocean", optionB: "Spend a year documenting life in an old-growth forest" },
    { optionA: "Live through every ice age in fast-forward", optionB: "Live through the rise of every great forest in fast-forward" },
    { optionA: "Have skin that absorbs sunlight and converts it to energy", optionB: "Have lungs that can filter and breathe any atmosphere" },
    { optionA: "Have every ecological system on Earth in perfect balance", optionB: "Have every river in the world flow cleanly to the sea" },
    { optionA: "Know every plant's medicinal properties by sight", optionB: "Know every animal's behavioral pattern by instinct" },
    { optionA: "Watch a timelapse of Earth's entire ecological history", optionB: "Watch a live feed of every biome on Earth simultaneously" },
    { optionA: "Plant a tree that becomes a forest in your lifetime", optionB: "Restore a species to a population of millions in your lifetime" },
    { optionA: "Be able to feel earthquakes before they happen", optionB: "Be able to calm storms before they make landfall" },
    { optionA: "Have access to a pristine wilderness that never changes", optionB: "Have access to a wild landscape that evolves uniquely each year" },
    { optionA: "Be the voice of the environmental movement globally", optionB: "Be the scientist whose discovery saves the biosphere" },
    { optionA: "Transform every desert into fertile land", optionB: "Protect every existing fertile land from becoming desert" },
    { optionA: "See the Milky Way from the darkest place on Earth every night", optionB: "Hear the complete silence of nature from the most remote place on Earth" },
    { optionA: "Have the metabolism of a hummingbird", optionB: "Have the lifespan of a giant tortoise" },
    { optionA: "Live in a world with no artificial light pollution", optionB: "Live in a world with no artificial noise pollution" },
    { optionA: "Have the migration instincts of a monarch butterfly", optionB: "Have the homing ability of a carrier pigeon" },
    { optionA: "Be able to grow a full garden from memory alone", optionB: "Be able to identify every plant, animal, and mineral by sight" },
    { optionA: "Regenerate any damaged ecosystem you enter", optionB: "Purify any water source you are near" },
    { optionA: "Have a bond with an apex predator that keeps you both safe", optionB: "Have a bond with a tree that communicates through the mycelium network" },
    { optionA: "Feel every rainstorm as a personal renewal", optionB: "Feel every sunrise as a personal energizing force" },
    { optionA: "Understand the underground language of mycelium networks", optionB: "Understand the acoustic communication of whale songs" },
    { optionA: "Make one river the cleanest it's ever been", optionB: "Make one city the greenest it's ever been" },
    { optionA: "Have the sensory abilities of a bat", optionB: "Have the sensory abilities of a shark" },
    { optionA: "Live your life growing one tree from seed to ancient giant", optionB: "Live your life protecting one wilderness from all harm" },
    { optionA: "Experience every biome on Earth in one continuous journey", optionB: "Spend your entire life mastering the ecology of one biome" },
    { optionA: "Have birds migrate toward wherever you need to go", optionB: "Have rivers naturally guide you wherever you need to travel" },
    { optionA: "Run as fast as a cheetah for short bursts", optionB: "Swim as fast as a sailfish indefinitely" },
    { optionA: "See the world as a bee does, with ultraviolet vision", optionB: "Hear the world as a bat does, with perfect echolocation" },
    { optionA: "Absorb nutrients from soil by walking barefoot", optionB: "Absorb oxygen directly from water by touch" },
    { optionA: "Have a lifelong connection to a specific wild place that knows you", optionB: "Have the ability to find belonging in any wild place on Earth" },
    { optionA: "Be the first person to map the full biodiversity of the deep ocean", optionB: "Be the first person to map the full biodiversity of the forest floor" },
    { optionA: "Have the instinct to always find north like a migrating bird", optionB: "Have the instinct to always find water like a desert animal" },
    { optionA: "Live in a world where rewilding has restored every continent", optionB: "Live in a world where human civilization coexists perfectly with nature" },
    { optionA: "Experience being a single-celled organism in a tidepool", optionB: "Experience being the apex predator of the open ocean for a day" },
  ],
};
