export const WYR_PART1 = {
  "Superpowers & Fantasy": [
    { optionA: "Control fire at will but be permanently immune to cold", optionB: "Control ice at will but be permanently immune to heat" },
    { optionA: "Be a powerful wizard with no physical strength", optionB: "Be a mighty warrior with zero magical ability" },
    { optionA: "Ride a dragon that only flies at night", optionB: "Ride a phoenix that only flies during storms" },
    { optionA: "Have the ability to speak to animals but they ignore your advice", optionB: "Have animals understand you perfectly but you can't understand them back" },
    { optionA: "Wield Excalibur but only against evil", optionB: "Wear the One Ring but it slowly corrupts you" },
    { optionA: "Have superhuman speed but no endurance (1 minute max)", optionB: "Have superhuman strength but no coordination" },
    { optionA: "Be able to turn invisible but lose color vision while invisible", optionB: "Be able to phase through walls but lose your sense of touch while phasing" },
    { optionA: "Have a familiar that can spy anywhere but speaks only in riddles", optionB: "Have a familiar that gives direct answers but can only travel 10 feet from you" },
    { optionA: "Rewind time by 10 seconds once per day", optionB: "Pause time for 10 seconds once per day" },
    { optionA: "Summon any mythical creature once a year", optionB: "Communicate with any mythical creature telepathically whenever you want" },
    { optionA: "Wield a sword that deals emotional damage instead of physical", optionB: "Wield a sword that deals physical damage but makes enemies feel no pain" },
    { optionA: "Have unlimited mana but only know three spells", optionB: "Know every spell ever written but have a tiny mana pool" },
    { optionA: "Be immune to all magic but lose the ability to sense it", optionB: "Detect all magic perfectly but be twice as vulnerable to it" },
    { optionA: "Live in a world where everyone has one minor superpower", optionB: "Live in a world where one person has all superpowers" },
    { optionA: "Have the power to absorb any skill by touching someone — but lose a random skill each time", optionB: "Have every skill permanently at an average level with no room to improve" },
    { optionA: "Transform into any animal but be stuck for 24 hours", optionB: "Transform into any animal freely but only for 60 seconds" },
    { optionA: "Breathe underwater but lose 20% lung capacity on land", optionB: "Survive in space but lose 20% of your lung capacity in atmosphere" },
    { optionA: "Have a bottomless bag that holds anything but you can't see inside it", optionB: "Have a bag that shows everything inside but has a 10-item limit" },
    { optionA: "Heal others of any wound but feel the pain yourself", optionB: "Heal your own wounds instantly but feel no physical sensation at all" },
    { optionA: "Become a necromancer who only raises friendly ghosts", optionB: "Become a summoner whose creatures are powerful but always sleepy" },
    { optionA: "Have a magic mirror that shows where any lost object is", optionB: "Have a magic compass that always points toward your greatest desire" },
    { optionA: "Be an elf with 500-year lifespan but age visibly after 100", optionB: "Be a dwarf with 300-year lifespan who looks eternally 30" },
    { optionA: "Have the power of prophecy but you can only see bad events", optionB: "Have the power of prophecy but your visions are always a century off" },
    { optionA: "Shoot lightning from your hands but it destroys electronics nearby", optionB: "Shoot water jets from your hands but you get mildly drenched each time" },
    { optionA: "Have an enchanted cloak that makes you seem trustworthy to all", optionB: "Have enchanted boots that take you wherever you most need to be" },
    { optionA: "Be a half-dragon who can breathe fire but can't tolerate cold", optionB: "Be a half-vampire who heals fast but must avoid sunlight during peak hours" },
    { optionA: "Discover you're the chosen one — but the prophecy is vague and contradictory", optionB: "Discover a clear prophecy about you — but it predicts mediocrity" },
    { optionA: "Have the ability to read minds but only one thought at a time, randomly chosen", optionB: "Project your thoughts into others' minds but lose control of which thought" },
    { optionA: "Control gravity in a 10-foot radius around you", optionB: "Control magnetism anywhere within sight" },
    { optionA: "Be granted one wish by a genie — but the genie is famously literal", optionB: "Be granted three wishes by a genie — but each wish shrinks your memory by 10%" },
    { optionA: "Own a magic book that writes the future but the ink fades within an hour", optionB: "Own a magic book that explains any event in the past with perfect accuracy" },
    { optionA: "Survive any fall no matter the height", optionB: "Never be injured in a vehicle accident of any kind" },
    { optionA: "Shoot energy blasts but lose 1 year of life per blast", optionB: "Fly freely but lose 1 year of life for every hour airborne" },
    { optionA: "Have the power to duplicate any physical object once per day", optionB: "Have the power to destroy any object with a touch — permanently" },
    { optionA: "Be the greatest archer to ever live, with enchanted arrows that always hit", optionB: "Be the greatest swordsman to ever live, with a blade that never dulls" },
    { optionA: "Have a talking sword that gives strategic advice but is aggressively opinionated", optionB: "Have a silent sword that doubles your combat skill with no commentary" },
    { optionA: "Control weather in a 1-mile radius but it reflects your mood", optionB: "Control weather globally but only once per month" },
    { optionA: "Have the ability to grow plants instantly but they all grow thorns", optionB: "Have the ability to wither any plant instantly and make the soil ultra-fertile" },
    { optionA: "Be a skilled alchemist who can make any potion but can't drink them yourself", optionB: "Be a skilled alchemist who can only make potions for yourself" },
    { optionA: "Become an archmage at 20 but lose all power at 40", optionB: "Develop magic slowly and reach full power at 80" },
    { optionA: "Be immune to all poisons and venoms", optionB: "Be immune to all diseases and infections" },
    { optionA: "Have a shadow that acts independently and can interact with objects", optionB: "Have a reflection that gives you advice (not always correct)" },
    { optionA: "Teleport anywhere you've been before", optionB: "Teleport anywhere you can currently see" },
    { optionA: "Have a superpower that's incredibly useful but impossible to explain to others", optionB: "Have a superpower that everyone understands but considers boring" },
    { optionA: "Conjure walls of stone at will, anywhere", optionB: "Conjure bridges of light at will, anywhere" },
    { optionA: "Have precognition for danger only — always 3 seconds ahead", optionB: "Have postcognition — see the full history of any object you touch" },
    { optionA: "Be a legendary hero whose name is remembered for 1,000 years", optionB: "Be an unknown hero whose actions change the world without credit" },
    { optionA: "Have a dragon egg that will hatch into a loyal dragon — in 50 years", optionB: "Have a baby dragon now that is loyal but constantly causes chaos" },
    { optionA: "Wield magic that's powered by music — the better you play, the stronger the spell", optionB: "Wield magic that's powered by emotion — the more you feel, the stronger the spell" },
    { optionA: "Have the power to erase one memory from anyone's mind, once per day", optionB: "Have the power to restore any one memory in anyone's mind, once per day" },
    { optionA: "Have skin that becomes as hard as diamond when you expect an attack", optionB: "Have the ability to dodge any single attack per encounter perfectly" },
    { optionA: "Be able to grant a minor wish to one stranger per week", optionB: "Be able to remove one misfortune from a stranger per week" },
    { optionA: "Exist in a fantasy world as a powerful mage but be unable to read", optionB: "Exist in a fantasy world as an expert scholar but have no magical ability" },
    { optionA: "Have the blessing of a war god — victory in battle but constant conflict finds you", optionB: "Have the blessing of a luck god — small fortune daily but no grand victories" },
    { optionA: "Have eyes that can see in any darkness", optionB: "Have ears that can hear any sound within a mile" },
    { optionA: "Have a mythical sword that absorbs the power of whatever it cuts", optionB: "Have a mythical shield that reflects any magical attack back at its caster" },
    { optionA: "Be able to create pocket dimensions the size of a closet", optionB: "Be able to access any existing space from any other space (doorways anywhere)" },
    { optionA: "Have the power to make plants grow at 1,000x speed", optionB: "Have the power to make minerals form and crystallize at 1,000x speed" },
    { optionA: "Be an all-powerful wizard inside dreams but powerless when awake", optionB: "Be an all-powerful warrior when awake but completely helpless in dreams" },
    { optionA: "Gain the memories of anyone you shake hands with", optionB: "Erase your own memories selectively, on demand" },
    { optionA: "Have unlimited stamina — never tire physically", optionB: "Have unlimited focus — never tire mentally" },
    { optionA: "Have the power of perfect disguise — look like anyone you've met", optionB: "Have the power of perfect mimicry — sound exactly like anyone you've heard" },
    { optionA: "Be able to instantly craft any tool or weapon from raw materials", optionB: "Be able to instantly repair any broken object to its original state" },
    { optionA: "Have a power that makes you invisible to cameras only", optionB: "Have a power that makes you invisible to all artificial surveillance but visible to humans" },
    { optionA: "Conjure illusions so realistic others can touch and smell them", optionB: "Conjure real objects but they vanish after 1 hour" },
    { optionA: "Have a supernatural sense of direction — always know true north and your exact location", optionB: "Have a supernatural sense of time — always know the exact time and date" },
    { optionA: "Survive on no food or sleep — but lose all enjoyment from both", optionB: "Require food and sleep but get 10x the pleasure from both" },
    { optionA: "Have a superpower that activates randomly and you can't control it", optionB: "Have a weaker but fully controlled superpower" },
    { optionA: "Be an immortal cursed to watch everyone you love age and die", optionB: "Age normally but get to reincarnate with memories intact" },
    { optionA: "Have the ability to borrow one trait from any person for 24 hours", optionB: "Have the ability to permanently gift one of your traits to anyone" },
    { optionA: "Have a magical pet that senses lies perfectly", optionB: "Have a magical pet that can find any lost person or object" },
    { optionA: "Cast a spell that controls probability in small ways — nudging luck 10% in your favor", optionB: "Cast a spell that controls certainty — guarantee one outcome per day" },
    { optionA: "Have the power to walk through fire unharmed", optionB: "Have the power to walk on water and any liquid surface" },
    { optionA: "Be able to stop aging at any age you choose", optionB: "Be able to reverse your age by 1 year per month, indefinitely" },
    { optionA: "Have a god-tier ability that only works when observed by others", optionB: "Have a moderate ability that works best when completely alone" },
    { optionA: "Command an army of constructs (golems) that obey your every word", optionB: "Command a small squad of elite magical beings with independent judgment" },
    { optionA: "Have the power to understand any written language ever devised", optionB: "Have the power to speak and be understood in any spoken language ever devised" },
    { optionA: "Find a map to a legendary treasure — but it's in a deadly dungeon", optionB: "Find a legendary treasure delivered to your door — but it comes with a mysterious curse" },
    { optionA: "Have a power that requires you to sing to activate it", optionB: "Have a power that requires you to dance to activate it" },
    { optionA: "Gain the power to merge with machines and control them", optionB: "Gain the power to animate and command any organic creature" },
  ],

  "Lifestyles & Preferences": [
    { optionA: "Live in a glass house with stunning views but zero privacy", optionB: "Live in a cozy underground home with no natural light" },
    { optionA: "Live in a vibrant city where everything is walkable", optionB: "Live on a rural farm with fresh air and total quiet" },
    { optionA: "Own 10 items total but each is perfect quality", optionB: "Own 1,000 items with variety but average quality" },
    { optionA: "Wake up naturally at 5am every day feeling fully rested", optionB: "Sleep until noon every day feeling perfectly rested" },
    { optionA: "Work a job you hate that pays extremely well", optionB: "Work a job you love that pays barely enough to live" },
    { optionA: "Always eat the same perfect meal for every breakfast", optionB: "Always eat a different random meal for every breakfast, no control" },
    { optionA: "Have a perfectly organized home but a chaotic work life", optionB: "Have a chaotic home but a perfectly organized work life" },
    { optionA: "Never need to exercise but lose all enjoyment from physical activity", optionB: "Need 3 hours of exercise daily but enjoy every second of it" },
    { optionA: "Read 100 books a year but remember none of them", optionB: "Read 5 books a year but perfectly recall every detail" },
    { optionA: "Travel to a new country every month but never feel at home anywhere", optionB: "Never travel but feel deeply at home wherever you are" },
    { optionA: "Be a night owl in a world built for early birds", optionB: "Be an early bird in a world built for night owls" },
    { optionA: "Eat only healthy food you don't enjoy", optionB: "Eat only food you love that has zero nutritional value" },
    { optionA: "Have a perfectly consistent routine, every day identical", optionB: "Have a completely spontaneous life with no predictability" },
    { optionA: "Live in a tiny apartment in the most exciting neighborhood in the world", optionB: "Live in a mansion in the most boring suburb imaginable" },
    { optionA: "Always dress impeccably but feel uncomfortable in your clothes", optionB: "Always dress for comfort but get judged on your appearance constantly" },
    { optionA: "Be a minimalist — own only 50 things", optionB: "Be a maximalist — every room full of curated collections" },
    { optionA: "Have an analog lifestyle — no smartphones, no streaming, no social media", optionB: "Be hyper-connected — instant access to everything digital, always online" },
    { optionA: "Spend weekends solo, completely recharging in solitude", optionB: "Spend weekends in lively group activities, always surrounded by people" },
    { optionA: "Cook every meal at home from scratch", optionB: "Eat every meal at a restaurant or takeout" },
    { optionA: "Live near the ocean but have no interest in water activities", optionB: "Live in the mountains and love hiking but hate cold weather" },
    { optionA: "Have a wardrobe of 5 perfect outfits you wear in rotation", optionB: "Have a wardrobe of 200 items but never feel like you have anything to wear" },
    { optionA: "Keep every space spotlessly clean but have severe cleaning anxiety", optionB: "Be comfortable in clutter with zero cleaning stress" },
    { optionA: "Have a social life that's full but exhausting", optionB: "Have a quiet social life that's limited but deeply satisfying" },
    { optionA: "Own a pet that requires 4 hours of care daily but is endlessly loving", optionB: "Own a pet that's completely self-sufficient but rarely interacts with you" },
    { optionA: "Be a morning person who gets 3 magical productive hours at dawn", optionB: "Be a night owl who hits peak creativity at midnight" },
    { optionA: "Live car-free in a transit-heavy city", optionB: "Live car-dependent in a sprawling suburb" },
    { optionA: "Have one deeply close friend", optionB: "Have 50 casual friends" },
    { optionA: "Work from home permanently with no office contact", optionB: "Work in an office permanently with no remote option" },
    { optionA: "Follow a strict daily budget but never worry about big purchases", optionB: "Spend freely on daily luxuries but stress constantly about big expenses" },
    { optionA: "Live in a different city every year", optionB: "Live in the same neighborhood your entire life" },
    { optionA: "Have a garden that requires daily tending but produces all your food", optionB: "Have a low-maintenance indoor plant that does nothing practical" },
    { optionA: "Maintain a bullet journal and physical calendar for everything", optionB: "Use AI-powered apps that manage your schedule entirely" },
    { optionA: "Spend your free time creating things (art, music, building)", optionB: "Spend your free time consuming things (books, shows, games)" },
    { optionA: "Live in a place with four dramatic seasons", optionB: "Live in a place with perpetual mild, pleasant weather" },
    { optionA: "Wake up remembering all your dreams in vivid detail", optionB: "Never remember dreams but wake up feeling profoundly well-rested" },
    { optionA: "Be a social butterfly who energizes rooms but needs alone time to recover", optionB: "Be quietly magnetic — people are drawn to you in small groups" },
    { optionA: "Only own physical books — no e-books or audiobooks", optionB: "Only use digital books — no physical clutter" },
    { optionA: "Have a perfectly curated wardrobe managed by a stylist", optionB: "Have total style freedom but no guidance — hit or miss every day" },
    { optionA: "Have a rigorous morning routine (90 min): journal, workout, meditate, cold shower", optionB: "Wake up and immediately start your day with zero routines" },
    { optionA: "Live near your family but lose some independence", optionB: "Live far from family but have complete independence" },
    { optionA: "Have a career with total autonomy but no collaboration", optionB: "Have a career that requires constant collaboration but you're never autonomous" },
    { optionA: "Sleep 6 hours and feel fine but never experience a deeply satisfying long sleep", optionB: "Need 10 hours of sleep but every night is deeply restorative" },
    { optionA: "Live in a walkable neighborhood with high cost of living", optionB: "Live in a driveable suburb with low cost of living" },
    { optionA: "Have a flexible schedule with unpredictable income", optionB: "Have a rigid 9-5 with completely predictable income" },
    { optionA: "Keep every digital file perfectly organized in folders", optionB: "Keep everything in one massive folder and rely on search" },
    { optionA: "Be a homebody who creates a perfect sanctuary at home", optionB: "Be an explorer who is rarely home but always experiencing something new" },
    { optionA: "Have a social media presence that's carefully curated and large", optionB: "Have zero social media but a rich offline social life" },
    { optionA: "Take cold showers exclusively — energizing, dreaded daily", optionB: "Take only hot baths — indulgent, time-consuming daily" },
    { optionA: "Have a subscription to every streaming service available", optionB: "Have no streaming — only physical media you curate yourself" },
    { optionA: "Spend money on experiences (travel, concerts, dining)", optionB: "Spend money on objects (art, gadgets, fashion, furniture)" },
    { optionA: "Work in complete silence always", optionB: "Always work with background noise (music, podcasts, ambient sound)" },
    { optionA: "Live with multiple roommates who are great but rarely give you privacy", optionB: "Live alone with total privacy but occasional loneliness" },
    { optionA: "Own a luxury item in one category (car, watch, bag) and be frugal everywhere else", optionB: "Be moderately comfortable in every category with no luxury items" },
    { optionA: "Have a hobby that takes 20 hours a week but brings deep joy", optionB: "Have a hobby that takes 2 hours a week but brings mild, consistent satisfaction" },
    { optionA: "Always be early to everything — 15+ minutes ahead", optionB: "Always arrive exactly on time to everything — perfectly punctual" },
    { optionA: "Have a digital detox one week per month — no internet at all", optionB: "Be connected 24/7 with no enforced breaks" },
    { optionA: "Have a capsule wardrobe of neutral tones", optionB: "Wear only bold, colorful, statement outfits" },
    { optionA: "Live on a houseboat — scenic, unconventional, rocking gently", optionB: "Live in a treehouse — elevated, isolated, surrounded by nature" },
    { optionA: "Be known as the friend who always hosts", optionB: "Be known as the friend who always shows up but never hosts" },
    { optionA: "Have an afternoon nap culture — 30-min nap every day", optionB: "Have a no-nap lifestyle — power through with coffee and movement" },
    { optionA: "Have a life partner who is your complete opposite in lifestyle", optionB: "Have a life partner who is your twin in lifestyle preferences" },
    { optionA: "Be an avid journaler who writes daily private reflections", optionB: "Never journal — process everything through conversation with others" },
    { optionA: "Have every meal planned a week in advance", optionB: "Decide what to eat only when you're already hungry" },
    { optionA: "Own a home outright with no debt but in a mediocre location", optionB: "Rent in the perfect location forever with no ownership" },
    { optionA: "Wake up to complete silence every morning", optionB: "Wake up to the sound of a lively, noisy city every morning" },
    { optionA: "Have an elaborate self-care routine — 2 hours a day on yourself", optionB: "Have a basic 10-minute routine with no fuss" },
    { optionA: "Be a planner — vacations booked 6 months out, itinerary in hand", optionB: "Be a spontaneous traveler — decide destination day-of, figure it out as you go" },
    { optionA: "Have a tidy desk but a messy bag or purse", optionB: "Have a messy desk but a perfectly organized bag or purse" },
    { optionA: "Be an early adopter — always have the newest tech the day it launches", optionB: "Use tech until it dies — never upgrade unless forced" },
    { optionA: "Live in a co-living community with shared resources and communal meals", optionB: "Live in a self-sufficient private home with no shared resources" },
    { optionA: "Follow a strict diet with clear rules and meal prepping", optionB: "Eat intuitively — no rules, just listen to your body" },
    { optionA: "Spend your evenings reading and reflecting", optionB: "Spend your evenings socializing and experiencing things" },
    { optionA: "Have a uniform — wear the same outfit style every day (like Steve Jobs)", optionB: "Express yourself differently through clothing every single day" },
    { optionA: "Be a city person who thrives on stimulation and access", optionB: "Be a nature person who thrives on quiet and open space" },
    { optionA: "Have only physical cash — no cards or digital payments", optionB: "Be entirely cashless — cards and apps for everything" },
    { optionA: "Be early to bed, early to rise — 9pm–5am sleep schedule", optionB: "Be late to bed, late to rise — 2am–10am sleep schedule" },
    { optionA: "Have a life filled with meaningful rituals and traditions", optionB: "Have a life of constant novelty with no repeated rituals" },
  ],

  "Future, Past & Time": [
    { optionA: "Visit ancient Rome at its peak for one week, as an observer", optionB: "Visit Earth in 500 years for one week, as an observer" },
    { optionA: "Know the exact date of your own death", optionB: "Know the cause of your own death but not when it will happen" },
    { optionA: "Relive your best memory — but remember that it already ended", optionB: "Skip your worst memory — but lose everything you learned from it" },
    { optionA: "Go back and change one decision from your past", optionB: "Get a preview of the best decision you could make in your future" },
    { optionA: "Meet your 10-year-older self for one hour", optionB: "Receive a letter written by your 10-year-older self" },
    { optionA: "Live through the Renaissance as a wealthy merchant", optionB: "Live through the 1920s as a creative in Paris" },
    { optionA: "Be able to send one text message to your past self — 10 years ago", optionB: "Receive one text message from your future self — 10 years from now" },
    { optionA: "Know which of your current beliefs will turn out to be wrong", optionB: "Know which of your current beliefs will be completely vindicated" },
    { optionA: "Have your memory wiped and relive your 20s with total freedom", optionB: "Keep all your memories and relive your 20s with full wisdom" },
    { optionA: "Travel to any historical event as an invisible spectator", optionB: "Travel to any future event as an invisible spectator" },
    { optionA: "Experience one full day in a city 200 years in the future", optionB: "Experience one full day in a city 200 years in the past" },
    { optionA: "Know which inventions in your lifetime will change humanity most", optionB: "Know which inventions you personally could help bring about" },
    { optionA: "Live in the era of your greatest historical fascination", optionB: "Live in the era your descendants will consider a golden age" },
    { optionA: "See a one-minute clip from 100 years in the future — no context, no explanation", optionB: "See a one-minute clip from 100 years in the past — full context provided" },
    { optionA: "Be able to pause your life and explore a parallel timeline for 30 days", optionB: "Be able to skip forward 30 days any time life gets difficult" },
    { optionA: "Know what your life would look like if you'd made different major choices", optionB: "Know that your current path is definitively the best one available to you" },
    { optionA: "Meet your ancestors from 500 years ago and talk for an hour", optionB: "Meet your descendants from 500 years from now and talk for an hour" },
    { optionA: "Have the ability to experience any historical moment as if you were there — but never change it", optionB: "Have the ability to change one moment in history — but experience the unknown consequences" },
    { optionA: "Witness the birth of any civilization", optionB: "Witness the founding of any religion or philosophy at its origin" },
    { optionA: "Know which of your current friendships will last a lifetime", optionB: "Know which relationships will be the most transformative but temporary" },
    { optionA: "Live as a medieval knight — honor, danger, rigid hierarchy", optionB: "Live as a medieval monk — peace, learning, isolation" },
    { optionA: "Have no memory of your past before age 12", optionB: "Have perfect memory of every moment of your life since birth" },
    { optionA: "Jump 50 years into the future for one day — then return", optionB: "Jump 50 years into the past for one day — then return" },
    { optionA: "Know what technology will replace your current career", optionB: "Know what new career will emerge that you'd be perfect for" },
    { optionA: "Be present at the birth of the internet — could you influence it?", optionB: "Be present at the founding of the printing press — could you influence it?" },
    { optionA: "Relive one year of your life with full memory but no ability to change anything", optionB: "Forget one year of your life entirely — the memories simply gone" },
    { optionA: "Know the moment you will meet the most important person in your life", optionB: "Know the moment your biggest opportunity will arrive" },
    { optionA: "Have a time machine that works but makes you 1 month older per trip", optionB: "Have a time machine that's free to use but takes you to a random time within 100 years" },
    { optionA: "See the world 10 minutes from now — always 10 minutes ahead", optionB: "See the world 10 minutes ago — always able to review the very recent past" },
    { optionA: "Live through the Space Age of the 1960s and feel that collective wonder", optionB: "Live through the early Internet era of the 1990s and feel that frontier energy" },
    { optionA: "Know the most important historical event that has been completely covered up", optionB: "Know the most important historical event that has been completely misunderstood" },
    { optionA: "Have the option to live your life backwards — from old age to birth", optionB: "Live your current life twice, knowing everything the second time" },
    { optionA: "Be a time traveler who can only observe — never interact", optionB: "Be a time traveler who can interact freely but can only visit one era" },
    { optionA: "Know if humanity survives the next 200 years — but not how", optionB: "Know exactly how humanity survives — but not whether it does" },
    { optionA: "Be frozen in time for 100 years and wake up to a changed world", optionB: "Slowly experience the next 100 years, watching everything transform" },
    { optionA: "Have a 5-minute conversation with Shakespeare", optionB: "Have a 5-minute conversation with a person living in 2200" },
    { optionA: "Know what Earth looked like 10,000 years before recorded history at your current location", optionB: "Know what your current location will look like 10,000 years in the future" },
    { optionA: "Experience the peak of ancient Alexandria's library — total human knowledge of that era", optionB: "Experience the peak of Silicon Valley — total innovation energy of the 2010s" },
    { optionA: "Go back in time to your first day of school knowing everything you know now", optionB: "Go back to your first day at your current (or best) job knowing everything you know now" },
    { optionA: "Have your biography written about your real life as it is", optionB: "Have a fictional biography written that's more dramatic and interesting than your real life" },
    { optionA: "Witness the end of the last ice age", optionB: "Witness the construction of the first great human city" },
    { optionA: "Be told by a reliable oracle: your greatest achievement is still ahead of you", optionB: "Be told by a reliable oracle: your greatest achievement is already behind you" },
    { optionA: "Know which regrets you'll have on your deathbed", optionB: "Know which moments you'll cherish most on your deathbed" },
    { optionA: "Be transported to a future where humans have solved climate change — see how", optionB: "Be transported to a future where climate change was catastrophic — witness the aftermath" },
    { optionA: "Have access to a detailed archive of your entire life from age 5 onward — every moment recorded", optionB: "Have access to a detailed prediction of every major event in your life for the next 20 years" },
    { optionA: "Travel to the moment a great art masterpiece was being created and watch", optionB: "Travel to the moment a great scientific discovery was being made and watch" },
    { optionA: "Know which technologies you currently use will still exist in 50 years", optionB: "Know which technologies don't exist yet that will completely change your life" },
    { optionA: "Live through one decade of the future and return — changed", optionB: "Receive a documentary film about one decade of the future — informed" },
    { optionA: "Remember your past lives (if they existed)", optionB: "Preview your next life (if it exists)" },
    { optionA: "Have a map of every major crossroads decision in your life — paths taken and untaken", optionB: "Have a map of every major crossroads decision in your life — only the outcomes of each path, no details" },
    { optionA: "Experience a week in the daily life of a Roman plebeian", optionB: "Experience a week in the daily life of a Roman senator" },
    { optionA: "Witness the moment humans first landed on the moon — in mission control", optionB: "Witness the moment humans first land on Mars — wherever it happens" },
    { optionA: "Have the ability to revisit any moment from your past in full sensory detail — but only watch", optionB: "Have the ability to visit any moment from a stranger's past — with their permission" },
    { optionA: "Know whether artificial general intelligence will be developed in your lifetime", optionB: "Know what the first post-AGI decade of human history will look like" },
    { optionA: "Live your life 10 years earlier (born a decade sooner)", optionB: "Live your life 10 years later (born a decade later)" },
    { optionA: "Experience the world's first city 6,000 years ago, as a resident", optionB: "Experience the world's last city 600 years from now, as a resident" },
    { optionA: "Know precisely how your childhood shaped your personality", optionB: "Know precisely how your adulthood will continue to shape you" },
    { optionA: "Be able to age backwards from your current age to 0 — living that life in reverse", optionB: "Be able to age forward from your current age to 120 — living a double-length second half" },
    { optionA: "Visit the moment of your greatest personal success and relive the feeling", optionB: "Visit the moment of your greatest personal failure with the wisdom to understand it" },
    { optionA: "Have 5 more years added to your past — an extra 5 years in your 20s", optionB: "Have 5 more years guaranteed added to your future at full health" },
    { optionA: "Know how the current political era of your country will end", optionB: "Know how the next political era of your country will begin" },
    { optionA: "Be a historian who can witness any event firsthand — but is cursed to never be believed", optionB: "Be a historian who is always believed — but can only research through documents, never witness events" },
    { optionA: "Discover that a historical event you care about happened very differently than recorded", optionB: "Confirm that a historical event you care about happened exactly as recorded" },
    { optionA: "Have a time loop — the same perfect day repeating until you choose to exit", optionB: "Have a time scramble — every day pulls you to a random year in your own lifetime" },
    { optionA: "Experience one day in 1920s Harlem during the Renaissance", optionB: "Experience one day in 1970s New York during the birth of hip-hop" },
    { optionA: "Know what the dominant language of humanity will be in 300 years", optionB: "Know whether human languages will diversify or converge in 300 years" },
    { optionA: "Have an extra 10 years of healthy life that only you can experience — no sharing it", optionB: "Have 5 extra years that you can give, in chunks, to people you love" },
    { optionA: "See your family tree going back 1,000 years — names, faces, stories", optionB: "See your family tree going forward 200 years — names, faces, stories" },
    { optionA: "Know which currently unknown person alive today will reshape history", optionB: "Know which currently famous person alive today will be forgotten within 50 years" },
    { optionA: "Receive a 10-second vision of the future every morning when you wake up", optionB: "Receive a 10-second vision of the past every morning when you wake up" },
    { optionA: "Be transported to the moment humans first harnessed fire", optionB: "Be transported to the moment humans first developed written language" },
    { optionA: "Have the memories of a person who lived 200 years ago — full sensory recall", optionB: "Have a person 200 years from now hold your current memories — and they can contact you once" },
    { optionA: "Know which of today's social norms will be considered deeply wrong in 100 years", optionB: "Know which of today's fringe ideas will be mainstream in 100 years" },
    { optionA: "Be able to fast-forward through any boring period of your life instantly", optionB: "Be able to slow down any wonderful period of your life to last twice as long" },
    { optionA: "Have your consciousness uploaded and preserved for 1,000 years, then restored", optionB: "Live continuously for 1,000 years in the same body, experiencing every change" },
    { optionA: "Experience the fall of Constantinople", optionB: "Experience the fall of the Berlin Wall" },
    { optionA: "Know what the world thought of you 50 years after your death", optionB: "Know what the world thought of you 50 years before your birth" },
    { optionA: "Have the ability to bookmark any moment in your life and return to experience it once more", optionB: "Have the ability to leave a message for your past self at any age you choose" },
  ],

  "Skills & Talents": [
    { optionA: "Master any one instrument in the world at a legendary level", optionB: "Play every instrument at a competent, enjoyable level" },
    { optionA: "Be able to learn any physical skill in 1 week", optionB: "Be able to learn any intellectual skill in 1 week" },
    { optionA: "Have perfect pitch and musical intuition", optionB: "Have perfect rhythm and percussive mastery" },
    { optionA: "Be the world's greatest painter but be unable to describe your work verbally", optionB: "Be the world's greatest writer but be unable to create any visual art" },
    { optionA: "Have elite analytical skills — think like the world's best mathematician", optionB: "Have elite creative skills — think like the world's most original artist" },
    { optionA: "Master one martial art to a grandmaster level", optionB: "Master every martial art to a black-belt level" },
    { optionA: "Have the surgical precision of the world's best surgeon", optionB: "Have the diagnostic intuition of the world's best physician" },
    { optionA: "Speak 10 languages fluently but have average skill in your native one", optionB: "Speak only your native language but with extraordinary eloquence and command" },
    { optionA: "Be a brilliant composer who can't perform music", optionB: "Be a brilliant performer who can't compose an original piece" },
    { optionA: "Have the coding ability to build anything — but only solo, never collaborate", optionB: "Have extraordinary collaborative ability — lead any technical team to brilliance, but can't code alone" },
    { optionA: "Be an elite chef with a palate so refined you can no longer enjoy simple food", optionB: "Be an enthusiastic home cook who brings joy to every meal without technical perfection" },
    { optionA: "Learn any new language in 24 hours — but forget it after a year", optionB: "Learn any new language in 6 months — but retain it perfectly forever" },
    { optionA: "Have the physical talent to compete in any one Olympic sport", optionB: "Have the physical talent to compete in every Olympic sport at a qualifying level" },
    { optionA: "Be able to read and retain any book in 30 minutes", optionB: "Be able to deeply understand and synthesize any book in 3 hours" },
    { optionA: "Have perfect memory for faces — never forget anyone you've met", optionB: "Have perfect memory for names — never forget anyone's name" },
    { optionA: "Master chess to grandmaster level", optionB: "Master poker to world series level" },
    { optionA: "Have extraordinary empathy — deeply understand others' emotions", optionB: "Have extraordinary analytical clarity — deeply understand systems and patterns" },
    { optionA: "Be an expert at building and making things with your hands (carpentry, metalwork, crafts)", optionB: "Be an expert at designing and planning things on paper (architecture, engineering, systems)" },
    { optionA: "Have the ability to write code that solves any problem given enough time", optionB: "Have the ability to explain any complex concept so that anyone can understand it" },
    { optionA: "Master deep focus — enter flow state on command for hours", optionB: "Master broad attention — hold 20 tasks in mind simultaneously without losing any" },
    { optionA: "Have perfect public speaking — command any room, any size", optionB: "Have perfect one-on-one communication — deeply connect with any individual instantly" },
    { optionA: "Be a world-class negotiator who never loses a deal", optionB: "Be a world-class mediator who resolves any conflict" },
    { optionA: "Have the athletic talent of a professional footballer (soccer player)", optionB: "Have the athletic talent of a professional basketball player" },
    { optionA: "Be an exceptional writer whose work is dense, complex, and beloved by critics", optionB: "Be an exceptional writer whose work is accessible and beloved by millions" },
    { optionA: "Master drawing to the level of the great Renaissance masters", optionB: "Master photography to the level of the greatest photographers in history" },
    { optionA: "Have the skill to build a complete house by hand", optionB: "Have the skill to repair and restore any mechanical or electronic device" },
    { optionA: "Have perfect intuition about people — know instantly if someone is trustworthy", optionB: "Have perfect intuition about situations — know instantly what action is correct" },
    { optionA: "Be the best dancer in any style you choose — but only that one style", optionB: "Be an above-average dancer in every style that exists" },
    { optionA: "Have the financial modeling skills of the world's best investment analyst", optionB: "Have the entrepreneurial instincts of the world's most successful founder" },
    { optionA: "Master speed-reading at 10,000 words per minute with full comprehension", optionB: "Master slow, deep reading — absorb 10 pages per hour with perfect synthesis" },
    { optionA: "Be the world's best at strategy games (chess, Go, poker)", optionB: "Be the world's best at reflex games (fighting games, FPS, racing)" },
    { optionA: "Have elite persuasion skills — change anyone's mind over time", optionB: "Have elite logic skills — construct airtight arguments no one can refute" },
    { optionA: "Master one craft so deeply you produce work that lasts centuries", optionB: "Master many crafts enough that your daily life is filled with handmade beauty" },
    { optionA: "Have the vocal range and control of the world's greatest opera singer", optionB: "Have the vocal range and control of the world's greatest pop vocalist" },
    { optionA: "Be exceptionally skilled at starting things — ideas, businesses, movements", optionB: "Be exceptionally skilled at finishing things — execution, delivery, completion" },
    { optionA: "Have extraordinary skill at reading nonverbal communication", optionB: "Have extraordinary skill at crafting precise verbal communication" },
    { optionA: "Learn any physical skill by watching it once", optionB: "Learn any intellectual skill by reading about it once" },
    { optionA: "Have perfect spatial reasoning — visualize any 3D structure mentally", optionB: "Have perfect verbal reasoning — parse and produce any linguistic structure perfectly" },
    { optionA: "Be a master of improv — sharp, funny, spontaneous in any moment", optionB: "Be a master of scripted performance — deliver any written material with perfection" },
    { optionA: "Have elite scientific research skills — design the perfect experiment for any question", optionB: "Have elite engineering skills — build the perfect solution to any problem" },
    { optionA: "Have the ability to pick up any musical style perfectly after hearing it once", optionB: "Have the ability to compose entirely original music in any style from imagination alone" },
    { optionA: "Be a world-class teacher of a single subject", optionB: "Be a competent teacher of every subject" },
    { optionA: "Have the culinary creativity of a Michelin-starred chef — bold, experimental", optionB: "Have the culinary comfort mastery of the world's best home cook — perfect classics" },
    { optionA: "Master the art of debate — always find the strongest argument", optionB: "Master the art of dialogue — always find common ground" },
    { optionA: "Have the endurance of an ultra-marathon runner", optionB: "Have the explosive power of an elite sprinter" },
    { optionA: "Be an extraordinary generalist — good at everything, master of nothing", optionB: "Be an extraordinary specialist — world's best at one thing, average at all else" },
    { optionA: "Have the pattern recognition of a grandmaster chess player applied to real-world situations", optionB: "Have the statistical intuition of the world's best data scientist applied to real-world decisions" },
    { optionA: "Master lockpicking and sleight of hand — physical dexterity at its finest", optionB: "Master memory techniques — hold and recall 10,000 data points perfectly" },
    { optionA: "Have the improvisational skill of the world's greatest jazz musician", optionB: "Have the compositional skill of the world's greatest classical composer" },
    { optionA: "Be able to solve any problem involving numbers instantly in your head", optionB: "Be able to solve any problem involving words and language instantly in your head" },
    { optionA: "Have the investigative skill of the world's greatest detective — see what others miss", optionB: "Have the predictive skill of the world's greatest forecaster — know what's coming" },
    { optionA: "Master any game instantly — board games, video games, card games — the moment you sit down", optionB: "Master any sport instantly — the moment you put on the gear" },
    { optionA: "Be the world's best at drawing people out — interviews, conversations, getting stories", optionB: "Be the world's best at synthesizing information — turning raw data into insight" },
    { optionA: "Have the hand-eye coordination of the world's greatest surgeon combined with the speed of the world's fastest typist", optionB: "Have the mental calculation speed of the world's fastest mental mathematician combined with the memory of the world's greatest mnemonist" },
    { optionA: "Be an elite wilderness survival expert — thrive in any environment", optionB: "Be an elite urban survival expert — thrive in any city, any situation" },
    { optionA: "Have mastery of nonverbal communication — your body language is perfectly calibrated always", optionB: "Have mastery of paraverbal communication — your tone, pacing, and voice are perfectly calibrated always" },
    { optionA: "Be the greatest living sculptor — your hands shape marble and clay into timeless works", optionB: "Be the greatest living filmmaker — your eye for image and story is unmatched" },
    { optionA: "Have perfect taste — your aesthetic judgment in any domain is impeccable", optionB: "Have perfect execution — whatever you design, you can build to perfection" },
    { optionA: "Be world-class at a skill that was once highly valued but is now obsolete", optionB: "Be world-class at a skill that will become highly valuable in 20 years but isn't yet" },
    { optionA: "Have encyclopedic knowledge of history — every date, name, event", optionB: "Have encyclopedic knowledge of science — every theory, discovery, equation" },
    { optionA: "Master the ancient art of rhetoric — persuade through structure and beauty of argument", optionB: "Master the modern art of copywriting — persuade through simplicity and precision" },
    { optionA: "Be the world's most talented woodworker — every joint perfect, every surface flawless", optionB: "Be the world's most talented glassblower — every form ethereal and precise" },
    { optionA: "Have the speed-reading ability to absorb a library in a year", optionB: "Have the deep-reading ability to understand one great book more profoundly than anyone alive" },
    { optionA: "Master the skill of active listening — people feel more understood by you than anyone else", optionB: "Master the skill of storytelling — any story you tell becomes unforgettable" },
    { optionA: "Be an elite sprinter — fastest human on Earth", optionB: "Be an elite climber — able to scale any surface in the world" },
    { optionA: "Have the cognitive endurance to think deeply about a problem for 12 hours straight", optionB: "Have the cognitive flexibility to switch between 10 difficult problems rapidly without losing quality" },
    { optionA: "Master origami to the level of creating any form, however complex, from memory", optionB: "Master calligraphy in any script to the level of a living art form" },
    { optionA: "Be exceptionally skilled at reading financial statements — see a company's true health at a glance", optionB: "Be exceptionally skilled at reading people — see a person's true character at a glance" },
    { optionA: "Have perfect absolute spatial memory — never get lost anywhere in the world", optionB: "Have perfect absolute temporal memory — remember the exact time of every event in your life" },
    { optionA: "Be the world's best at generating ideas — 100 novel ideas per hour", optionB: "Be the world's best at evaluating ideas — immediately identify what will work and what won't" },
    { optionA: "Have the physical grace of the world's greatest ballet dancer", optionB: "Have the physical power of the world's greatest powerlifter" },
    { optionA: "Master the skill of asking the perfect question in any situation", optionB: "Master the skill of giving the perfect answer to any question" },
    { optionA: "Have extraordinary skill at building and maintaining systems and processes", optionB: "Have extraordinary skill at breaking and disrupting systems and processes creatively" },
    { optionA: "Be a master of one domain so deep that your understanding exceeds everyone alive", optionB: "Be deeply competent across 10 domains — a true polymath" },
    { optionA: "Have the teaching ability to make any complex concept click for anyone", optionB: "Have the learning ability to master any complex concept faster than anyone" },
    { optionA: "Be able to write any style of code perfectly — the best programmer alive", optionB: "Be able to design any system perfectly — the best systems architect alive" },
    { optionA: "Have the world's most precise eye for detail — catch every error, every flaw", optionB: "Have the world's best eye for the big picture — see the whole pattern instantly" },
    { optionA: "Master the physical skill of parkour — move through any environment fluidly", optionB: "Master the physical skill of gymnastics — control your body in any orientation" },
  ],
};
